import Link from "next/link"
import { ArrowLeft, CheckCircle2, GraduationCap, School, Sparkles } from "lucide-react"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"

const tiers = [
  { name: "Free", icon: GraduationCap, note: "Experience the preparation system before subscribing.", features: ["Diagnostic and starter question bank", "Limited interview practice", "Basic feedback", "Limited Gemini Live usage", "Basic tutor recommendations"] },
  { name: "Pro", icon: Sparkles, note: "The complete personalised preparation system.", features: ["Full Personal AI Tutor and long-term preparation profile", "All full papers and adaptive interventions", "Mistake DNA and Progress Proof", "Detailed interview and essay analysis", "Tutorial Lab and Daily Challenge", "Application Digital Twin and defence practice", "Mock Interview Day and supercurricular coach"] },
  { name: "School", icon: School, note: "Teacher-supported preparation across a cohort.", features: ["Everything in Pro", "Teacher Coach and review workflow", "Human + AI feedback records", "Cohort-ready cloud data model", "Parent-safe progress summaries", "School subscription tier already supported by billing"] },
]

export default function PremiumPage() {
  return <main className="min-h-screen bg-[#f5f7f7] text-[#172b3a]"><header className="border-b bg-white"><div className="mx-auto flex max-w-6xl items-center justify-between px-4 py-4"><Button asChild variant="ghost"><Link href="/tutor"><ArrowLeft />Personal Tutor</Link></Button><Badge variant="outline">Plans</Badge></div></header><div className="mx-auto max-w-6xl space-y-7 px-4 py-10"><section className="text-center"><p className="text-xs font-bold uppercase tracking-[.18em] text-[#147d91]">Pay for personalisation, not just more questions</p><h1 className="mx-auto mt-2 max-w-4xl font-serif text-4xl font-bold sm:text-5xl">The paid value is the tutor that learns from everything you do.</h1><p className="mx-auto mt-4 max-w-3xl text-slate-600">Pro combines tests, interviews, essays, application evidence and mistake patterns into one persistent preparation system. Practice scores remain practice evidence, not admissions predictions.</p></section><section className="grid gap-5 lg:grid-cols-3">{tiers.map(tier => { const Icon = tier.icon; return <Card key={tier.name} className={tier.name === "Pro" ? "border-[#147d91] shadow-[0_20px_60px_rgba(16,42,67,.10)]" : "shadow-none"}><CardHeader><Icon className="size-6 text-[#147d91]" /><div className="flex items-center gap-2"><CardTitle className="font-serif text-3xl">{tier.name}</CardTitle>{tier.name === "Pro" && <Badge>Core experience</Badge>}</div><CardDescription>{tier.note}</CardDescription></CardHeader><CardContent className="space-y-3">{tier.features.map(item => <p key={item} className="flex gap-2 text-sm leading-6"><CheckCircle2 className="mt-1 size-4 shrink-0 text-emerald-600" />{item}</p>)}<Button asChild className="mt-3 w-full" variant={tier.name === "Pro" ? "default" : "outline"}><Link href={tier.name === "School" ? "/teacher-coach" : "/account"}>{tier.name === "School" ? "Open teacher tools" : "Account & billing"}</Link></Button></CardContent></Card>})}</section></div></main>
}
