"use client"

import { useEffect, useState } from "react"
import Link from "next/link"
import { ArrowLeft, CheckCircle2, Loader2, RefreshCw, UserCheck } from "lucide-react"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Textarea } from "@/components/ui/textarea"

type Order={id:string;user_id:string;status:string;source_type:string;title:string;notes:string;reviewer_name?:string|null;feedback?:string|null;created_at:string}
type QueueResponse={orders?:Order[];error?:string}
type SaveResponse={ok?:boolean;error?:string}

export default function ExpertReviewAdminPage(){
 const[orders,setOrders]=useState<Order[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState("")
 async function load(){setLoading(true);setError("");try{const r=await fetch("/api/admin/expert-reviews",{cache:"no-store"});const x=await r.json() as QueueResponse;if(!r.ok)throw new Error(x.error||"Could not load review queue");setOrders(x.orders||[])}catch(e){setError(e instanceof Error?e.message:"Could not load review queue")}finally{setLoading(false)}}
 useEffect(()=>{void load()},[])
 async function save(order:Order){const r=await fetch("/api/admin/expert-reviews",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:order.id,status:order.status,reviewerName:order.reviewer_name,feedback:order.feedback})});const x=await r.json() as SaveResponse;if(!r.ok){setError(x.error||"Could not save review");return}await load()}
 return <main className="min-h-screen bg-[#f5f7f7] text-[#172b3a]"><header className="border-b bg-white"><div className="mx-auto flex max-w-6xl items-center justify-between px-4 py-4"><Button asChild variant="ghost"><Link href="/admin"><ArrowLeft/>Admin</Link></Button><Button variant="outline" onClick={()=>void load()}><RefreshCw/>Refresh</Button></div></header><div className="mx-auto max-w-6xl space-y-6 px-4 py-8"><section><Badge><UserCheck className="size-3.5"/>Paid expert reviews</Badge><h1 className="mt-3 font-serif text-4xl font-bold">Human review queue</h1><p className="mt-2 max-w-3xl text-sm text-slate-600">Paid review requests appear here after Stripe confirms checkout. Add reviewer feedback and mark the order completed; the student sees the result in Expert Review.</p></section>{error&&<div className="rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm">{error}</div>}{loading?<Card><CardContent className="flex items-center gap-2 p-6"><Loader2 className="animate-spin"/>Loading…</CardContent></Card>:<div className="space-y-4">{orders.map((order,index)=><Card key={order.id}><CardHeader><div className="flex flex-wrap items-center gap-2"><Badge>{order.status.replace(/_/g," ")}</Badge><Badge variant="outline">{order.source_type.replace(/_/g," ")}</Badge><span className="text-xs text-slate-400">{new Date(order.created_at).toLocaleString("en-GB")}</span></div><CardTitle className="font-serif text-2xl">{order.title}</CardTitle><CardDescription>{order.notes||"No requested focus supplied."}</CardDescription></CardHeader><CardContent className="grid gap-3"><div className="grid gap-3 md:grid-cols-2"><label><span className="mb-1 block text-xs font-bold uppercase tracking-wider">Status</span><select value={order.status} onChange={e=>setOrders(current=>current.map((x,i)=>i===index?{...x,status:e.target.value}:x))} className="h-10 w-full rounded-md border bg-white px-3 text-sm">{["queued","in_review","completed","cancelled","refunded"].map(x=><option key={x} value={x}>{x.replace(/_/g," ")}</option>)}</select></label><label><span className="mb-1 block text-xs font-bold uppercase tracking-wider">Reviewer</span><input value={order.reviewer_name||""} onChange={e=>setOrders(current=>current.map((x,i)=>i===index?{...x,reviewer_name:e.target.value}:x))} className="h-10 w-full rounded-md border bg-white px-3 text-sm" placeholder="Reviewer name"/></label></div><Textarea rows={7} value={order.feedback||""} onChange={e=>setOrders(current=>current.map((x,i)=>i===index?{...x,feedback:e.target.value}:x))} placeholder="Detailed human feedback…"/><Button onClick={()=>void save(order)}><CheckCircle2/>Save review</Button></CardContent></Card>)}{!orders.length&&<Card><CardContent className="p-6 text-sm text-slate-500">No paid expert-review orders yet.</CardContent></Card>}</div>}</div></main>
}
