"use client"

import { useEffect, useState } from "react"
import { Button } from "@/components/ui/button"
import { progressCsv, studentSummary, type SchoolDetail } from "@/lib/school/progress"

const date = (value?: string | null) => value && Number.isFinite(Date.parse(value)) ? new Date(value).toLocaleDateString("en-GB") : "No date"
const colour = (state: string) => state === "Completed" ? "bg-emerald-50 text-emerald-900" : state === "Overdue" ? "bg-amber-50 text-amber-950" : "bg-slate-50 text-slate-700"

export function ProgressWorkspace({ detail }: { detail: SchoolDetail }) {
  const [search, setSearch] = useState("")
  const [filter, setFilter] = useState("all")
  const [selected, setSelected] = useState("")
  const [now, setNow] = useState(() => Date.now())
  useEffect(() => { const timer = setInterval(() => setNow(Date.now()), 60000); return () => clearInterval(timer) }, [])
  const summaries = detail.students.map(s => studentSummary(detail, s, now))
  const visible = summaries.filter(s => `${s.student.displayName} ${s.student.targetCourse ?? ""}`.toLowerCase().includes(search.toLowerCase()) && (filter === "all" || (filter === "overdue" ? s.overdue > 0 : s.dueSoon > 0)))
  const student = summaries.find(s => s.student.userId === selected)
  const priorities = new Map<string, number>()
  for (const s of detail.students) if (s.priority?.label) priorities.set(s.priority.label, (priorities.get(s.priority.label) ?? 0) + 1)
  const saveCsv = () => {
    const url = URL.createObjectURL(new Blob([progressCsv(detail, now)], { type: "text/csv;charset=utf-8" }))
    const a = document.createElement("a"); a.href = url; a.download = "school-assignment-progress.csv"; a.click(); setTimeout(() => URL.revokeObjectURL(url), 1000)
  }
  return <section className="school-progress space-y-5 rounded-2xl border bg-white p-5 sm:p-6" aria-label="School progress tracking">
    <style>{`@media print { body * { visibility: hidden; } .school-progress, .school-progress * { visibility: visible; } .school-progress { position: absolute; left: 0; top: 0; width: 100%; border: 0; } .school-progress .no-print { display: none !important; } .school-progress .overflow-x-auto { overflow: visible; } .school-progress tr { break-inside: avoid; } }`}</style>
    <div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="font-serif text-2xl font-bold">Progress & follow-up</h2><p className="text-sm text-slate-600">{detail.cohort.name} · {date(new Date(now).toISOString())}</p></div><div className="no-print flex gap-2"><Button variant="outline" onClick={saveCsv}>Export task CSV</Button><Button variant="outline" onClick={() => window.print()}>Print report</Button></div></div>
    <p className="text-sm text-slate-600">Completion and reflections are student-reported. Preparation scores are coaching indicators, not admissions predictions. Profile dates show the last saved summary, not the last login.</p>
    <div className="grid gap-3 sm:grid-cols-3">{[["Students with overdue work", summaries.filter(s => s.overdue).length], ["Outstanding overdue tasks", summaries.reduce((n, s) => n + s.overdue, 0)], ["Tasks due in next 7 days", summaries.reduce((n, s) => n + s.dueSoon, 0)]].map(([label, value]) => <div key={label} className="rounded-xl bg-slate-50 p-4"><p className="text-sm text-slate-600">{label}</p><p className="text-3xl font-bold">{value}</p></div>)}</div>
    <div><h3 className="font-semibold">Common teaching priorities</h3><div className="mt-2 flex flex-wrap gap-2">{[...priorities].sort((a,b) => b[1]-a[1]).slice(0,5).map(([label,count]) => <span className="rounded-full bg-teal-50 px-3 py-1 text-sm text-teal-900" key={label}>{label} · {count} {count === 1 ? "student" : "students"}</span>)}{!priorities.size && <p className="text-sm text-slate-500">Priorities appear as students save preparation evidence.</p>}</div></div>
    <div className="no-print flex flex-wrap gap-3"><label className="flex-1 text-sm">Search students<input className="mt-1 block w-full rounded-md border p-2" value={search} onChange={e => setSearch(e.target.value)} placeholder="Name or course" /></label><label className="text-sm">Show<select className="mt-1 block rounded-md border p-2" value={filter} onChange={e => setFilter(e.target.value)}><option value="all">All students</option><option value="overdue">Overdue work</option><option value="soon">Due within 7 days</option></select></label></div>
    <div className="overflow-x-auto"><table className="w-full text-left text-sm"><caption className="sr-only">Student assignment completion</caption><thead><tr className="border-b"><th className="p-3">Student</th><th className="p-3">Completed</th><th className="p-3">Overdue</th><th className="p-3">Profile saved</th><th className="no-print p-3">Review</th></tr></thead><tbody>{visible.map(s => <tr className="border-b" key={s.student.userId}><th className="p-3 font-medium">{s.student.displayName}<span className="block text-xs text-slate-500">{s.student.targetCourse || "Course not set"}</span></th><td className="p-3">{s.completed}/{s.tasks.length}{s.percent !== null ? ` (${s.percent}%)` : " — no tasks"}</td><td className="p-3">{s.overdue || "None"}</td><td className="p-3">{s.student.updatedAt ? date(s.student.updatedAt) : "No summary yet"}</td><td className="no-print p-3"><Button size="sm" variant="outline" onClick={() => setSelected(s.student.userId)} aria-label={`Review ${s.student.displayName}`}>Review</Button></td></tr>)}</tbody></table>{!visible.length && <p className="p-4 text-sm text-slate-500">No students match this view.</p>}</div>
    <details><summary className="cursor-pointer font-semibold">Assignment progress matrix</summary><div className="mt-3 overflow-x-auto"><table className="w-full text-left text-xs"><thead><tr><th className="p-2">Student</th>{detail.assignments.map(a => <th className="min-w-36 p-2" key={a.id}>{a.title}<span className="block font-normal">{date(a.due_at)}</span></th>)}</tr></thead><tbody>{visible.map(s => <tr key={s.student.userId}><th className="p-2">{s.student.displayName}</th>{s.tasks.map(t => <td className={`border p-2 ${colour(t.state)}`} key={t.id}>{t.state}</td>)}</tr>)}</tbody></table>{!detail.assignments.length && <p>No assignments have been set.</p>}</div></details>
    {student && <section className="rounded-xl border border-teal-200 p-4" aria-label="Individual student report"><div className="flex justify-between gap-3"><h3 className="font-serif text-xl font-bold">{student.student.displayName} — preparation review</h3><Button className="no-print" size="sm" variant="ghost" onClick={() => setSelected("")}>Close</Button></div><p className="mt-2 text-sm">{student.student.targetUniversity || "University not set"} · {student.student.targetCourse || "Course not set"}</p><p className="mt-2 text-sm">{student.student.interviewCount} interviews · {student.student.fullPaperCount} papers · {student.student.essayCount} essays</p><p className="mt-2 text-sm"><strong>Next focus:</strong> {student.student.priority?.label || "Build a preparation baseline"}. <strong>Strength:</strong> {student.student.strongest?.label || "More evidence needed"}.</p><div className="mt-4 space-y-3">{student.tasks.map(t => <div className={`rounded-lg p-3 ${colour(t.state)}`} key={t.id}><strong>{t.title}</strong><p className="text-sm">{t.state} · Due: {date(t.due_at)}</p>{t.progress?.note && <p className="mt-2 whitespace-pre-wrap text-sm"><strong>Student reflection:</strong> {t.progress.note}</p>}</div>)}</div></section>}
  </section>
}
