import Link from "next/link"
import { GraduationCap, School, ShieldCheck, UserCheck } from "lucide-react"

const privacyEmail=process.env.NEXT_PUBLIC_PRIVACY_CONTACT_EMAIL||"Privacy contact to be configured before launch"

export const metadata={title:"School Data Protection | ScholarBridge"}

export default function SchoolDataPage(){return <main className="min-h-screen bg-slate-50 px-4 py-10 text-slate-900 sm:px-6"><div className="mx-auto max-w-4xl space-y-6">
  <div className="flex items-center gap-2 text-sm font-semibold text-teal-800"><GraduationCap className="size-5"/>ScholarBridge for Schools</div>
  <section className="rounded-3xl bg-[#102a43] p-7 text-white sm:p-9"><p className="text-xs font-bold uppercase tracking-[.18em] text-cyan-200">School data governance</p><h1 className="mt-3 font-serif text-4xl font-bold">Pupil data needs a defined school agreement before import.</h1><p className="mt-4 leading-7 text-slate-200">This page sets the product expectations for School-plan deployments. It is not, by itself, a signed data-processing agreement.</p></section>
  <div className="grid gap-4 md:grid-cols-2"><Item icon={<School/>} title="Define the roles">The school and ScholarBridge must identify who is controller, processor or joint controller for each purpose. The role can differ between school-directed pupil records and ScholarBridge's own account/security/billing processing.</Item><Item icon={<UserCheck/>} title="Least-privilege access">Teachers and school administrators should only see pupils/cohorts they are authorised to manage. Student accounts remain separate and must not become publicly discoverable.</Item><Item icon={<ShieldCheck/>} title="Contract before data import">Before a school uploads or syncs pupil data, put appropriate contractual/data-processing terms in place covering instructions, confidentiality, security, sub-processors, deletion/export, breaches and international transfers.</Item><Item icon={<ShieldCheck/>} title="Student rights remain visible">School oversight must not hide the Privacy Centre or Safeguarding route. Requests involving school-controlled information may need coordination with the school's data-protection contact.</Item></div>
  <section className="rounded-2xl border bg-white p-6"><h2 className="font-serif text-2xl font-bold">School launch controls</h2><ul className="mt-4 list-disc space-y-2 pl-6 text-sm leading-6 text-slate-600"><li>Use separate named accounts; do not share teacher/admin credentials.</li><li>Confirm cohort membership and teacher permissions before enabling dashboards.</li><li>Minimise imported pupil fields to what the preparation service actually needs.</li><li>Do not import special-category or safeguarding information into general AI prompts.</li><li>Agree an offboarding process for export/deletion when a pupil leaves or a contract ends.</li><li>Document sub-processors and international-transfer safeguards.</li><li>Keep the school's own safeguarding procedures in force; ScholarBridge does not replace a DSL or school reporting route.</li></ul></section>
  <section className="rounded-2xl border border-teal-200 bg-teal-50 p-5 text-sm leading-6 text-teal-950"><strong>School/privacy contact:</strong> {privacyEmail}. Before commercial school onboarding, use a reviewed school contract/DPA that reflects the actual deployment.</section>
  <div className="flex flex-wrap gap-4 text-sm font-semibold"><Link href="/privacy" className="text-teal-800 underline">Privacy Notice</Link><Link href="/safeguarding" className="text-teal-800 underline">Safeguarding</Link><Link href="/terms" className="text-teal-800 underline">Terms</Link></div>
</div></main>}

function Item({icon,title,children}:{icon:React.ReactNode;title:string;children:React.ReactNode}){return <section className="rounded-2xl border bg-white p-5"><div className="flex gap-3"><span className="mt-0.5 text-teal-700">{icon}</span><div><h2 className="font-serif text-xl font-bold">{title}</h2><p className="mt-2 text-sm leading-6 text-slate-600">{children}</p></div></div></section>}
