import Link from "next/link"
import { ShieldCheck } from "lucide-react"

export const metadata = { title: "Privacy Notice | ScholarBridge", description: "How ScholarBridge uses and protects personal data." }
const controllerName = process.env.NEXT_PUBLIC_DATA_CONTROLLER_NAME || "ScholarBridge service operator"
const controllerAddress = process.env.NEXT_PUBLIC_DATA_CONTROLLER_ADDRESS || "Add the controller's registered or contact address in Vercel"
const privacyEmail = process.env.NEXT_PUBLIC_PRIVACY_CONTACT_EMAIL || "Add a privacy contact email in Vercel"

export default function PrivacyPage() {
  return <main className="min-h-screen bg-[#f5f7f7] px-4 py-10 text-[#172b3a] sm:px-6"><article className="mx-auto max-w-4xl rounded-[2rem] border border-slate-200 bg-white p-6 shadow-sm sm:p-10">
    <div className="flex items-start gap-3"><span className="grid size-11 shrink-0 place-items-center rounded-2xl bg-[#edf7f8] text-[#147d91]"><ShieldCheck /></span><div><p className="text-xs font-bold uppercase tracking-[.18em] text-[#147d91]">Privacy & UK GDPR</p><h1 className="mt-1 font-serif text-4xl font-bold">ScholarBridge Privacy Notice</h1><p className="mt-2 text-sm text-slate-500">Last updated: 25 September 2026</p></div></div>

    <section className="mt-7 rounded-2xl border border-[#cfe1e4] bg-[#f8fbfb] p-5"><h2 className="font-serif text-2xl font-bold">The short version</h2><p className="mt-2 leading-7 text-slate-700">ScholarBridge stores the information needed to run your account, remember preparation progress and provide personalised practice. We do not sell your personal data. Some features use specialist providers such as cloud hosting, payments and AI/voice services. Optional services are kept separate from essential account functions.</p><div className="mt-4 flex flex-wrap gap-3 text-sm font-semibold"><Link href="/privacy-centre" className="text-[#147d91] underline">Open Privacy Centre</Link><Link href="/safeguarding" className="text-[#147d91] underline">Report a safety concern</Link></div></section>

    <div className="mt-8 space-y-8 leading-7 text-slate-700">
      <Section n="1" title="Who is responsible for your data?"><p><strong>{controllerName}</strong> is the data controller for ScholarBridge unless a school or another organisation is the controller for a particular school-managed processing purpose.</p><p><strong>Contact address:</strong> {controllerAddress}<br/><strong>Privacy contact:</strong> {privacyEmail}</p></Section>
      <Section n="2" title="Information we may collect"><ul className="list-disc space-y-2 pl-6"><li>Account details such as name, email and authentication information.</li><li>A broad age band (13–15, 16–17 or 18+) so age-appropriate protections can be applied without collecting a full date of birth.</li><li>Versioned acknowledgement of the Terms and Privacy Notice.</li><li>Target university/course, application year and preparation preferences.</li><li>Answers, scores, feedback, progress, reflections, written work and study-plan information.</li><li>Interview transcripts/audio where you actively use a feature that requires them.</li><li>Files or text you choose to submit for analysis.</li><li>School/cohort information where a school account is used.</li><li>Subscription/payment status. Full payment-card details are handled by Stripe, not stored directly by ScholarBridge.</li><li>Technical and security information needed to operate accounts safely.</li><li>Privacy-rights requests and safeguarding reports you choose to submit.</li></ul></Section>
      <Section n="3" title="Why we use it"><p>We use personal data to provide and personalise the service, save progress, mark practice work, operate interview/tutoring features, manage subscriptions, provide authorised school dashboards, respond to rights/safety reports, prevent abuse and protect accounts.</p></Section>
      <Section n="4" title="Lawful bases"><p>The lawful basis depends on the processing purpose. It may include performing the service/contract requested, legitimate interests such as security where those interests do not override your rights, compliance with law, or consent for genuinely optional processing. Where consent is the basis, it can be withdrawn.</p></Section>
      <Section n="5" title="AI and service providers"><p>ScholarBridge can use Supabase, Vercel, Stripe, Google Gemini, OpenAI and ElevenLabs depending on the feature. Providers should receive only the information needed for that feature. Avoid entering highly sensitive information that is unnecessary for admissions preparation.</p><p>Where personal data is transferred outside the UK, recognised contractual or other safeguards should be used where required. Current processor arrangements must be reviewed as part of launch governance.</p></Section>
      <Section n="6" title="Children and young people"><p>Direct self-sign-up is intended for users aged 13 or over. ScholarBridge asks for an age band rather than a full birth date. High-privacy defaults apply, optional services are not automatically enabled, and younger users are given accessible routes to privacy and safeguarding controls. If you are under 13, do not self-register; use an appropriate parent/guardian or school-managed route.</p></Section>
      <Section n="7" title="Retention"><p>User-linked learning/account data is retained while needed to provide the account and is designed to be erased through account deletion, subject to lawful exceptions. Safeguarding/privacy-request records may need proportionate retention for handling, accountability or legal obligations. Payment providers can retain transaction records where required by financial/tax law. A documented retention schedule must be maintained and reviewed operationally.</p></Section>
      <Section n="8" title="Your rights"><p>Depending on the circumstances, you may have rights of access, correction, erasure, restriction, objection, portability and withdrawal of consent. ScholarBridge provides a <Link href="/privacy-centre" className="font-semibold text-[#147d91] underline">Privacy Centre</Link> for data export, rights requests and account deletion. You may also complain to the UK Information Commissioner’s Office.</p></Section>
      <Section n="9" title="Automated and AI feedback"><p>AI feedback, practice classifications, readiness indicators and scores are educational support. They are not official admissions decisions and should not be used as the sole basis for a significant decision about a student. ScholarBridge should not infer sensitive personal characteristics from voice, video or writing.</p></Section>
      <Section n="10" title="Schools"><p>For School-plan use, the school and ScholarBridge must identify their data-protection roles for each processing purpose and put suitable contractual/data-processing terms in place before importing pupil data. School access must be limited to authorised pupils and staff.</p></Section>
      <Section n="11" title="Cookies and device storage"><p>Essential storage supports authentication, security, plan access and privacy choices. Optional technologies are controlled separately. See the <Link href="/cookies" className="font-semibold text-[#147d91] underline">Cookie & Storage Notice</Link>.</p></Section>
      <Section n="12" title="Safeguarding and complaints"><p>Safety concerns can be raised through the <Link href="/safeguarding" className="font-semibold text-[#147d91] underline">Safeguarding page</Link>. Privacy complaints can be sent to {privacyEmail}. AI is not used to make the final decision on whether a safeguarding concern is valid.</p></Section>
      <Section n="13" title="Changes to this notice"><p>We may update this notice as features, providers or laws change. Material changes should be highlighted and versioned acknowledgement can be requested where appropriate.</p></Section>
    </div>
  </article></main>
}

function Section({n,title,children}:{n:string;title:string;children:React.ReactNode}){return <section><h2 className="font-serif text-2xl font-bold text-[#102a43]">{n}. {title}</h2><div className="mt-2 space-y-2">{children}</div></section>}
