export type CoursePrompt = {
  id: string
  course: string
  theme: string
  prompt: string
  followUps: string[]
  mutation: string
  interviewerFocus: string[]
}

const make = (course: string, rows: Array<Omit<CoursePrompt, "course">>) => rows.map(row => ({ ...row, course }))

export const courseInterviewBank: CoursePrompt[] = [
  ...make("Physics", [
    { id:"phy-terminal", theme:"Modelling", prompt:"A coffee filter falls through still air and eventually reaches a steady speed. Without starting from a memorised formula, explain how you would model the motion from release to terminal speed.", followUps:["What assumptions are you making about drag?","What would the velocity–time graph look like near the start and near terminal speed?","How could you test whether drag is proportional to speed or speed squared?"], mutation:"Now imagine the same filter is dropped in a much denser gas. Which parts of your model change first?", interviewerFocus:["modelling","graphs","assumptions","limiting behaviour"] },
    { id:"phy-orbit", theme:"Estimation", prompt:"Estimate the orbital speed of a low-Earth satellite using only quantities you could reasonably reconstruct in an interview.", followUps:["Which quantity dominates your uncertainty?","Can you derive the relationship rather than quote it?","How would the answer change for an orbit twice as far from Earth’s centre?"], mutation:"Suppose Earth had the same mass but half its radius. What changes?", interviewerFocus:["estimation","gravitation","derivation","scaling"] },
    { id:"phy-circuit", theme:"Experimental reasoning", prompt:"You are given an unknown two-terminal component, a cell, resistors, meters and leads. Design a sequence of measurements that would let you infer whether the component is ohmic.", followUps:["How would meter resistance affect your conclusion?","What pattern in the data would make you suspicious of heating?","Which graph would you plot and why?"], mutation:"Now the component changes resistance rapidly with temperature. How would you redesign the procedure?", interviewerFocus:["experiment","uncertainty","circuits","data"] },
  ]),
  ...make("Engineering", [
    { id:"eng-bridge", theme:"Structures", prompt:"You must span a gap with a bridge using very little material. What determines where you would put material first?", followUps:["Where do you expect the largest bending moments?","Why can a deeper beam be more efficient than a thicker one?","What failure mode might invalidate a purely elastic model?"], mutation:"Now the bridge must tolerate a moving point load rather than a static central load.", interviewerFocus:["forces","moments","failure","design trade-offs"] },
    { id:"eng-cooling", theme:"Heat transfer", prompt:"Two identical hot metal blocks are left to cool, one in still air and one in moving air. Build a model for the temperature histories and explain what you would expect to differ.", followUps:["Which heat-transfer mechanism changes most?","What does the initial slope tell you?","When might a lumped-temperature model fail?"], mutation:"Now one block is hollow but has the same mass. Predict the effect before calculating.", interviewerFocus:["heat transfer","modelling","surface area","time constants"] },
    { id:"eng-control", theme:"Systems", prompt:"A small robot must follow a straight painted line using two light sensors. Describe a control strategy before writing any code.", followUps:["What happens if the correction is too aggressive?","How could proportional control help?","What disturbance would you test first?"], mutation:"Now one sensor is biased by a constant offset. How could the system detect or compensate?", interviewerFocus:["feedback","stability","sensors","robustness"] },
  ]),
  ...make("Mathematics", [
    { id:"math-prime", theme:"Proof", prompt:"Consider the claim that there are infinitely many primes. Reconstruct a proof from first principles, then identify exactly where contradiction enters.", followUps:["Why must the constructed number have a prime factor?","Does the proof tell you anything about gaps between primes?","Can you adapt the structure to another infinite family?"], mutation:"Replace primes with primes congruent to a particular residue. Which parts of the simple argument survive?", interviewerFocus:["proof","contradiction","definitions","generalisation"] },
    { id:"math-seq", theme:"Sequences", prompt:"A sequence is defined by repeatedly averaging a positive number with its reciprocal. What behaviour do you expect and how would you investigate it?", followUps:["Can you identify a fixed point?","How could you show the sequence stays on one side of the fixed point?","Can you establish monotonicity?"], mutation:"Replace the arithmetic mean with a weighted mean. What changes?", interviewerFocus:["sequences","fixed points","inequalities","convergence"] },
    { id:"math-random", theme:"Probability", prompt:"A fair coin is tossed until two consecutive heads occur. How would you find the expected number of tosses?", followUps:["Why is a simple geometric model insufficient?","Can you define states?","Can you write coupled expectation equations?"], mutation:"Now stop at HTH instead. What additional state information is needed?", interviewerFocus:["conditional expectation","states","recurrence","modelling"] },
  ]),
  ...make("Computer Science", [
    { id:"cs-search", theme:"Algorithms", prompt:"You need to find a name in a sorted list. Explain why binary search works, then state the invariant that makes it reliable.", followUps:["What breaks if the list changes while you search?","What is the worst-case number of comparisons?","How would you prove termination?"], mutation:"Now the data is stored on slow remote storage where each access is expensive. Would your strategy change?", interviewerFocus:["algorithms","invariants","complexity","systems"] },
    { id:"cs-cache", theme:"Systems", prompt:"A program becomes much faster after it has processed similar data once. Give several possible explanations and design a way to distinguish them.", followUps:["How would you separate CPU cache effects from memoisation?","What measurements would you collect?","What would count as a confound?"], mutation:"Now performance becomes worse after repeated use. Which explanations move to the top of your list?", interviewerFocus:["hypotheses","memory","measurement","experiments"] },
    { id:"cs-proof", theme:"Correctness", prompt:"Suppose an algorithm repeatedly swaps adjacent out-of-order items. What must you establish to prove it eventually sorts the list?", followUps:["Can you define a measure that always decreases?","Why does local improvement imply global order at termination?","What is the time complexity?"], mutation:"Now swaps can occasionally fail. What guarantees can you still make?", interviewerFocus:["correctness","termination","complexity","robustness"] },
  ]),
  ...make("Natural Sciences", [
    { id:"ns-enzyme", theme:"Biology/Chemistry", prompt:"An enzyme-catalysed reaction speeds up with temperature and then slows sharply. Give a mechanistic explanation and design data that could distinguish competing explanations.", followUps:["How would substrate concentration interact with temperature?","What control would you include?","Could diffusion produce a similar pattern?"], mutation:"Now the enzyme is immobilised on beads. Which part of the interpretation becomes more complicated?", interviewerFocus:["mechanism","kinetics","controls","alternative explanations"] },
    { id:"ns-equilibrium", theme:"Chemistry", prompt:"A coloured equilibrium mixture becomes paler when compressed. What can you infer, and what can you not infer, from that observation alone?", followUps:["How would Le Chatelier’s principle connect to a molecular picture?","Could temperature change be a confound?","What additional measurement would strengthen your conclusion?"], mutation:"Now the colour change reverses slowly after the initial compression. Suggest explanations.", interviewerFocus:["equilibrium","inference","molecular reasoning","evidence"] },
    { id:"ns-population", theme:"Biology", prompt:"A population grows rapidly, levels off, then begins to oscillate. Give at least two mechanistic explanations for the oscillation.", followUps:["How would a time delay produce oscillations?","How could predator–prey dynamics look similar?","What data would distinguish the models?"], mutation:"Now the oscillations become larger over time. Which model assumptions would you question?", interviewerFocus:["population models","feedback","data","model discrimination"] },
  ]),
  ...make("Economics", [
    { id:"eco-rent", theme:"Policy", prompt:"A city caps residential rents below the current market level. Build the strongest case for and against the policy using a simple model, then identify what the model leaves out.", followUps:["What happens to quantity supplied over different time horizons?","How could allocation change when price cannot?","Which empirical outcomes would matter most?"], mutation:"Now the city simultaneously expands housing supply. Does your recommendation change?", interviewerFocus:["supply and demand","welfare","distribution","policy evaluation"] },
    { id:"eco-tax", theme:"Incidence", prompt:"A tax is legally imposed on sellers. Who actually bears the burden?", followUps:["Why is statutory incidence not enough?","How do elasticities matter?","Can the consumer burden exceed half even if firms remit the tax?"], mutation:"Now demand becomes much more elastic after one year. How does the incidence change over time?", interviewerFocus:["elasticity","incidence","comparative statics","time"] },
    { id:"eco-average", theme:"Data", prompt:"A report says average wages rose while most workers received no pay rise. Is that possible? Give several mechanisms.", followUps:["How could composition effects matter?","Which summary statistics would you request?","What would a median tell you that a mean does not?"], mutation:"Now the median also rises. What explanations remain?", interviewerFocus:["statistics","composition","inequality","interpretation"] },
  ]),
  ...make("PPE", [
    { id:"ppe-vote", theme:"Political philosophy", prompt:"Should voting be compulsory? Start by identifying the values that are in tension rather than giving a yes/no answer.", followUps:["What conception of freedom are you using?","Does legitimacy depend on participation?","Could compulsory attendance be separated from compulsory choice?"], mutation:"Suppose non-participation is itself a deliberate political expression. Does that alter your view?", interviewerFocus:["freedom","legitimacy","trade-offs","definitions"] },
    { id:"ppe-expert", theme:"Epistemology/politics", prompt:"When should elected governments defer to experts?", followUps:["What counts as expertise?","Who chooses the experts?","How should value disagreements be handled when the technical evidence is clear?"], mutation:"Now experts strongly disagree with each other. What changes in your framework?", interviewerFocus:["expertise","democracy","values","uncertainty"] },
    { id:"ppe-inequality", theme:"Economics/philosophy", prompt:"Can an unequal outcome be fair? Give a criterion for fairness and test it against at least two cases.", followUps:["Is opportunity enough?","What if inequality improves the position of the least advantaged?","How much does responsibility matter?"], mutation:"Now imagine the unequal outcome arose from a random lottery everyone accepted beforehand.", interviewerFocus:["fairness","distribution","responsibility","counterexamples"] },
  ]),
  ...make("Law", [
    { id:"law-taking", theme:"Rules", prompt:"A rule prohibits ‘taking another person’s vehicle without consent’. What does ‘taking’ need to mean for the rule to handle borrowing, moving and temporarily using a vehicle coherently?", followUps:["Does moving a car one metre count?","Should intention matter?","What principle distinguishes trivial interference from the target harm?"], mutation:"Now the owner had previously given broad permission but has not been contacted today.", interviewerFocus:["interpretation","rule design","edge cases","principle"] },
    { id:"law-promise", theme:"Obligation", prompt:"When, if ever, should a promise become legally enforceable?", followUps:["Why not enforce every serious promise?","What role should reliance play?","Can formality substitute for evidence of intention?"], mutation:"Now the promise is made publicly and a third party changes position because of it.", interviewerFocus:["principle","reliance","policy","hard cases"] },
    { id:"law-speech", theme:"Rights", prompt:"A university restricts a lawful but highly offensive speaker. Build a principled framework for deciding whether that restriction is justified.", followUps:["What is the relevant harm?","Does a university have different duties from the state?","How would your rule avoid viewpoint discrimination?"], mutation:"Now the event presents a credible risk of violence from opponents rather than from the speaker.", interviewerFocus:["rights","harm","institutional role","consistency"] },
  ]),
  ...make("Medicine", [
    { id:"med-screen", theme:"Evidence", prompt:"A screening test is described as 99% accurate. Why is that statement not enough to tell a patient what a positive result means?", followUps:["What additional probabilities do you need?","How does disease prevalence matter?","Can you explain the result using natural frequencies?"], mutation:"Now the condition becomes ten times more common in the tested population.", interviewerFocus:["probability","communication","evidence","base rates"] },
    { id:"med-resource", theme:"Ethics", prompt:"Two patients could benefit from one scarce treatment. What kinds of reasons could be relevant to a fair allocation decision?", followUps:["Should age matter?","How should urgency and expected benefit interact?","What would make a criterion discriminatory rather than clinically relevant?"], mutation:"Now one patient has already received part of the treatment course.", interviewerFocus:["ethics","fairness","clinical reasoning","criteria"] },
    { id:"med-trial", theme:"Research", prompt:"A new treatment performs better than standard care in a small trial. What would you need to know before changing practice?", followUps:["Why does randomisation matter?","What is the difference between statistical and clinical significance?","Which sources of bias would you inspect first?"], mutation:"Now the effect is large but adverse events are more common.", interviewerFocus:["trials","bias","risk-benefit","evidence"] },
  ]),
  ...make("History", [
    { id:"hist-source", theme:"Source criticism", prompt:"A minister’s diary says a policy was introduced purely for economic reasons. What can this source establish, and what can it not establish?", followUps:["How does audience affect the source?","What corroborating evidence would you seek?","Could sincerity still produce an unreliable account?"], mutation:"Now the diary was written twenty years later for publication.", interviewerFocus:["source criticism","motive","corroboration","memory"] },
    { id:"hist-cause", theme:"Causation", prompt:"What does it mean to say one event ‘caused’ another in history? Build a useful definition and test it.", followUps:["How do necessary and sufficient causes differ?","How would you handle long-term structural conditions?","Can historians rank causes without pretending to measure them precisely?"], mutation:"Remove the factor you initially ranked first. Would the outcome still have occurred?", interviewerFocus:["causation","counterfactuals","structure","argument"] },
    { id:"hist-absence", theme:"Evidence", prompt:"When can the absence of evidence become evidence of absence?", followUps:["What matters about the expected survival of records?","How would institutional record-keeping affect the inference?","Give a case where silence is highly informative and one where it is not."], mutation:"Now you discover that half the archive was destroyed randomly.", interviewerFocus:["evidence","archives","probability","inference"] },
  ]),
  ...make("English", [
    { id:"englit-voice", theme:"Close reading", prompt:"Read the sentence ‘She had been waiting for the room to become hers.’ What ambiguities or tensions would you want to explore before seeing any wider context?", followUps:["What does the tense contribute?","What might ‘hers’ mean beyond legal ownership?","How could punctuation or surrounding syntax change the tone?"], mutation:"Now imagine the sentence appears at the end rather than the beginning of a novel.", interviewerFocus:["close reading","ambiguity","syntax","context"] },
    { id:"englit-narrator", theme:"Narrative", prompt:"Can an unreliable narrator tell the truth?", followUps:["What kinds of unreliability are possible?","Can factual unreliability coexist with emotional truth?","How would a reader detect the gap?"], mutation:"Now the narrator openly admits that memory is unreliable.", interviewerFocus:["narrative voice","truth","reader inference","form"] },
    { id:"englit-translation", theme:"Language", prompt:"A translator must choose between preserving rhythm and preserving literal meaning. Is that always a genuine trade-off?", followUps:["What counts as ‘literal’ meaning?","Can form itself carry meaning?","How would your answer differ for drama and lyric poetry?"], mutation:"Now the translation is intended for performance rather than silent reading.", interviewerFocus:["translation","form","meaning","audience"] },
  ]),
]

export const coursesWithDeepBanks = Array.from(new Set(courseInterviewBank.map(item => item.course)))

export function promptsForCourse(course: string) {
  const exact = courseInterviewBank.filter(item => item.course.toLowerCase() === course.trim().toLowerCase())
  if (exact.length) return exact
  if (/engineering/i.test(course)) return courseInterviewBank.filter(item => item.course === "Engineering")
  if (/math/i.test(course)) return courseInterviewBank.filter(item => item.course === "Mathematics")
  if (/computer/i.test(course)) return courseInterviewBank.filter(item => item.course === "Computer Science")
  if (/law|jurisprudence/i.test(course)) return courseInterviewBank.filter(item => item.course === "Law")
  if (/english/i.test(course)) return courseInterviewBank.filter(item => item.course === "English")
  return courseInterviewBank.filter(item => item.course === "Physics")
}
