import { courseInterviewBank, type CoursePrompt } from "@/lib/course-interview-bank"

const make = (course: string, rows: Array<Omit<CoursePrompt, "course">>) => rows.map(row => ({ ...row, course }))

export const courseInterviewBank2027: CoursePrompt[] = [
  ...make("Physics", [
    { id:"2027-phy-pendulum", theme:"Modelling", prompt:"A pendulum clock is moved from sea level to the top of a very high mountain. Without quoting a memorised result, predict how its timekeeping changes and justify the direction of the effect.", followUps:["Which physical quantity has changed?","How would you derive the dependence of period on that quantity?","What approximation is hidden in the usual pendulum model?"], mutation:"Now make the pendulum swing through a much larger angle. Which assumption fails first?", interviewerFocus:["modelling","derivation","approximations","scaling"] },
    { id:"2027-phy-solar", theme:"Estimation", prompt:"Estimate the power per square metre received from the Sun at Earth using only quantities you might reconstruct in an interview.", followUps:["Which geometric factor matters?","How would you check the order of magnitude?","Which assumption contributes most uncertainty?"], mutation:"Now move Earth to twice its current orbital radius. Predict the new intensity before calculating.", interviewerFocus:["estimation","inverse-square","units","reasonableness"] },
    { id:"2027-phy-collision", theme:"Mechanics", prompt:"Two carts collide on a low-friction track and stick together. What can you infer without knowing the detailed forces during the collision?", followUps:["Which quantity is conserved and why?","Why is kinetic energy generally not conserved?","How could you estimate the energy transformed?"], mutation:"Now the carts repel using a compressed spring instead of sticking.", interviewerFocus:["momentum","energy","systems","assumptions"] },
  ]),
  ...make("Engineering", [
    { id:"2027-eng-tower", theme:"Structures", prompt:"A tall thin tower must be made lighter without becoming less resistant to bending. What geometric changes would you explore first?", followUps:["Why does moving material away from the neutral axis matter?","What new failure mode can appear in very thin members?","How would wind loading change your priorities?"], mutation:"Now the tower must also survive an earthquake with horizontal acceleration.", interviewerFocus:["second moment","buckling","loads","trade-offs"] },
    { id:"2027-eng-battery", theme:"Systems", prompt:"An electric vehicle battery overheats during rapid charging. Build a simple model of where the heat comes from and how it could be removed.", followUps:["Which terms scale with current?","What role does surface area play?","How would you distinguish poor cooling from high internal resistance experimentally?"], mutation:"Now the vehicle must fast-charge in a hot climate.", interviewerFocus:["energy","thermal design","experiments","constraints"] },
    { id:"2027-eng-filter", theme:"Design", prompt:"Design a low-cost water filter for a remote community. What would you need to optimise besides simply removing visible particles?", followUps:["How would flow rate trade off against filtration?","What would you test for that cannot be seen?","How would maintenance change your design?"], mutation:"Now replacement parts can only arrive twice a year.", interviewerFocus:["design constraints","testing","reliability","trade-offs"] },
  ]),
  ...make("Chemistry", [
    { id:"2027-chem-rate", theme:"Kinetics", prompt:"A reaction doubles in rate when temperature rises by 10 °C. Why does that observation not mean every molecule is moving twice as fast?", followUps:["How does the energy distribution change?","What does activation energy contribute?","How could a catalyst alter the pattern?"], mutation:"Now the rate stops increasing above a certain temperature. Suggest competing explanations.", interviewerFocus:["kinetics","Boltzmann distribution","activation energy","evidence"] },
    { id:"2027-chem-buffer", theme:"Equilibria", prompt:"A solution resists a change in pH when a small amount of acid is added. Explain the mechanism rather than just naming it as a buffer.", followUps:["Which equilibrium shifts?","What limits the buffering capacity?","How would dilution affect the pH and capacity differently?"], mutation:"Now add enough acid to consume most of the conjugate base.", interviewerFocus:["equilibrium","mechanism","capacity","prediction"] },
    { id:"2027-chem-spectrum", theme:"Evidence", prompt:"Two compounds have the same molecular formula but different spectra. What kinds of structural differences could explain that?", followUps:["Which measurements would you combine?","Why can one technique be ambiguous?","How would symmetry affect the information obtained?"], mutation:"Now one sample contains a mixture of two compounds.", interviewerFocus:["spectroscopy","structure","evidence","ambiguity"] },
  ]),
  ...make("Materials Science", [
    { id:"2027-mat-crack", theme:"Failure", prompt:"A metal component fails from a small crack even though the average stress is below its quoted strength. Why might that happen?", followUps:["How does crack geometry alter local stress?","Why can repeated loading matter?","What evidence would distinguish fatigue from overload?"], mutation:"Now the same component operates at much lower temperature.", interviewerFocus:["stress concentration","fatigue","fracture","evidence"] },
    { id:"2027-mat-composite", theme:"Design", prompt:"Why might combining two weaker materials produce a composite that performs better than either alone?", followUps:["How can fibres redirect load?","What role does the interface play?","Which direction might still remain weak?"], mutation:"Now the load direction varies unpredictably in service.", interviewerFocus:["composites","anisotropy","interfaces","design"] },
    { id:"2027-mat-heat", theme:"Structure-property", prompt:"A material is strong but performs badly as a thermal barrier. What microscopic properties would you investigate?", followUps:["How can electrons carry heat?","What role do lattice vibrations play?","Can porosity help and hurt simultaneously?"], mutation:"Now the material must also survive repeated thermal cycling.", interviewerFocus:["thermal transport","microstructure","porosity","trade-offs"] },
  ]),
  ...make("Mathematics", [
    { id:"2027-math-fixed", theme:"Functions", prompt:"A continuous function maps the interval [0,1] into itself. Under what conditions might you expect a fixed point, and how could you argue for one geometrically?", followUps:["What function would you construct to compare f(x) with x?","Where could a sign change arise?","Which assumption is doing the real work?"], mutation:"Now remove continuity. Can you build a counterexample?", interviewerFocus:["continuity","fixed points","proof","counterexamples"] },
    { id:"2027-math-invariant", theme:"Problem solving", prompt:"Numbers are written around a circle and an operation repeatedly replaces two neighbours by their average. What quantities might remain unchanged or move monotonically?", followUps:["What happens to the total?","What happens to the range?","Can you use that to predict long-run behaviour?"], mutation:"Now replace the average by a weighted average.", interviewerFocus:["invariants","monotonicity","convergence","generalisation"] },
    { id:"2027-math-graph", theme:"Proof", prompt:"Every person at a party shakes hands with some number of others. Explain why two people must have shaken hands with the same number of people.", followUps:["What are the possible handshake counts?","Can 0 and n−1 both occur?","Where exactly does the pigeonhole principle enter?"], mutation:"Now require every person to have shaken at least one hand.", interviewerFocus:["pigeonhole principle","graphs","proof","edge cases"] },
  ]),
  ...make("Computer Science", [
    { id:"2027-cs-hash", theme:"Data structures", prompt:"A hash table gives fast lookup on average. Why is 'on average' an important qualification?", followUps:["What creates collisions?","How could an adversary make performance worse?","What properties would you want from a hash function?"], mutation:"Now memory is limited and the table must run at very high occupancy.", interviewerFocus:["hashing","complexity","collisions","trade-offs"] },
    { id:"2027-cs-network", theme:"Networks", prompt:"A message crosses several unreliable network links. Where would you put mechanisms for detecting and recovering from lost data?", followUps:["Why might end-to-end checking still be needed?","What is the cost of retransmission?","How would latency change your design?"], mutation:"Now the network occasionally duplicates rather than loses packets.", interviewerFocus:["reliability","layers","latency","protocol design"] },
    { id:"2027-cs-greedy", theme:"Algorithms", prompt:"A greedy algorithm always takes the locally best next step. Why can that fail even when every individual choice seems sensible?", followUps:["Can you construct a counterexample?","What property would make greediness safe?","How might dynamic programming differ?"], mutation:"Now the problem has a matroid-like exchange property. What becomes plausible?", interviewerFocus:["greedy algorithms","counterexamples","optimality","structure"] },
  ]),
  ...make("Biology", [
    { id:"2027-bio-resistance", theme:"Evolution", prompt:"A bacterial population becomes resistant after antibiotic exposure. Why is it misleading to say the antibiotic caused individual bacteria to adapt because they needed to?", followUps:["Where does variation come from?","How does selection change frequencies?","What experiment could distinguish selection from induced change?"], mutation:"Now resistance carries a fitness cost when the antibiotic is removed.", interviewerFocus:["selection","variation","fitness","experiments"] },
    { id:"2027-bio-gradient", theme:"Physiology", prompt:"An organ exchanges substances across a membrane. What features could increase exchange without simply making the organ larger?", followUps:["How does surface area help?","Why maintain a concentration gradient?","When does diffusion distance become limiting?"], mutation:"Now blood flow through the organ is halved.", interviewerFocus:["diffusion","surface area","gradients","transport"] },
    { id:"2027-bio-gene", theme:"Regulation", prompt:"Two cells contain the same DNA but produce very different proteins. What mechanisms could create that difference?", followUps:["Where can regulation occur?","How could chromatin matter?","How would you test whether transcription or translation is the main difference?"], mutation:"Now the cells rapidly switch states after a signal.", interviewerFocus:["gene expression","regulation","experiments","mechanism"] },
  ]),
  ...make("Medicine", [
    { id:"2027-med-test", theme:"Diagnostic reasoning", prompt:"A diagnostic test is very sensitive but only moderately specific. What kinds of errors should you expect, and when might that trade-off be useful?", followUps:["What is a false positive?","How does prevalence affect interpretation?","Why might screening favour sensitivity?"], mutation:"Now confirmatory testing is expensive and invasive.", interviewerFocus:["sensitivity","specificity","base rates","trade-offs"] },
    { id:"2027-med-cause", theme:"Evidence", prompt:"Patients who exercise more have lower rates of a disease. Why is that not enough to conclude exercise alone caused the difference?", followUps:["Name plausible confounders.","What would randomisation solve and not solve?","What evidence could strengthen causal inference if a trial is impossible?"], mutation:"Now a dose-response relationship is observed across several independent cohorts.", interviewerFocus:["causation","confounding","study design","evidence"] },
    { id:"2027-med-consent", theme:"Ethics", prompt:"A competent patient refuses a treatment that clinicians strongly recommend. What principles are in tension?", followUps:["What information is needed for valid consent or refusal?","When does capacity matter?","Does disagreement prove incapacity?"], mutation:"Now the patient cannot communicate and has no recorded wishes.", interviewerFocus:["autonomy","capacity","beneficence","reasoning"] },
  ]),
  ...make("Natural Sciences", [
    { id:"2027-ns-scale", theme:"Cross-disciplinary", prompt:"Why do many biological and physical systems behave differently when scaled up, even if their shape stays similar?", followUps:["Compare how area and volume scale.","Give a biological consequence.","Give an engineering consequence."], mutation:"Now the system is elongated rather than geometrically similar.", interviewerFocus:["scaling","surface area","modelling","transfer"] },
    { id:"2027-ns-feedback", theme:"Systems", prompt:"Give a mechanistic explanation for how negative feedback can stabilise a system without keeping it perfectly constant.", followUps:["What creates the restoring response?","Why can delays cause oscillation?","How would positive feedback differ?"], mutation:"Now the feedback has a long time delay.", interviewerFocus:["feedback","stability","oscillation","mechanism"] },
    { id:"2027-ns-data", theme:"Experimental reasoning", prompt:"Two experiments give different estimates of the same constant. How would you decide whether the difference reflects random uncertainty, systematic error or a real contextual effect?", followUps:["What would replication tell you?","How would calibration help?","What pattern would suggest context dependence?"], mutation:"Now both experiments are individually very precise.", interviewerFocus:["uncertainty","systematic error","replication","inference"] },
  ]),
  ...make("Economics", [
    { id:"2027-eco-price", theme:"Markets", prompt:"Why can a higher price sometimes increase rather than reduce the quantity of a good supplied over time?", followUps:["Distinguish movement along a supply curve from a shift.","How do entry and investment matter?","What happens if capacity is fixed in the short run?"], mutation:"Now the good requires ten years to produce.", interviewerFocus:["supply","time horizons","investment","elasticity"] },
    { id:"2027-eco-externality", theme:"Policy", prompt:"A factory produces a useful product but also creates pollution. Build a framework for deciding whether a tax could improve the outcome.", followUps:["What is the external cost?","Why does the correct tax depend on marginal rather than total damage?","What information would be hard to estimate?"], mutation:"Now pollution damage varies sharply by location.", interviewerFocus:["externalities","Pigouvian tax","margins","information"] },
    { id:"2027-eco-selection", theme:"Information", prompt:"An insurer raises prices and then finds that its customer pool becomes riskier. Give a mechanism that could explain this.", followUps:["How could adverse selection arise?","What information asymmetry matters?","What policy or contract design could reduce the problem?"], mutation:"Now insurers can observe one imperfect risk signal.", interviewerFocus:["adverse selection","information","incentives","contracts"] },
  ]),
  ...make("PPE", [
    { id:"2027-ppe-liberty", theme:"Political philosophy", prompt:"Is restricting one person's freedom ever necessary to protect the freedom of others? Build a criterion rather than answering with a slogan.", followUps:["What counts as harm?","Does offence count?","How should uncertainty about future harm matter?"], mutation:"Now the restriction is temporary and reviewable rather than permanent.", interviewerFocus:["liberty","harm","proportionality","criteria"] },
    { id:"2027-ppe-measure", theme:"Political economy", prompt:"A government announces that wellbeing has risen because GDP per person increased. What important possibilities are hidden by that claim?", followUps:["How does distribution matter?","What is omitted from GDP?","When might GDP still be useful?"], mutation:"Now median household income falls while GDP per person rises.", interviewerFocus:["measurement","distribution","welfare","interpretation"] },
    { id:"2027-ppe-truth", theme:"Epistemology", prompt:"If two well-informed people examine the same evidence and disagree, must at least one be irrational?", followUps:["Could prior beliefs matter?","What counts as reasonable weighting of evidence?","When should disagreement reduce confidence?"], mutation:"Now one person has a strong financial incentive to prefer one conclusion.", interviewerFocus:["evidence","rational disagreement","bias","confidence"] },
  ]),
  ...make("Law", [
    { id:"2027-law-causation", theme:"Causation", prompt:"A driver negligently blocks a road; an ambulance is delayed and a patient dies. What would a legal test for causation need to distinguish?", followUps:["Is factual causation enough?","How remote can a consequence be?","Should foreseeability matter?"], mutation:"Now the ambulance would probably have arrived too late even without the obstruction.", interviewerFocus:["causation","remoteness","foreseeability","counterfactuals"] },
    { id:"2027-law-rule", theme:"Interpretation", prompt:"A rule bans 'dangerous objects' from a building. How should an interpreter decide whether an ordinary glass bottle is covered?", followUps:["Should inherent properties or context matter more?","What role does purpose play?","How would you avoid arbitrary exceptions?"], mutation:"Now the bottle has been broken and is being carried during an argument.", interviewerFocus:["interpretation","purpose","context","consistency"] },
    { id:"2027-law-liability", theme:"Responsibility", prompt:"Should someone be legally responsible for harm they could not reasonably have predicted?", followUps:["What values support fault-based liability?","When might strict liability be justified?","Who is best placed to insure against the risk?"], mutation:"Now the activity creates unusual but very serious risks to the public.", interviewerFocus:["fault","strict liability","risk","policy"] },
  ]),
  ...make("History", [
    { id:"2027-hist-number", theme:"Quantitative evidence", prompt:"A census shows a city's population doubled in thirty years. What historical conclusions can you draw safely, and what remains unknown?", followUps:["Could boundaries have changed?","What does the total hide about migration and birth rates?","Which complementary sources would you seek?"], mutation:"Now you discover the census method changed halfway through the period.", interviewerFocus:["quantitative evidence","measurement","corroboration","inference"] },
    { id:"2027-hist-counter", theme:"Counterfactuals", prompt:"Can counterfactual questions improve historical explanation, or are they merely speculation?", followUps:["What makes a counterfactual disciplined?","How can it test causal importance?","Where does the method become too unconstrained?"], mutation:"Now consider removing a structural factor rather than an individual decision.", interviewerFocus:["counterfactuals","causation","method","constraints"] },
    { id:"2027-hist-memory", theme:"Memory", prompt:"An eyewitness gives a vivid account forty years after an event. Does vividness make the source more reliable?", followUps:["How can memory change?","Can later interpretation reshape recollection?","What corroboration would matter most?"], mutation:"Now the witness kept a diary written immediately after the event.", interviewerFocus:["memory","reliability","corroboration","source criticism"] },
  ]),
  ...make("English", [
    { id:"2027-englit-opening", theme:"Close reading", prompt:"A novel opens: 'By noon, everyone had agreed not to mention the rain.' What questions does that sentence make you ask about voice, community and omission?", followUps:["What does 'everyone' imply?","Why might the time marker matter?","How does not mentioning something make it more present?"], mutation:"Now imagine this is the final sentence instead of the opening.", interviewerFocus:["close reading","implication","structure","voice"] },
    { id:"2027-englit-metaphor", theme:"Language", prompt:"When does a metaphor stop feeling metaphorical and become ordinary language?", followUps:["Can a dead metaphor still shape thought?","How would context revive it?","Does the author's intention matter?"], mutation:"Now compare a scientific metaphor with a poetic one.", interviewerFocus:["metaphor","convention","meaning","context"] },
    { id:"2027-englit-form", theme:"Form", prompt:"Can the form of a text contradict what its speaker claims? Give a mechanism by which that could happen.", followUps:["How could rhythm or syntax undermine certainty?","What role might repetition play?","How would you distinguish contradiction from complexity?"], mutation:"Now apply the idea to a dramatic monologue.", interviewerFocus:["form","voice","irony","interpretation"] },
  ]),
  ...make("Geography", [
    { id:"2027-geo-flood", theme:"Physical geography", prompt:"A river floods more frequently after urban development upstream. Build a causal explanation and identify evidence that could falsify it.", followUps:["How does infiltration change?","What happens to lag time?","Which other changes could confound the comparison?"], mutation:"Now extensive green roofs are introduced across the catchment.", interviewerFocus:["hydrology","causation","data","urbanisation"] },
    { id:"2027-geo-map", theme:"Spatial reasoning", prompt:"Two maps of the same city suggest very different levels of inequality. How could choices of scale and classification create that difference?", followUps:["What is the modifiable areal unit problem?","How do class boundaries affect visual interpretation?","What data would you inspect behind the map?"], mutation:"Now compare census tracts with household-level data.", interviewerFocus:["mapping","scale","classification","data interpretation"] },
    { id:"2027-geo-migration", theme:"Human geography", prompt:"A region experiences rapid net migration but little population growth. Give several mechanisms that could make both statements true.", followUps:["How can age structure matter?","What role could internal migration play?","Which demographic rates would you request?"], mutation:"Now the region also has rising average age.", interviewerFocus:["migration","demography","composition","inference"] },
  ]),
]

export const courseInterviewBankExpanded2027 = [...courseInterviewBank, ...courseInterviewBank2027]

export const coursesWithDeepBanks2027 = Array.from(new Set(courseInterviewBankExpanded2027.map(item => item.course))).sort()

export function promptsForCourse2027(course: string) {
  const key = course.trim().toLowerCase()
  const exact = courseInterviewBankExpanded2027.filter(item => item.course.toLowerCase() === key)
  if (exact.length) return exact
  if (/engineering/.test(key)) return courseInterviewBankExpanded2027.filter(item => item.course === "Engineering")
  if (/physics/.test(key)) return courseInterviewBankExpanded2027.filter(item => item.course === "Physics")
  if (/chem/.test(key)) return courseInterviewBankExpanded2027.filter(item => item.course === "Chemistry")
  if (/materials/.test(key)) return courseInterviewBankExpanded2027.filter(item => item.course === "Materials Science")
  if (/computer|computing/.test(key)) return courseInterviewBankExpanded2027.filter(item => item.course === "Computer Science")
  if (/math/.test(key)) return courseInterviewBankExpanded2027.filter(item => item.course === "Mathematics")
  if (/medicine|medical/.test(key)) return courseInterviewBankExpanded2027.filter(item => item.course === "Medicine")
  if (/biology|biomedical|biochem/.test(key)) return courseInterviewBankExpanded2027.filter(item => item.course === "Biology")
  if (/natural science/.test(key)) return courseInterviewBankExpanded2027.filter(item => item.course === "Natural Sciences")
  if (/econom/.test(key)) return courseInterviewBankExpanded2027.filter(item => item.course === "Economics")
  if (/ppe|politic|philosoph/.test(key)) return courseInterviewBankExpanded2027.filter(item => item.course === "PPE")
  if (/law|jurisprudence/.test(key)) return courseInterviewBankExpanded2027.filter(item => item.course === "Law")
  if (/history/.test(key)) return courseInterviewBankExpanded2027.filter(item => item.course === "History")
  if (/english|literature/.test(key)) return courseInterviewBankExpanded2027.filter(item => item.course === "English")
  if (/geograph/.test(key)) return courseInterviewBankExpanded2027.filter(item => item.course === "Geography")
  return courseInterviewBankExpanded2027
}
