import type { TestQuestion } from "@/lib/oxbridge-data"

function rotate<T>(items: T[], shift: number) {
  const n = ((shift % items.length) + items.length) % items.length
  return [...items.slice(n), ...items.slice(0, n)]
}

function q(id: string, section: string, prompt: string, correct: string, distractors: [string, string, string], explanation: string, seed: number): TestQuestion {
  const options = rotate([correct, ...distractors], seed % 4)
  return { id, test: "ESAT", section, difficulty: seed % 2 ? "Stretch" : "Challenge", prompt, options, answer: options.indexOf(correct), explanation }
}

export const esatSpecificationReserveBank: TestQuestion[] = [
  q("esat-spec-m1-units-c", "Mathematics 1", "A rectangular field has area 0.006 km². What is its area in m²?", "6000 m²", ["60 m²", "600 m²", "60000 m²"], "Since 1 km² = 1,000,000 m², 0.006 km² = 6000 m².", 1),
  q("esat-spec-m1-number-c", "Mathematics 1", "Write 0.00072 in standard form.", "7.2 × 10⁻⁴", ["7.2 × 10⁻³", "72 × 10⁻⁴", "0.72 × 10⁻⁴"], "Standard form has a coefficient from 1 up to 10, so moving the decimal four places gives 7.2 × 10⁻⁴.", 2),
  q("esat-spec-m1-geometry-c", "Mathematics 1", "A sector is one quarter of a circle of radius 8 cm. What is its area?", "16π cm²", ["8π cm²", "32π cm²", "64π cm²"], "The full-circle area is 64π cm², so one quarter has area 16π cm².", 3),
  q("esat-spec-m1-statistics-c", "Mathematics 1", "A data set has lower quartile 12 and upper quartile 31. What is its interquartile range?", "19", ["12", "21", "43"], "The interquartile range is Q3 − Q1 = 31 − 12 = 19.", 4),
  q("esat-spec-m1-probability-c", "Mathematics 1", "A fair spinner has eight equal sectors, three of which are green. What is the probability of not landing on green?", "5/8", ["3/8", "3/5", "5/3"], "Five of the eight sectors are not green, so the required probability is 5/8.", 5),

  q("esat-spec-m2-algebra-c", "Mathematics 2", "If f(x)=2x−1 and g(x)=x², what is f(g(3))?", "17", ["25", "32", "35"], "g(3)=9, then f(9)=2×9−1=17.", 6),
  q("esat-spec-m2-sequences-c", "Mathematics 2", "The geometric sequence 160, 80, 40, … continues indefinitely. What is its sum to infinity?", "320", ["240", "280", "400"], "For first term 160 and ratio 1/2, S∞=160/(1−1/2)=320.", 7),
  q("esat-spec-m2-integration-c", "Mathematics 2", "The curve has gradient function dy/dx=6x and passes through (1,5). Which equation describes the curve?", "y=3x²+2", ["y=6x²−1", "y=3x²+5", "y=6x+1"], "Integrating gives y=3x²+C. Using (1,5) gives 5=3+C, so C=2.", 8),
  q("esat-spec-m2-graphs-c", "Mathematics 2", "Which transformation maps y=x² to y=(x−4)²?", "A translation 4 units to the right.", ["A translation 4 units upward.", "A translation 4 units to the left.", "A vertical stretch by factor 4."], "Replacing x by x−4 shifts every point on the graph four units to the right.", 9),

  q("esat-spec-physics-magnetism-c", "Physics", "A current-carrying conductor is placed parallel to a uniform magnetic field. What magnetic force acts on the straight conductor?", "Zero", ["A force of BIL", "A force of BI/L", "A force that must double the current"], "The force is F=BIL sin θ; for a conductor parallel to the field θ=0°, so the force is zero.", 10),
  q("esat-spec-physics-thermal-c", "Physics", "A fixed mass of ideal gas is heated at constant volume. Which change is expected?", "Its pressure increases.", ["Its pressure decreases.", "Its pressure stays fixed while temperature rises.", "Its volume must double immediately."], "At constant volume and fixed amount of gas, pressure is proportional to absolute temperature, so heating raises the pressure.", 11),
  q("esat-spec-physics-radioactivity-c", "Physics", "Which type of nuclear radiation has the greatest penetrating power through matter?", "Gamma radiation", ["Alpha radiation", "Beta radiation", "All three have equal penetration"], "Gamma radiation is the most penetrating of alpha, beta and gamma radiation; alpha is the least penetrating.", 12),

  q("esat-spec-chem-reactions-c", "Chemistry", "For an equilibrium reaction at constant temperature, which change can alter the equilibrium position without changing the equilibrium constant?", "Changing the concentration of a reactant", ["Adding a catalyst", "Grinding a solid catalyst more finely", "Increasing catalyst concentration only"], "Changing concentration changes the reaction quotient and can shift equilibrium; at fixed temperature the equilibrium constant is unchanged.", 13),
  q("esat-spec-chem-bonding-c", "Chemistry", "Which feature best explains why metals conduct electricity when solid?", "Delocalised electrons can move through the lattice.", ["Positive ions move freely through the solid.", "Neutral molecules exchange protons through the lattice.", "Covalent bonds continuously break and reform between molecules."], "Metallic structures contain delocalised electrons that can move and carry charge while the positive ions remain in fixed lattice positions.", 14),
  q("esat-spec-chem-acids-c", "Chemistry", "Which ion is responsible for the acidic properties of an aqueous acid solution?", "H⁺(aq)", ["OH⁻(aq)", "Na⁺(aq)", "Cl⁻(aq) in every acid"], "Acids in aqueous solution produce hydrogen ions; alkalis instead produce hydroxide ions.", 15),
  q("esat-spec-chem-energetics-c", "Chemistry", "Two reactions use the same reactants and products, but one is catalysed. Which energy quantity is lower for the catalysed pathway?", "Activation energy", ["Energy of the reactants", "Energy of the products", "Overall enthalpy change"], "A catalyst supplies an alternative pathway with lower activation energy while leaving reactant, product and overall enthalpy levels unchanged.", 16),
  q("esat-spec-chem-electroorganic-c", "Chemistry", "Which general formula describes an acyclic alkene containing one carbon-carbon double bond?", "CₙH₂ₙ", ["CₙH₂ₙ₊₂", "CₙH₂ₙ₋₂", "CₙHₙ"], "An acyclic hydrocarbon with one C=C double bond has two fewer hydrogen atoms than the corresponding alkane, giving CₙH₂ₙ.", 17),
  q("esat-spec-chem-analysis-c", "Chemistry", "A gas turns damp red litmus paper blue. Which gas is most consistent with this observation?", "Ammonia", ["Carbon dioxide", "Hydrogen", "Oxygen"], "Ammonia dissolves in water on the paper to form an alkaline solution, turning red litmus blue.", 18),

  q("esat-spec-bio-cells-c", "Biology", "Why do active-transport processes require energy from respiration?", "They can move substances against a concentration gradient.", ["They move water only by osmosis.", "They make diffusion occur without particles.", "They remove the need for membrane proteins."], "Active transport uses energy to move substances against their concentration gradient through membrane transport proteins.", 19),
  q("esat-spec-bio-evolution-c", "Biology", "Which process produces new combinations of alleles in sexually reproducing organisms?", "Meiosis and random fertilisation", ["Binary fission only", "Mitosis without mutation", "Identical cloning of one parent"], "Meiosis generates genetically varied gametes and random fertilisation combines alleles from two gametes in new ways.", 20),
  q("esat-spec-bio-enzymes-c", "Biology", "A competitive inhibitor reduces enzyme activity. Which explanation best describes its action?", "It competes with substrate for the enzyme's active site.", ["It permanently becomes the enzyme's product.", "It removes every substrate molecule from solution.", "It increases the number of active sites on each enzyme."], "A competitive inhibitor has sufficient similarity to the substrate to bind at the active site and reduce substrate binding.", 21),
  q("esat-spec-bio-physiology-c", "Biology", "Why does heart rate usually increase during vigorous exercise?", "To deliver oxygen and glucose to respiring muscles more rapidly.", ["To stop blood reaching skeletal muscles.", "To reduce carbon dioxide removal from tissues.", "To make diffusion distances in cells longer."], "Working muscles respire faster, so increased cardiac output helps deliver substrates and remove carbon dioxide more quickly.", 22),
  q("esat-spec-bio-immunity-c", "Biology", "What is the role of antibodies in a specific immune response?", "They bind specifically to antigens.", ["They digest every pathogen directly as enzymes.", "They transport oxygen around the body.", "They replace memory cells after infection."], "Antibodies have binding sites complementary to particular antigens and can help neutralise or mark pathogens for destruction.", 23),
  q("esat-spec-bio-plants-c", "Biology", "Which tissue transports dissolved sugars such as sucrose from sources to sinks in a plant?", "Phloem", ["Xylem", "Epidermis", "Palisade mesophyll"], "Phloem carries assimilates such as sucrose between sources and sinks by translocation.", 24),
]
