export type TrackId = "maths" | "physical" | "life" | "law" | "humanities" | "economics" | "languages"
export type University = "Oxford" | "Cambridge" | "Both" | "Undecided"

export type InterviewQuestion = {
  id: string
  track: TrackId
  title: string
  prompt: string
  stimulus?: string
  difficulty: "Foundation" | "Stretch" | "Challenge"
  time: number
  probes: string[]
  concepts: string[]
  strongAnswer: string
}

export type TestQuestion = {
  id: string
  test: "TMUA" | "ESAT" | "TARA" | "LNAT" | "UCAT"
  section: string
  difficulty: "Foundation" | "Stretch" | "Challenge"
  prompt: string
  options: string[]
  answer: number
  explanation: string
}

export const tracks: Array<{ id: TrackId; name: string; short: string; courses: string[]; skills: string[]; tests: string[] }> = [
  { id: "maths", name: "Mathematics & Computer Science", short: "Maths & CS", courses: ["Mathematics", "Computer Science", "Mathematics and Philosophy", "Mathematics and Computer Science"], skills: ["proof", "abstraction", "pattern-finding", "clear assumptions"], tests: ["TMUA", "STEP (Cambridge Mathematics offer holders)"] },
  { id: "physical", name: "Physics, Engineering & Chemistry", short: "Physical sciences", courses: ["Physics", "Engineering", "Chemistry", "Materials Science", "Earth Sciences"], skills: ["modelling", "estimation", "units", "experimental reasoning"], tests: ["ESAT for relevant Oxford/Cambridge courses"] },
  { id: "life", name: "Biology, Medicine & Natural Sciences", short: "Life sciences", courses: ["Medicine", "Biomedical Sciences", "Biology", "Natural Sciences", "Psychology"], skills: ["data interpretation", "mechanisms", "hypotheses", "ethical reasoning"], tests: ["UCAT for Medicine", "ESAT for selected science courses", "TARA for selected Oxford courses"] },
  { id: "law", name: "Law", short: "Law", courses: ["Law", "Law with Law Studies in Europe", "Jurisprudence"], skills: ["logical argument", "counterexamples", "text analysis", "qualification"], tests: ["LNAT for Oxford and Cambridge Law"] },
  { id: "humanities", name: "History, Philosophy, Politics & Geography", short: "Humanities", courses: ["History", "Philosophy", "Politics", "Geography", "HSPS", "Theology"], skills: ["source evaluation", "conceptual distinctions", "evidence", "alternative interpretations"], tests: ["TARA for selected Oxford courses", "College assessment where specified"] },
  { id: "economics", name: "Economics, PPE & Management", short: "Economics & PPE", courses: ["Economics", "Economics and Management", "PPE", "Land Economy", "History and Economics"], skills: ["incentives", "trade-offs", "quantitative reasoning", "evaluating assumptions"], tests: ["TARA for selected Oxford courses", "TMUA for Cambridge Economics"] },
  { id: "languages", name: "English, Languages & Classics", short: "Languages & literature", courses: ["English", "Modern Languages", "Classics", "Linguistics", "Asian and Middle Eastern Studies"], skills: ["close reading", "interpretation", "language awareness", "defending a reading"], tests: ["Course or college assessment where specified"] },
]

export const interviewQuestions: InterviewQuestion[] = [
  { id: "m1", track: "maths", title: "The painted cube", difficulty: "Foundation", time: 6, prompt: "A large cube is painted on every outer face, then cut into 27 equal small cubes. How many small cubes have exactly two painted faces? Explain a method that still works if it is cut into n³ cubes.", probes: ["What happens at the corners?", "Can you express your result for any n ≥ 2?", "Test your rule for n = 2."], concepts: ["edge", "corner", "twelve", "n-2", "count", "general"], strongAnswer: "Separate edge cubes from corners. Each of the 12 edges has n−2 non-corner cubes, each with exactly two painted faces, giving 12(n−2). For n=3 this is 12. Checking n=2 gives zero, which fits because every small cube is a corner cube." },
  { id: "m2", track: "maths", title: "A suspicious algorithm", difficulty: "Stretch", time: 7, prompt: "A program checks whether an integer is prime by testing divisibility by every integer from 2 up to n−1. How would you improve it, and why is your stopping point valid?", probes: ["Suppose n has a factor larger than √n.", "What must be true of the paired factor?", "How would you handle n < 2?"], concepts: ["square root", "factor", "pair", "divisibility", "complexity", "prime"], strongAnswer: "Only test possible divisors up to √n. If n=ab and both a and b were greater than √n, their product would exceed n; therefore a composite n has at least one factor at most √n. Reject n<2 and handle 2 separately or include it in the loop." },
  { id: "m3", track: "maths", title: "Infinite hotel", difficulty: "Challenge", time: 8, prompt: "A hotel has rooms numbered 1, 2, 3, … and every room is occupied. One new guest arrives. Can the hotel accommodate them? What if infinitely many new guests arrive?", probes: ["Give an explicit reassignment rule.", "Does this prove there are different sizes of infinity?", "What changes if rooms were indexed by real numbers?"], concepts: ["bijection", "mapping", "n+1", "2n", "countable", "infinity"], strongAnswer: "For one guest, move the occupant of room n to n+1 and use room 1. For countably many guests, move occupant n to 2n and place new guest k in room 2k−1. This demonstrates a bijection with a proper subset for countably infinite sets, not that all infinities are equal." },
  { id: "p1", track: "physical", title: "Cooling tea", difficulty: "Foundation", time: 6, prompt: "Two identical cups contain equally hot tea. Milk is added to cup A immediately and to cup B just before drinking ten minutes later. Which drink is cooler at the end? State your assumptions and justify your reasoning.", probes: ["How does temperature difference affect the cooling rate?", "What if evaporation matters?", "Which measurement would test your claim?"], concepts: ["temperature difference", "rate", "Newton", "energy", "assumption", "experiment"], strongAnswer: "Under Newton's law of cooling, the hotter cup initially loses energy faster because heat-loss rate depends on its temperature difference from the surroundings. Adding milk early lowers that difference, so cup A generally loses less energy to the room and is warmer at the end. The conclusion depends on equal milk temperature, volumes, evaporation and mixing." },
  { id: "p2", track: "physical", title: "Estimate the atmosphere", difficulty: "Stretch", time: 8, prompt: "Estimate the total mass of Earth's atmosphere using quantities you could reasonably know. Talk through every approximation.", probes: ["How is pressure related to weight?", "What area is the atmosphere acting over?", "Check the units of your expression."], concepts: ["pressure", "area", "weight", "gravity", "4πr", "estimate"], strongAnswer: "Use pressure = force/area, so atmospheric weight is p×4πR² and mass is p4πR²/g. With p≈10⁵ Pa, R≈6.4×10⁶ m and g≈10 m s⁻², the mass is about 5×10¹⁸ kg. This treats sea-level pressure as representative and ignores topography." },
  { id: "p3", track: "physical", title: "Design a fair sensor", difficulty: "Challenge", time: 8, prompt: "A low-cost air-quality sensor reports values that drift with humidity. How would you determine whether a sudden pollution spike is real?", probes: ["What controls would you use?", "How would you separate correlation from causation?", "What result would change your conclusion?"], concepts: ["control", "calibration", "humidity", "replicate", "correlation", "uncertainty"], strongAnswer: "Compare with a calibrated reference instrument, measure humidity simultaneously, repeat across locations and use a blank or filtered-air control. Model the sensor's humidity response from baseline data, correct for it, then check whether the residual spike appears in independent sensors. Report uncertainty and a falsifying result." },
  { id: "b1", track: "life", title: "Bigger cells", difficulty: "Foundation", time: 6, prompt: "Why are cells usually small? If a cell doubled in every linear dimension, what would happen to its surface-area-to-volume ratio?", probes: ["Scale area and volume separately.", "Why does this matter for exchange?", "Can a large cell overcome the problem?"], concepts: ["surface area", "volume", "diffusion", "square", "cube", "ratio"], strongAnswer: "Surface area scales with length squared while volume scales with length cubed. Doubling length multiplies area by 4 and volume by 8, so the ratio halves. Exchange capacity per unit volume falls; adaptations such as folds, internal transport and elongated shapes can compensate." },
  { id: "b2", track: "life", title: "Unexpected trial result", difficulty: "Stretch", time: 8, prompt: "A treatment group recovers faster than a control group, but the treatment group was younger on average. What can and cannot be concluded?", probes: ["Name the problem in the design.", "How would randomisation help?", "What further analysis would you request?"], concepts: ["confound", "age", "random", "causation", "control", "sample"], strongAnswer: "The data show an association, not necessarily a treatment effect, because age is a confounder. Random allocation should balance known and unknown factors on average. I would examine baseline comparability, stratify or adjust for age, inspect uncertainty and seek a suitably powered randomised replication." },
  { id: "l1", track: "law", title: "The park rule", difficulty: "Foundation", time: 7, stimulus: "A sign says: ‘No vehicles in the park.’ A paramedic drives an ambulance into the park to help an injured runner.", prompt: "Has the rule been broken? Develop arguments for both interpretations before reaching a provisional view.", probes: ["What is the rule's likely purpose?", "Would your answer change for an electric toy car?", "Who should decide exceptions?"], concepts: ["literal", "purpose", "exception", "vehicle", "harm", "interpretation"], strongAnswer: "Literally, an ambulance is a vehicle, so the wording covers it. Purposively, the rule likely protects safety and tranquillity, while emergency access advances safety. A defensible conclusion is that the conduct falls within the words but should be treated as an implied necessity exception; the toy-car counterexample shows why context and purpose matter." },
  { id: "l2", track: "law", title: "Promise and reliance", difficulty: "Challenge", time: 8, prompt: "Should every promise that another person relies on be legally enforceable? Build a rule, then test it against a casual promise between friends.", probes: ["How serious must the reliance be?", "Does intention matter?", "What costs follow from enforcing too much?"], concepts: ["reliance", "intention", "reasonable", "harm", "evidence", "rule"], strongAnswer: "Not every relied-on promise should be enforceable. A possible rule requires clear assurance, reasonable and foreseeable reliance, significant detriment and circumstances making enforcement just. Casual social promises may lack intent and reliable evidence. The rule balances protection from harmful reliance against freedom from excessive legal intrusion." },
  { id: "h1", track: "humanities", title: "Reading a source", difficulty: "Foundation", time: 7, stimulus: "A minister's diary calls a protest ‘small, disorderly and unrepresentative’; a local newspaper describes the same event as ‘the largest peaceful gathering in a generation’.", prompt: "How would a historian use these sources without simply deciding that one is true and the other false?", probes: ["What can provenance tell you?", "What evidence would you seek next?", "Can bias itself be useful evidence?"], concepts: ["provenance", "purpose", "audience", "corroborate", "bias", "context"], strongAnswer: "Treat each as evidence of both the event and the author's position. Ask about purpose, audience, access and language; compare independent records such as photographs, police logs and multiple accounts. Their disagreement may reveal political stakes. A source can be factually limited yet valuable evidence of contemporary attitudes." },
  { id: "h2", track: "humanities", title: "Can freedom be measured?", difficulty: "Challenge", time: 8, prompt: "Can one society be objectively described as freer than another? Define freedom before you compare them.", probes: ["Distinguish negative and positive freedom.", "How would you weight competing dimensions?", "Could more law sometimes increase freedom?"], concepts: ["definition", "negative", "positive", "rights", "capacity", "trade-off"], strongAnswer: "A comparison requires a stated conception: absence of interference, effective capability, political participation, or a combination. Indicators can then be measured, but weighting them remains value-laden. Law may restrict some action while protecting others from coercion, so a transparent multi-dimensional comparison is stronger than a single supposedly neutral score." },
  { id: "e1", track: "economics", title: "Free bus travel", difficulty: "Foundation", time: 7, prompt: "A city makes all bus travel free. Predict two intended and two unintended effects. What information would you need before judging the policy?", probes: ["What happens to demand and crowding?", "Who gains most?", "What is the opportunity cost?"], concepts: ["demand", "substitute", "crowding", "equity", "cost", "elasticity"], strongAnswer: "Intended effects include greater access and substitution away from cars. Unintended effects could include crowding and journeys shifting from walking rather than driving. Evaluation needs ridership by prior mode and income, capacity, marginal operating costs, congestion and emissions. The tax cost and alternative uses of funds are part of the opportunity cost." },
  { id: "e2", track: "economics", title: "Rational choice?", difficulty: "Stretch", time: 8, prompt: "If people often make predictable mistakes, should economists abandon the assumption of rational choice?", probes: ["What makes a model useful?", "Can an unrealistic assumption still predict well?", "How could you test competing models?"], concepts: ["model", "prediction", "assumption", "behaviour", "test", "bounded"], strongAnswer: "Not necessarily. Rational choice is a simplifying benchmark whose value depends on explanatory and predictive success. Where deviations are systematic, bounded-rationality or behavioural models may perform better. Compare out-of-sample predictions and prefer the simplest model adequate for the decision, rather than judging assumptions by realism alone." },
  { id: "g1", track: "languages", title: "The unreliable voice", difficulty: "Stretch", time: 8, stimulus: "A narrator insists three times that they remember an event ‘perfectly’, while changing one small detail in each account.", prompt: "What interpretations does this pattern invite, and what further features of the passage would help you decide between them?", probes: ["Could repetition create irony?", "Distinguish the author from the narrator.", "What would count against your preferred reading?"], concepts: ["narrator", "repetition", "irony", "structure", "evidence", "alternative"], strongAnswer: "The insistence may undermine rather than secure reliability: repetition and shifting detail can suggest self-deception, trauma, manipulation or ordinary uncertainty. I would inspect diction, chronology, focalisation and other characters' accounts. The narrator is not identical to the author, and a strong reading states what textual evidence could favour a rival interpretation." },
]

export const testQuestions: TestQuestion[] = [
  { id:"t1", test:"TMUA", section:"Mathematical reasoning", difficulty:"Foundation", prompt:"For all real x, which expression is always non-negative?", options:["x³ − x", "x² − 4x + 4", "2x − 1", "x² − 4"], answer:1, explanation:"x² − 4x + 4 = (x − 2)², and every real square is non-negative." },
  { id:"t2", test:"TMUA", section:"Logic and proof", difficulty:"Stretch", prompt:"A statement says: ‘If n² is even, then n is even.’ Which is its contrapositive?", options:["If n is even, n² is even", "If n² is odd, n is odd", "If n is odd, n² is odd", "If n is not even, n² may be even"], answer:2, explanation:"The contrapositive of P→Q is not-Q→not-P: if n is odd, then n² is odd." },
  { id:"t3", test:"TMUA", section:"Problem solving", difficulty:"Challenge", prompt:"A sequence has a₁=2 and aₙ₊₁=2aₙ+1. Which formula is correct?", options:["2ⁿ", "3·2ⁿ⁻¹−1", "2ⁿ+1", "3ⁿ−1"], answer:1, explanation:"Let bₙ=aₙ+1. Then bₙ₊₁=2bₙ and b₁=3, so bₙ=3·2ⁿ⁻¹ and aₙ=bₙ−1." },
  { id:"s1", test:"ESAT", section:"Mathematics 1", difficulty:"Foundation", prompt:"A quantity Q=mv²/r. If m has units kg, v has units m s⁻¹ and r has units m, what are the units of Q?", options:["kg m s⁻¹", "kg m s⁻²", "kg m² s⁻²", "kg s⁻²"], answer:1, explanation:"kg × (m² s⁻²) ÷ m = kg m s⁻², the unit of force." },
  { id:"s2", test:"ESAT", section:"Physics", difficulty:"Stretch", prompt:"A ball is thrown horizontally from a cliff, ignoring air resistance. Which statement is correct?", options:["Its horizontal speed increases", "Its vertical acceleration increases", "Its horizontal acceleration is zero", "Its total acceleration is zero"], answer:2, explanation:"With air resistance ignored, gravity acts vertically. Horizontal velocity is constant and horizontal acceleration is zero." },
  { id:"s3", test:"ESAT", section:"Chemistry", difficulty:"Stretch", prompt:"Which change most directly increases the rate of a reaction without changing the equilibrium position?", options:["Add a catalyst", "Increase temperature", "Increase reactant concentration", "Remove product"], answer:0, explanation:"A catalyst lowers activation energy for both directions and speeds approach to equilibrium without changing its position." },
  { id:"s4", test:"ESAT", section:"Biology", difficulty:"Challenge", prompt:"A membrane is permeable to water but not solute. Side A has a higher solute concentration than side B. What is the initial net movement?", options:["Solute A→B", "Water A→B", "Water B→A", "No net movement"], answer:2, explanation:"Water moves from the side with higher water potential (lower solute concentration, B) to lower water potential (A)." },
  { id:"r1", test:"TARA", section:"Critical thinking", difficulty:"Foundation", prompt:"All members of the debate team enjoy public speaking. Mira enjoys public speaking. What follows?", options:["Mira is on the debate team", "Mira may or may not be on the debate team", "Mira is not on the debate team", "Nobody outside the team enjoys speaking"], answer:1, explanation:"The statement gives team membership as sufficient for enjoyment, not necessary. Affirming the consequent is invalid." },
  { id:"r2", test:"TARA", section:"Problem solving", difficulty:"Stretch", prompt:"A school can fund either 3 microscopes or 5 tablets with the same budget. The opportunity cost of one microscope, measured in tablets, is:", options:["3/5", "1", "5/3", "8"], answer:2, explanation:"Three microscopes trade off against five tablets, so one microscope costs 5/3 tablets." },
  { id:"r3", test:"TARA", section:"Writing task", difficulty:"Challenge", prompt:"Which is the strongest thesis for the prompt ‘Should public decisions prioritise expertise over majority opinion?’", options:["Experts are clever, so yes.", "Majorities are always right in democracies.", "Expertise should guide factual means, while legitimate goals require accountable public judgement.", "There are arguments on both sides and the topic is complex."], answer:2, explanation:"It makes a qualified, contestable distinction and gives the essay a clear structure rather than asserting or sitting on the fence." },
  { id:"lnt1", test:"LNAT", section:"Argument analysis", difficulty:"Foundation", prompt:"An article argues: ‘The library extended its hours and borrowing rose; therefore longer hours caused the rise.’ What is the clearest weakness?", options:["Libraries should never close", "Borrowing cannot be measured", "Another factor may have caused the rise", "The conclusion is too modest"], answer:2, explanation:"The timing shows correlation, but does not exclude publicity, seasonal demand or other causes." },
  { id:"lnt2", test:"LNAT", section:"Inference", difficulty:"Stretch", prompt:"A passage states that a rule is easy to enforce but may penalise harmless conduct. Which conclusion is best supported?", options:["Ease of enforcement settles whether a rule is just", "Enforceability and fairness can pull in different directions", "Harmless conduct must always be lawful", "Rules should contain no exceptions"], answer:1, explanation:"The sentence explicitly sets administrative ease against the risk of unfairness; it does not settle the balance." },
  { id:"u1", test:"UCAT", section:"Decision making", difficulty:"Foundation", prompt:"No ceramic objects in a collection are magnetic. Some blue objects are ceramic. Which conclusion follows?", options:["No blue objects are magnetic", "Some blue objects are not magnetic", "All non-magnetic objects are ceramic", "Some magnetic objects are blue"], answer:1, explanation:"The blue objects that are ceramic must be non-magnetic. Nothing is stated about other blue objects." },
  { id:"u2", test:"UCAT", section:"Quantitative reasoning", difficulty:"Stretch", prompt:"A clinic sees 84 patients in 7 hours at a constant average rate. At that rate, how many patients are seen in 4.5 hours?", options:["48", "52", "54", "60"], answer:2, explanation:"84 ÷ 7 = 12 patients per hour; 12 × 4.5 = 54." },
  { id:"u3", test:"UCAT", section:"Situational judgement", difficulty:"Challenge", prompt:"A student notices confidential patient details visible on an unattended screen during work experience. What is the most appropriate first action?", options:["Photograph it as evidence", "Ignore it", "Close or shield the screen if permitted and alert the responsible staff member", "Post a warning in a group chat"], answer:2, explanation:"Protect confidentiality immediately without copying or sharing the information, then report it through the responsible supervisor." },
]

export const courseTestMap: Record<string, string> = {
  "Oxford Mathematics / Computer Science": "TMUA",
  "Oxford Physics / Engineering / Biomedical Sciences": "ESAT",
  "Oxford PPE / Economics & Management / selected humanities": "TARA",
  "Oxford Medicine": "UCAT",
  "Oxford Law": "LNAT",
  "Cambridge Computer Science / Economics": "TMUA",
  "Cambridge Engineering / Natural Sciences / Chemical Engineering": "ESAT",
  "Cambridge Medicine": "UCAT",
  "Cambridge Law": "LNAT",
  "Cambridge Mathematics": "TMUA at application; STEP is normally part of the offer",
  "Other courses": "Check the official course page: a college assessment may apply",
}
