import type { TrackId } from "@/lib/oxbridge-data"

export type PublishedInterviewItem = {
  id: string
  track: TrackId
  university: "Oxford" | "Cambridge"
  subject: string
  prompt: string
  status: "Exact published wording" | "Adapted from official published example" | "Official mock/example resource"
  sourceTitle: string
  sourceUrl: string
  note: string
  followUps: string[]
}

export const publishedInterviewItems: PublishedInterviewItem[] = [
  {
    id: "ox-bio-lion",
    track: "life",
    university: "Oxford",
    subject: "Biology",
    prompt: "Why do lions have manes?",
    status: "Exact published wording",
    sourceTitle: "Oxford University — Sample interview questions",
    sourceUrl: "https://www.ox.ac.uk/admissions/undergraduate/applying/guide-for-applicants/interviews/sample_questions",
    note: "Oxford states these questions come directly from interview tutors; the tutor commentary says this question has been used in interviews.",
    followUps: ["What competing explanations can you generate?", "How would you test each explanation?", "What observation would make you change your preferred explanation?"],
  },
  {
    id: "ox-psych-eyes",
    track: "life",
    university: "Oxford",
    subject: "Experimental Psychology",
    prompt: "Why do human beings have two eyes?",
    status: "Exact published wording",
    sourceTitle: "Oxford University — Sample interview questions",
    sourceUrl: "https://www.ox.ac.uk/admissions/undergraduate/applying/guide-for-applicants/interviews/sample_questions",
    note: "A publicly released Oxford tutor question used to explore perception, geometry, biology and the ability to connect disciplines.",
    followUps: ["Why can one eye still give some depth information?", "What variables might determine useful eye separation?", "How could you test one of your explanations experimentally?"],
  },
  {
    id: "ox-law-take",
    track: "law",
    university: "Oxford",
    subject: "Law",
    prompt: "What does it mean for someone to ‘take’ another's car?",
    status: "Exact published wording",
    sourceTitle: "Oxford University — Sample interview questions",
    sourceUrl: "https://www.ox.ac.uk/admissions/undergraduate/applying/guide-for-applicants/interviews/sample_questions",
    note: "Oxford publishes this as an example of defining a rule, applying it to edge cases, and revising the definition under challenge.",
    followUps: ["Can something be taken without being moved?", "Which facts should matter to your definition?", "Construct an edge case that breaks your first rule."],
  },
  {
    id: "ox-cs-pirates",
    track: "maths",
    university: "Oxford",
    subject: "Computer Science",
    prompt: "Seven perfectly rational pirates must divide 100 coins under a voting rule. Work backwards from smaller groups to find a stable proposal.",
    status: "Adapted from official published example",
    sourceTitle: "Oxford University — Sample interview questions",
    sourceUrl: "https://www.ox.ac.uk/admissions/undergraduate/applying/guide-for-applicants/interviews/sample_questions",
    note: "Adapted from Oxford's published pirate-logic interview example. The app changes the wording while preserving the backward-reasoning skill.",
    followUps: ["Solve the two-pirate case first.", "Which pirate is cheapest to persuade at each stage?", "Can you generalise the strategy?"],
  },
  {
    id: "ox-atmosphere",
    track: "physical",
    university: "Oxford",
    subject: "Earth Sciences",
    prompt: "Estimate the total mass of Earth's atmosphere using quantities you could plausibly know or estimate.",
    status: "Adapted from official published example",
    sourceTitle: "Oxford University — Sample interview questions",
    sourceUrl: "https://www.ox.ac.uk/admissions/undergraduate/applying/guide-for-applicants/interviews/sample_questions",
    note: "Adapted from Oxford's published Earth Sciences example on estimating atmospheric mass.",
    followUps: ["Which surface measurement already contains information about atmospheric weight?", "How would you estimate Earth's surface area?", "Check the dimensions of your final expression."],
  },
  {
    id: "ox-chem-isomers",
    track: "physical",
    university: "Oxford",
    subject: "Chemistry",
    prompt: "Explore how many distinct structures can be built from six carbon atoms and twelve hydrogen atoms, explaining how you know two drawings are genuinely different.",
    status: "Adapted from official published example",
    sourceTitle: "Oxford University — Sample interview questions",
    sourceUrl: "https://www.ox.ac.uk/admissions/undergraduate/applying/guide-for-applicants/interviews/sample_questions",
    note: "Adapted from Oxford's published Chemistry example on molecular structures and isomerism.",
    followUps: ["What bonding constraints must every structure satisfy?", "Which apparently different drawings are actually equivalent?", "What new forms of isomerism could appear?"],
  },
  {
    id: "ox-biodiversity",
    track: "life",
    university: "Oxford",
    subject: "Biology",
    prompt: "Why might some habitats sustain much greater biodiversity than others?",
    status: "Adapted from official published example",
    sourceTitle: "Oxford University — Sample interview questions",
    sourceUrl: "https://www.ox.ac.uk/admissions/undergraduate/applying/guide-for-applicants/interviews/sample_questions",
    note: "Adapted from an Oxford Biology question that moves from pattern recognition to mechanisms and testable predictions.",
    followUps: ["Separate speciation rate from extinction rate.", "What data could distinguish your explanations?", "Which correlation might be misleading?"],
  },
  {
    id: "ox-econ-pay",
    track: "economics",
    university: "Oxford",
    subject: "Economics and Management",
    prompt: "What economic arguments could justify very high pay in banking, and what arguments might justify government intervention?",
    status: "Adapted from official published example",
    sourceTitle: "Oxford University — Sample interview questions",
    sourceUrl: "https://www.ox.ac.uk/admissions/undergraduate/applying/guide-for-applicants/interviews/sample_questions",
    note: "Adapted from Oxford's published Economics and Management example about pay, labour markets, incentives and equity.",
    followUps: ["What would a competitive labour-market explanation predict?", "What evidence would suggest market power or rents instead?", "Distinguish efficiency arguments from equity arguments."],
  },
  {
    id: "ox-history-witness",
    track: "humanities",
    university: "Oxford",
    subject: "History",
    prompt: "Choose a person from the past you would most want to question. What historical problem would they actually help you solve, and how reliable would their answers be?",
    status: "Adapted from official published example",
    sourceTitle: "Oxford University — Sample interview questions",
    sourceUrl: "https://www.ox.ac.uk/admissions/undergraduate/applying/guide-for-applicants/interviews/sample_questions",
    note: "Adapted from an Oxford History example that tests source choice, evidence limitations and historical method.",
    followUps: ["Would someone less famous be a better witness?", "What might your chosen person be unwilling or unable to tell you?", "What independent evidence would you use to check their account?"],
  },
  {
    id: "ox-language-political",
    track: "languages",
    university: "Oxford",
    subject: "Modern Languages",
    prompt: "When is it useful to describe a novel, play or film as political, and when does that label become too broad to help?",
    status: "Adapted from official published example",
    sourceTitle: "Oxford University — Sample interview questions",
    sourceUrl: "https://www.ox.ac.uk/admissions/undergraduate/applying/guide-for-applicants/interviews/sample_questions",
    note: "Adapted from Oxford's published Modern Languages example about what makes a work political.",
    followUps: ["Is the label about content, form, context or reception?", "Can a work be political against its author's intentions?", "What example would challenge your definition?"],
  },
  {
    id: "cam-downing-linguistics",
    track: "languages",
    university: "Cambridge",
    subject: "Linguistics",
    prompt: "Use the official Cambridge example-interview resource, then practise analysing unfamiliar language data and revising a hypothesis when a counterexample appears.",
    status: "Official mock/example resource",
    sourceTitle: "Downing College Cambridge — Resources for preparing for interview",
    sourceUrl: "https://www.dow.cam.ac.uk/undergraduate-admissions/apply-downing/interviews/resources-preparing-interview",
    note: "Cambridge prohibits sharing real interview questions. This links an officially provided example interview instead.",
    followUps: ["State your first pattern clearly.", "Find evidence that does not fit it.", "Revise the rule as economically as possible."],
  },
  {
    id: "cam-downing-bionatsci",
    track: "life",
    university: "Cambridge",
    subject: "Biological Natural Sciences",
    prompt: "Use the official Cambridge example-interview resource, then practise interpreting unfamiliar biological evidence and proposing a discriminating experiment.",
    status: "Official mock/example resource",
    sourceTitle: "Downing College Cambridge — Resources for preparing for interview",
    sourceUrl: "https://www.dow.cam.ac.uk/undergraduate-admissions/apply-downing/interviews/resources-preparing-interview",
    note: "This is an official example/mock resource, not a disclosed live interview question.",
    followUps: ["Describe the evidence before explaining it.", "Give two mechanisms.", "Design one observation that separates them."],
  },
  {
    id: "cam-sidney-stem",
    track: "physical",
    university: "Cambridge",
    subject: "STEM mock interviews",
    prompt: "Use Cambridge's official mock-interview examples, then practise a supervision-style problem where the interviewer adds information after each answer.",
    status: "Official mock/example resource",
    sourceTitle: "Sidney Sussex College Cambridge — Interview Information",
    sourceUrl: "https://www.sid.cam.ac.uk/apply/undergraduate-study/apply-sidney/cambridge-interview",
    note: "Sidney Sussex publishes mock interview videos to show the style of questions applicants might encounter.",
    followUps: ["Explain the simplest model first.", "Use the new information to revise it.", "Say explicitly why your conclusion changed."],
  },
  {
    id: "cam-christs-cs",
    track: "maths",
    university: "Cambridge",
    subject: "Computer Science",
    prompt: "Use the Cambridge College sample-interview films, then practise decomposing an unfamiliar algorithmic problem aloud while the interviewer changes a constraint.",
    status: "Official mock/example resource",
    sourceTitle: "Christ's College Cambridge — Sample interview films",
    sourceUrl: "https://www.christs.cam.ac.uk/admissions/undergraduate-admissions/how-apply/application-support-uk-students/sample-interview",
    note: "Official College examples illustrate interview style without reproducing confidential live questions.",
    followUps: ["State an invariant or representation.", "What changes when the constraint changes?", "Compare the efficiency of two approaches."],
  },
  {
    id: "cam-sidney-humanities",
    track: "humanities",
    university: "Cambridge",
    subject: "Humanities mock interviews",
    prompt: "Use an official Cambridge mock-interview example, then practise drawing an interpretation from an unseen source while separating observation from inference.",
    status: "Official mock/example resource",
    sourceTitle: "Sidney Sussex College Cambridge — Interview Information",
    sourceUrl: "https://www.sid.cam.ac.uk/apply/undergraduate-study/apply-sidney/cambridge-interview",
    note: "A Cambridge College mock/example resource rather than a recalled admissions question.",
    followUps: ["Which detail is doing most of the evidential work?", "What rival interpretation also fits?", "What extra source would help decide?"],
  },
]

export function publishedForTrack(track: TrackId) {
  return publishedInterviewItems.filter(item => item.track === track)
}
