export type ReadingSection = "Core Ideas" | "Evidence & Data" | "Counterargument" | "Stretch"

export type ReadingRoomItem = {
  id: string
  track: "physical" | "maths" | "life" | "law" | "humanities" | "economics" | "languages"
  section: ReadingSection
  level: "Foundation" | "Developing" | "Challenge"
  title: string
  sourceType: string
  extract: string
  prompts: string[]
  challenge: string
  concepts: string[]
  estimatedMinutes: number
}

export const readingRoomItems: ReadingRoomItem[] = [
  { id:"physical-dark-measurement", track:"physical", section:"Core Ideas", level:"Foundation", title:"When measurement changes the model", sourceType:"Original scientific commentary", extract:"A measurement is often described as revealing a property that was already there. In practice, measurement can alter the system, select which quantity becomes operationally meaningful, and expose assumptions in the model used to interpret the reading. The important question is therefore not only what the instrument showed, but what relationship between instrument, system and model makes that reading evidence for the quantity we claim to have measured.", prompts:["Separate observation from interpretation in the passage.","Give a classical-physics example where the instrument affects the system.","Which claim would you most want to test experimentally?"], challenge:"Suppose the instrument disturbance can be made arbitrarily small. Does the author's argument collapse?", concepts:["measurement","model","evidence","disturbance"], estimatedMinutes:12 },
  { id:"physical-model-selection", track:"physical", section:"Evidence & Data", level:"Developing", title:"When two models fit the same data", sourceType:"Original data commentary", extract:"Two models can agree with every measurement made so far and still disagree about what will happen next. In that situation, collecting more of the same kind of data may add precision without adding discrimination. A powerful experiment is not merely one with a smaller uncertainty; it is one designed so that plausible models make meaningfully different predictions.", prompts:["What is the difference between precision and discrimination?","Give an example of an experiment that separates two models.","Why might more data fail to resolve a theoretical dispute?"], challenge:"If one model has fewer adjustable parameters but both fit the data equally well, should simplicity decide between them?", concepts:["model selection","uncertainty","prediction","experiment design"], estimatedMinutes:14 },
  { id:"physical-scale-laws", track:"physical", section:"Stretch", level:"Challenge", title:"Scaling is not enlargement", sourceType:"Original engineering commentary", extract:"Geometrically similar objects do not remain mechanically similar when their size changes. Length, area and volume scale at different rates, so forces associated with mass can grow faster than the cross-sectional areas available to support them. The difficulty is not a defect in a particular design but a consequence of geometry itself.", prompts:["State how length, area and volume scale with a scale factor k.","Why can a large animal not simply be a scaled-up small animal?","Which assumptions would fail first in a real engineering structure?"], challenge:"Could changing material alone completely restore mechanical similarity at every scale?", concepts:["scaling","dimensional reasoning","stress","similarity"], estimatedMinutes:16 },

  { id:"math-proof-explanation", track:"maths", section:"Core Ideas", level:"Foundation", title:"Proof as explanation", sourceType:"Original mathematical commentary", extract:"A proof can establish that a statement is true without making the truth feel inevitable. Two proofs of the same theorem may therefore differ in mathematical value even when both are valid: one may certify a result, while another reveals the structural reason it could hardly have been otherwise. Proof can therefore function both as verification and as a way of reorganising understanding.", prompts:["What distinction is being made between validity and explanation?","Can one proof be more informative than another while both are correct?","Is inevitability mathematical or psychological?"], challenge:"Could a computer-generated proof be maximally convincing but minimally explanatory?", concepts:["proof","explanation","validity","understanding"], estimatedMinutes:12 },
  { id:"math-data-pattern", track:"maths", section:"Evidence & Data", level:"Developing", title:"Patterns are evidence, not proof", sourceType:"Original mathematical commentary", extract:"A pattern observed in a million cases can be compelling evidence for a conjecture while still failing to establish it. The problem is not that the observations are weak, but that a universal mathematical claim reaches beyond every finite list of examples. Counterexamples therefore have an unusual logical power: one case can destroy a universal claim that millions of supporting cases could not prove.", prompts:["Why can finite checking not prove every universal statement?","Why is one counterexample decisive?","When is computation still mathematically useful?"], challenge:"If a claim has been checked for every integer below 10^20, how should that affect rational confidence even though it is not a proof?", concepts:["conjecture","counterexample","induction","computation"], estimatedMinutes:14 },
  { id:"math-definition-pressure", track:"maths", section:"Stretch", level:"Challenge", title:"Definitions do mathematical work", sourceType:"Original mathematical commentary", extract:"Definitions are sometimes treated as labels attached after the interesting mathematics has been done. In fact, a strong definition can make a theorem possible by separating the properties that matter from those that merely accompany them. Too weak a definition admits counterexamples; too strong a definition hides the structure we hoped to understand.", prompts:["What makes a definition mathematically useful?","Give an example where changing a definition changes a theorem.","How would you test whether a definition is too strong?"], challenge:"Can two different definitions capture the same concept equally well, or must one eventually be preferred?", concepts:["definition","generality","counterexample","structure"], estimatedMinutes:16 },

  { id:"life-correlation", track:"life", section:"Core Ideas", level:"Foundation", title:"Mechanism and biological evidence", sourceType:"Original biological commentary", extract:"Biology often advances by moving between levels of explanation. A population-level association may suggest a cellular mechanism, while a molecular pathway may fail to predict an organism-level outcome because feedback, compensation and environment intervene. Evidence becomes strongest when explanations survive movement between scales rather than working at only one level.", prompts:["What does movement between scales mean here?","Give an example where a molecular explanation could fail at organism level.","What evidence would strengthen a proposed mechanism?"], challenge:"If a molecular intervention reliably changes the organism-level outcome, is the mechanism thereby established?", concepts:["mechanism","scale","feedback","causation"], estimatedMinutes:12 },
  { id:"life-confounding", track:"life", section:"Evidence & Data", level:"Developing", title:"Association under confounding", sourceType:"Original epidemiological commentary", extract:"An observational study finds that people who report a particular behaviour have lower disease incidence. Even a large sample cannot by itself reveal whether the behaviour caused the difference. The groups may differ in age, income, prior health, environment or other behaviours. Size can reduce random error while leaving systematic bias untouched.", prompts:["Distinguish random error from confounding.","Which variables would you measure before making a causal claim?","What study design would strengthen the evidence?"], challenge:"If ten independent observational studies find the same association, what uncertainty still remains?", concepts:["confounding","causation","observational evidence","bias"], estimatedMinutes:14 },
  { id:"life-adaptation-tradeoff", track:"life", section:"Stretch", level:"Challenge", title:"Adaptation without perfection", sourceType:"Original evolutionary commentary", extract:"Calling a biological trait an adaptation does not imply that it is optimal. Evolution works with inherited constraints, competing functions and environments that change faster than genomes. A trait may persist because it is good enough relative to alternatives, because improving one function would damage another, or because selection has not had access to a feasible path toward the apparent optimum.", prompts:["Why does adaptation not imply perfection?","Give a biological example of a trade-off.","What evidence could distinguish current adaptation from historical constraint?"], challenge:"If engineers can design a better structure than evolution produced, does that count against evolutionary explanation?", concepts:["adaptation","trade-offs","constraint","selection"], estimatedMinutes:16 },

  { id:"law-rules-reasons", track:"law", section:"Core Ideas", level:"Foundation", title:"Rules and reasons", sourceType:"Original legal commentary", extract:"A legal rule gains predictability by compressing many reasons into a general form. Yet hard cases arise precisely where the compressed rule no longer tracks the reason that justified it. A legal system must then choose between fidelity to the rule's wording and fidelity to the principle that made the rule worth having.", prompts:["What does compressing reasons mean here?","Why can hard cases create tension between wording and purpose?","Which approach gives greater predictability?"], challenge:"If judges can always appeal to underlying principle, does the rule cease to constrain them?", concepts:["rules","principles","interpretation","predictability"], estimatedMinutes:12 },
  { id:"law-evidence-standard", track:"law", section:"Evidence & Data", level:"Developing", title:"Standards of proof and error", sourceType:"Original legal reasoning commentary", extract:"A legal standard of proof does more than describe how confident a decision-maker should feel. It also distributes the cost of error. Requiring stronger evidence before conviction reduces one kind of mistake while making another more likely. The standard therefore embeds a judgement about which errors the legal system regards as more serious.", prompts:["What two kinds of error are being traded off?","Why is a standard of proof partly normative rather than purely statistical?","How might the appropriate standard differ between legal contexts?"], challenge:"Could a perfectly accurate statistical model eliminate the need for standards of proof?", concepts:["burden of proof","error","evidence","legal values"], estimatedMinutes:14 },
  { id:"law-precedent-change", track:"law", section:"Counterargument", level:"Challenge", title:"When precedent should move", sourceType:"Original legal commentary", extract:"Precedent creates stability by making current decisions answerable to earlier ones. But stability is not the same as correctness. If an earlier rule rests on assumptions society no longer accepts, following it may preserve consistency at the cost of justice. Yet allowing every court to revise precedent whenever it sees a better argument would weaken the very predictability precedent supplies.", prompts:["State the strongest case for strict precedent.","State the strongest case for overruling it.","What criteria could limit when departure is justified?"], challenge:"Is consistency itself a form of justice, even when the underlying rule is imperfect?", concepts:["precedent","stability","change","judicial reasoning"], estimatedMinutes:16 },

  { id:"humanities-silence", track:"humanities", section:"Core Ideas", level:"Foundation", title:"The evidence of silence", sourceType:"Original historical commentary", extract:"Silence in the archive is ambiguous. It may indicate that something did not occur, that it was considered too ordinary to record, that the relevant voices lacked access to record-making institutions, or simply that records were lost. The historian's task is therefore not to treat absence as empty space, but to ask what kinds of traces the event should have produced if it had occurred.", prompts:["List the alternative explanations for archival silence.","When could silence become strong evidence?","How does institutional power affect what survives?"], challenge:"Suppose an institution was famous for meticulous record-keeping. How much stronger does absence become as evidence?", concepts:["archives","absence","power","inference"], estimatedMinutes:12 },
  { id:"humanities-source-bias", track:"humanities", section:"Evidence & Data", level:"Developing", title:"Biased sources can still be evidence", sourceType:"Original historical commentary", extract:"A partisan source may be unreliable as a neutral account of events while remaining highly informative about the beliefs, fears and strategies of the writer. Source criticism therefore asks not simply whether a document is biased, but what kind of claim it can legitimately support. Bias changes the evidential question; it does not automatically destroy evidential value.", prompts:["Distinguish using a source for events from using it for attitudes.","What questions would you ask about audience and purpose?","Can a neutral source also be misleading?"], challenge:"If every surviving source is partisan, can a historian still make justified claims about what happened?", concepts:["source criticism","bias","audience","inference"], estimatedMinutes:14 },
  { id:"humanities-causal-story", track:"humanities", section:"Counterargument", level:"Challenge", title:"The danger of a single cause", sourceType:"Original historical commentary", extract:"Historical explanations become attractive when they reduce complexity to one decisive cause. Yet the same event may require structural conditions, immediate triggers and choices by individuals. Removing one factor in imagination can reveal dependence, but counterfactual reasoning is difficult because changing one condition may alter many others at the same time.", prompts:["Separate background condition from trigger.","What makes a historical counterfactual useful?","Why can monocausal explanations be seductive?"], challenge:"If an event would probably have occurred eventually without a particular trigger, how important was that trigger?", concepts:["causation","counterfactuals","structure","agency"], estimatedMinutes:16 },

  { id:"economics-average", track:"economics", section:"Core Ideas", level:"Foundation", title:"Averages and hidden structure", sourceType:"Original economic commentary", extract:"An average is a compression of a distribution. That compression can be useful precisely because it discards detail, but it can also mislead when the discarded structure matters to the question being asked. A rise in average income may describe genuine improvement while simultaneously concealing stagnation for a majority if gains are concentrated strongly enough.", prompts:["What information does a mean discard?","How could the average rise if most people see no change?","Which additional statistics would you request?"], challenge:"If both mean and median rise, what important distributional information could still be hidden?", concepts:["mean","median","distribution","inequality"], estimatedMinutes:12 },
  { id:"economics-policy-identification", track:"economics", section:"Evidence & Data", level:"Developing", title:"Policy outcomes without a counterfactual", sourceType:"Original economic commentary", extract:"After a policy is introduced, an outcome improves. That fact alone does not tell us whether the policy caused the improvement, because we do not observe what would have happened in the same place at the same time without the policy. Causal inference therefore depends on constructing a credible comparison, not merely recording before-and-after change.", prompts:["What is the missing counterfactual?","Why can a neighbouring region be a poor comparison?","What evidence would make a comparison more credible?"], challenge:"If the policy was introduced everywhere at once, what strategies remain for estimating its effect?", concepts:["counterfactual","causal inference","policy","comparison"], estimatedMinutes:14 },
  { id:"economics-incentives-values", track:"economics", section:"Counterargument", level:"Challenge", title:"Efficiency is not the whole argument", sourceType:"Original economic commentary", extract:"A policy can increase total economic surplus while leaving some groups worse off. Calling the policy efficient therefore does not by itself settle whether it is desirable. One can separate the positive question of what the policy changes from the normative question of how those gains and losses should be valued or redistributed.", prompts:["Distinguish positive from normative claims.","Why can efficiency and fairness conflict?","When can compensation make an efficiency argument stronger?"], challenge:"If the winners could compensate the losers but never actually do, should potential compensation matter?", concepts:["efficiency","distribution","normative reasoning","compensation"], estimatedMinutes:16 },

  { id:"languages-translation", track:"languages", section:"Core Ideas", level:"Foundation", title:"Translation as interpretation", sourceType:"Original literary commentary", extract:"Translation does not begin after interpretation; it is already an act of interpretation. Choosing whether to preserve rhythm, ambiguity, register or literal syntax forces the translator to decide which features of the original are carrying the greatest weight. A translation therefore offers not a neutral copy but an argued reading in another language.", prompts:["Why does the author reject the idea of a neutral translation?","Which features might be impossible to preserve simultaneously?","Can two very different translations both be faithful?"], challenge:"Would machine translation weaken the claim that translation is necessarily interpretive?", concepts:["translation","interpretation","register","form"], estimatedMinutes:12 },
  { id:"languages-voice-evidence", track:"languages", section:"Evidence & Data", level:"Developing", title:"What counts as evidence in a text?", sourceType:"Original literary commentary", extract:"Literary interpretation often depends on details too small to look like evidence when isolated: a repeated verb, a shift in pronoun, a change in rhythm, an unexpected image. The challenge is to show that these features constrain interpretation rather than merely decorate it. A persuasive reading therefore links local textual choices to a larger claim without pretending that the text permits only one possible meaning.", prompts:["What makes a textual detail evidential rather than decorative?","How can an interpretation be constrained without being unique?","Give an example of a small linguistic feature carrying a large effect."], challenge:"If two interpretations explain all the same textual details equally well, how should a critic choose between them?", concepts:["close reading","evidence","ambiguity","interpretation"], estimatedMinutes:14 },
  { id:"languages-form-content", track:"languages", section:"Stretch", level:"Challenge", title:"When form argues", sourceType:"Original literary commentary", extract:"A text can make an argument not only through what it states but through how it organises attention. Repetition can normalise an idea, interruption can make certainty unstable, and an unreliable voice can force the reader to perform judgement rather than receive it. Form is therefore not a container for meaning; it can be one of the mechanisms by which meaning is produced.", prompts:["Give one example of form changing interpretation.","How can a narrator's unreliability create rather than remove meaning?","What evidence would show that a formal feature is deliberate rather than accidental?"], challenge:"Can a reader reasonably infer an effect from form even if the author did not consciously intend it?", concepts:["form","voice","reader","intention"], estimatedMinutes:16 },
]

export const readingSections: ReadingSection[] = ["Core Ideas", "Evidence & Data", "Counterargument", "Stretch"]

export function readingFor(track: string, section?: ReadingSection) {
  return readingRoomItems.filter(item => item.track === track && (!section || item.section === section))
}
