import type { InterviewQuestion, TrackId } from "@/lib/oxbridge-data"

export const realisticInterviewQuestions: InterviewQuestion[] = [
  {
    id: "rx-maths-1", track: "maths", title: "A function that folds back", difficulty: "Foundation", time: 8,
    prompt: "Consider f(x) = x + 1/x for positive x. Without using calculus at first, what can you say about the smallest value f(x) can take? Talk me through how you know, not just the answer.",
    probes: [
      "Try x = 1, x = 2 and x = 1/2. What symmetry do you notice?",
      "Can you turn that observation into an inequality rather than relying on examples?",
      "Now suppose x is allowed to be negative as well. Which parts of your argument survive?",
      "If I replace 1/x by 4/x, what would you predict before calculating?",
    ],
    concepts: ["reciprocal", "inequality", "minimum", "symmetry", "positive", "generalise"],
    strongAnswer: "For x>0, x+1/x is at least 2, with equality at x=1. One route is (x-1)^2>=0, giving x^2+1>=2x and hence x+1/x>=2. The reciprocal symmetry x and 1/x also helps locate the minimum. Extending to negative x changes the range and needs separate analysis rather than blindly reusing the positive-domain inequality step.",
  },
  {
    id: "rx-maths-2", track: "maths", title: "Lights around a circle", difficulty: "Stretch", time: 9,
    prompt: "Six lights are arranged in a circle, all initially off. Pressing one switch changes that light and its two neighbours. Can you leave exactly one light on? You may sketch the circle; tell me what your experiments suggest before trying to prove it.",
    probes: [
      "Try pressing two different switches. Which features of the lit pattern change in the same way each time?",
      "Pair each light with the one opposite it. What happens to the parity of each pair after a press?",
      "Starting from all off, can the three opposite-pair parities ever differ? What would one lit light require?",
      "Two opposite lights on passes that parity check. Does passing a necessary check prove reachability, or can you find actual presses?",
    ],
    concepts: ["invariant", "opposite pairs", "parity", "binary", "state", "proof"],
    strongAnswer: "It is impossible to leave exactly one light on. Number the circle 1 to 6 and track the parity of opposite pairs (1,4), (2,5) and (3,6). Any press toggles exactly one light in each pair, so all three pair parities change together. They start equal and must stay equal; a single lit light would make one parity odd and the other two even. This is a necessary condition, not a complete test for every target. For instance two opposite lights are reachable by pressing switches 2 and 3.",
  },
  {
    id: "rx-maths-3", track: "maths", title: "Three envelopes", difficulty: "Stretch", time: 8,
    stimulus: "Three envelopes contain £10, £20 and £40. You choose one at random. Before opening it, you may pay £3 to switch to one of the other two envelopes, also chosen at random.",
    prompt: "Should you ever pay to switch? Give me a decision rule and be explicit about what information you do and do not have.",
    probes: [
      "What is the expected value before you choose anything?",
      "Does the fact that you have already selected an envelope change the distribution of values in the others?",
      "Now I let you peek and learn only that your envelope is not £40. Does your decision change?",
      "What if the switching fee is unknown: can you derive a threshold fee?",
    ],
    concepts: ["expected value", "conditional", "probability", "information", "threshold", "decision"],
    strongAnswer: "Without opening the chosen envelope, keeping and switching to a random other envelope each have expected value £70/3, so paying £3 to switch loses £3 in expectation. Learning only that the chosen envelope is not £40 leaves £10 and £20 equally likely: keeping is worth £15, while a random other envelope is worth £27.50 before the fee. The gain from switching is £12.50 before fees; pay only if the fee is below £12.50. The decision changes because of information, not because merely choosing an envelope changes its value.",
  },
  {
    id: "rx-maths-4", track: "maths", title: "A proof that looks plausible", difficulty: "Challenge", time: 9,
    prompt: "A student claims: ‘Every polynomial with integer coefficients that takes an even value at x=0 and an odd value at x=1 must have an integer root somewhere.’ Do you believe the claim? Do not rush to calculate; decide what kind of evidence would settle it.",
    probes: [
      "What does the parity change establish about the values at 0 and 1? Does it establish their signs?",
      "Try a quadratic that stays positive for every real x. Can it meet both parity conditions?",
      "What are the values at 0 and 1 of x² + 2x + 2, and can that polynomial have any real root?",
      "What stronger condition at 0 and 1 would let continuity guarantee a real root between them? Would it guarantee an integer root?",
    ],
    concepts: ["counterexample", "polynomial", "integer", "continuity", "root", "parity"],
    strongAnswer: "The claim is false: p(x)=x²+2x+2 has p(0)=2 (even) and p(1)=5 (odd), but p(x)=(x+1)²+1 is positive for every real x and so has no integer root. Parity change says nothing about a sign change. Opposite signs at 0 and 1 would guarantee a real root in (0,1) by continuity, but still would not give an integer root.",
  },

  {
    id: "rx-physical-1", track: "physical", title: "A falling coffee filter", difficulty: "Foundation", time: 8,
    prompt: "A paper coffee filter is dropped from rest and soon seems to fall at nearly constant speed. Sketch the speed-time graph you expect and explain what determines its shape.",
    probes: [
      "What forces act immediately after release, and what changes as speed increases?",
      "I place a second identical filter inside the first. Predict the new graph before giving me any equations.",
      "If the drag force were proportional to speed squared, which qualitative features would stay the same?",
      "How would you use video data to distinguish between two drag models?",
    ],
    concepts: ["drag", "weight", "terminal speed", "acceleration", "model", "graph"],
    strongAnswer: "Initially weight dominates so the filter accelerates. Drag increases with speed, reducing the resultant force until drag balances weight and acceleration tends to zero at terminal speed. Adding mass while keeping a similar area raises the terminal speed. A model can be tested by extracting speed and acceleration from video and checking which drag-speed relation fits the data.",
  },
  {
    id: "rx-physical-2", track: "physical", title: "Warm metal, cold metal", difficulty: "Stretch", time: 8,
    stimulus: "A metal block and a wooden block have both been left in the same room overnight. The metal feels colder to the touch.",
    prompt: "What, exactly, can you infer from the sensation? Build a physical explanation and then tell me how you would test it.",
    probes: [
      "Are the two blocks necessarily at different temperatures before you touch them?",
      "Which material properties matter during the first few seconds of contact?",
      "Suppose I replace the wood with a dense ceramic. What prediction would your model make?",
      "Design one measurement that would separate temperature from heat-transfer rate.",
    ],
    concepts: ["temperature", "thermal conductivity", "heat transfer", "energy", "rate", "experiment"],
    strongAnswer: "The sensation mainly indicates a faster rate of energy transfer from the hand, not necessarily a lower initial temperature. Metal typically has higher thermal conductivity and effusivity, maintaining a larger heat flux at the skin. A direct temperature measurement before contact and a surface-temperature or heat-flux measurement during contact would test the explanation.",
  },
  {
    id: "rx-physical-3", track: "physical", title: "A bridge that starts to move", difficulty: "Stretch", time: 9,
    prompt: "People walk across a lightweight footbridge and a small sideways oscillation begins. The pedestrians are not deliberately marching in step. How could the motion grow rather than die away? Start with the simplest model you can.",
    probes: [
      "Where could energy enter the oscillation?",
      "How might a pedestrian change their gait in response to the bridge moving beneath them?",
      "What observation would distinguish resonance from a feedback mechanism?",
      "You are allowed one design change. Would you alter stiffness, damping or mass first, and why?",
    ],
    concepts: ["oscillation", "resonance", "feedback", "damping", "energy", "frequency"],
    strongAnswer: "A candidate should identify that growing motion needs net energy input. Simple resonance is one possibility, but pedestrian synchronisation can create feedback: bridge motion alters gait, changing lateral forcing in a way that reinforces the motion. Measurements of phase, forcing frequency and response would distinguish mechanisms. Design choices depend on which mechanism dominates.",
  },
  {
    id: "rx-physical-4", track: "physical", title: "A battery that recovers", difficulty: "Challenge", time: 9,
    stimulus: "A battery-powered device switches itself off under heavy load. After a minute with the load removed, the same battery can power the device again for a short time.",
    prompt: "Give me two physically different explanations for this behaviour. Then design a measurement that could distinguish them.",
    probes: [
      "What would internal resistance do to the terminal voltage during a large current draw?",
      "Could chemistry or temperature produce a similar observation?",
      "What would you expect the open-circuit voltage to do during the minute of rest?",
      "If you had only a voltmeter and a known resistor, what could you measure?",
    ],
    concepts: ["internal resistance", "terminal voltage", "current", "temperature", "chemistry", "measurement"],
    strongAnswer: "One explanation is voltage sag from internal resistance under high current, followed by recovery when current falls. Another is slower electrochemical or concentration-polarisation recovery, possibly temperature-dependent. Measuring loaded and open-circuit voltage versus time and estimating internal resistance with a known load can discriminate between mechanisms.",
  },

  {
    id: "rx-life-1", track: "life", title: "Leaves with holes", difficulty: "Foundation", time: 8,
    stimulus: "Two plants of the same species grow beside one another. One has many small holes in its leaves; the other has almost none. Both are equally tall.",
    prompt: "Give me several biological explanations before choosing one. What observations would help you decide between them?",
    probes: [
      "How would you separate herbivory from disease or physical damage?",
      "Could the difference be caused by the plants rather than by the environment around them?",
      "What would you measure if you suspected chemical defence?",
      "Suppose the damaged plant later produces more seeds. How would that affect your interpretation?",
    ],
    concepts: ["hypothesis", "herbivory", "defence", "variation", "evidence", "fitness"],
    strongAnswer: "A strong response generates alternatives rather than settling immediately: herbivory, pathogens, mechanical damage, microhabitat or genetic/physiological differences. It then proposes discriminating observations or experiments and recognises that visible damage need not map directly onto reproductive fitness.",
  },
  {
    id: "rx-life-2", track: "life", title: "The antibiotic graph", difficulty: "Stretch", time: 9,
    stimulus: "In a bacterial culture, cell number rises for four hours, stays roughly constant for two hours after an antibiotic is added, then begins rising again despite no further treatment.",
    prompt: "Talk me through explanations for the flat region and the later regrowth. Which explanation would you test first, and why?",
    probes: [
      "Does regrowth necessarily mean a genetic resistance mutation occurred during the experiment?",
      "How could dormant or tolerant cells produce a similar pattern?",
      "What would sequencing before and after treatment tell you, and what would it not tell you?",
      "How would your interpretation change if regrowth disappeared when the experiment was repeated from a single clone?",
    ],
    concepts: ["resistance", "selection", "mutation", "tolerance", "population", "experiment"],
    strongAnswer: "The plateau may reflect growth inhibition or killing balanced by survivors. Regrowth could result from pre-existing resistant variants, new mutations, phenotypic tolerance/persistence, or antibiotic degradation. A good candidate proposes tests that distinguish genetic and non-genetic explanations rather than equating regrowth automatically with mutation.",
  },
  {
    id: "rx-life-3", track: "life", title: "A heart-rate study", difficulty: "Stretch", time: 8,
    stimulus: "A study finds that teenagers who sleep fewer than six hours have a higher average resting heart rate than teenagers who sleep eight hours or more.",
    prompt: "What can the study legitimately conclude? Build the strongest causal explanation you can, then try to undermine it.",
    probes: [
      "Name three plausible confounders.",
      "Would adjusting statistically for caffeine solve the problem?",
      "What experiment would be informative but still ethically acceptable?",
      "Suppose the association disappears at weekends. What new hypothesis does that suggest?",
    ],
    concepts: ["correlation", "causation", "confounder", "study", "mechanism", "ethics"],
    strongAnswer: "The observational association alone does not establish that short sleep causes higher resting heart rate. Plausible mechanisms can be proposed, but confounding and reverse causation remain. Better evidence could come from repeated within-person measurements or a carefully designed sleep intervention with appropriate safeguards.",
  },
  {
    id: "rx-life-4", track: "life", title: "Why keep a costly trait?", difficulty: "Challenge", time: 9,
    prompt: "Imagine a bird species in which males with longer tail feathers escape predators less successfully, yet average tail length increases over many generations. How could natural selection allow that?",
    probes: [
      "Can a trait reduce survival and still increase total reproductive success?",
      "What data would distinguish mate choice from a genetic correlation with another advantageous trait?",
      "Suppose females raised without adult males show the same preference. What does that add?",
      "Could the system run away indefinitely? What might stop it?",
    ],
    concepts: ["selection", "sexual selection", "fitness", "trade-off", "inheritance", "evolution"],
    strongAnswer: "Selection acts on total reproductive success, not survival alone. A survival cost can be outweighed by mating advantage. Strong answers distinguish mechanisms such as direct mate preference, honest signalling or genetic correlation, propose evidence to separate them, and recognise constraints that prevent unlimited exaggeration.",
  },

  {
    id: "rx-law-1", track: "law", title: "The library rule", difficulty: "Foundation", time: 8,
    stimulus: "A university library rule says: ‘No electronic devices may make sounds in reading rooms.’ A student's medical glucose monitor sounds an urgent low-glucose alarm.",
    prompt: "Has the student broken the rule? Give me the strongest argument on each side before you settle on a provisional interpretation.",
    probes: [
      "Does it matter whether the rule contains an explicit exception?",
      "What purpose do you think the rule serves, and how much weight should that purpose carry?",
      "Now replace the medical alarm with a fire alarm built into a phone. Same answer?",
      "Draft one sentence that improves the rule without making it impossibly long.",
    ],
    concepts: ["literal", "purpose", "exception", "necessity", "interpretation", "rule"],
    strongAnswer: "The literal wording catches the alarm, but a purposive reading may imply exceptions where sound protects health or safety and does not represent the mischief targeted by the rule. A strong answer distinguishes interpretation from policy preference and tests any proposed exception against harder cases.",
  },
  {
    id: "rx-law-2", track: "law", title: "A promise made in anger", difficulty: "Stretch", time: 9,
    stimulus: "During an argument, A tells B: ‘If you leave now, I will pay your rent for the next three months.’ B leaves, signs a new tenancy, and later asks A to pay.",
    prompt: "Without relying on legal doctrine you may have memorised, construct a principled rule for deciding whether A should be legally bound.",
    probes: [
      "Which facts make reliance more or less reasonable?",
      "Should A's emotional state matter? If so, how could a court assess it?",
      "Suppose B had already planned to leave before the promise. What changes?",
      "Can your rule avoid both unfair surprise and opportunistic claims?",
    ],
    concepts: ["reliance", "intention", "reasonable", "evidence", "detriment", "rule"],
    strongAnswer: "A strong candidate constructs a rule using clarity of assurance, reasonable and foreseeable reliance, causation of detriment and evidence of seriousness, then stress-tests it. The key is not reciting contract doctrine but reasoning consistently across changed facts.",
  },
  {
    id: "rx-law-3", track: "law", title: "The protest barrier", difficulty: "Stretch", time: 9,
    stimulus: "A city permits demonstrations in a central square but requires barriers whenever organisers expect more than 500 people. A spontaneous protest grows from 100 to 2,000 people within an hour.",
    prompt: "Who, if anyone, should bear responsibility for the missing barriers? Start by identifying what a fair rule would need to accomplish.",
    probes: [
      "Could responsibility turn on what organisers reasonably foresaw rather than what actually happened?",
      "What if police observed the crowd growing but did nothing?",
      "Would strict liability make the rule easier to enforce but less fair?",
      "Give me a counterexample that exposes a weakness in your preferred rule.",
    ],
    concepts: ["responsibility", "foreseeability", "fairness", "strict liability", "duty", "counterexample"],
    strongAnswer: "The candidate should distinguish outcome from foreseeability, compare organiser and public-authority responsibility, and develop a rule that handles spontaneous events. Strong performance includes testing the rule against a hard counterexample and refining it rather than defending the first formulation at all costs.",
  },
  {
    id: "rx-law-4", track: "law", title: "Truth that misleads", difficulty: "Challenge", time: 9,
    prompt: "Can a person deceive someone while saying only things that are literally true? Give me a definition of deception, then try to break your own definition.",
    probes: [
      "Does deception require an intention to create a false belief?",
      "What if the speaker knows the listener will draw a false inference but says nothing false?",
      "Can silence deceive?",
      "Now distinguish deception from mistake and from withholding information.",
    ],
    concepts: ["deception", "intention", "truth", "inference", "omission", "definition"],
    strongAnswer: "A strong answer builds distinctions between falsity, intention, belief and inference. Literal truth can be used deceptively if selected or framed to induce a false belief, but the role of intention and omission needs careful treatment. The candidate should revise the definition when counterexamples expose over- or under-inclusion.",
  },

  {
    id: "rx-humanities-1", track: "humanities", title: "The silent diary", difficulty: "Foundation", time: 8,
    stimulus: "A factory owner's diary records wages, machinery and deliveries almost daily for 15 years, but never mentions accidents. A later newspaper campaign claims serious accidents were common at the factory.",
    prompt: "What can the diary's silence tell a historian, if anything? I want you to separate possibilities before drawing a conclusion.",
    probes: [
      "What would you need to know about what this diarist usually recorded?",
      "Could silence itself be strategic evidence?",
      "What other source types would you seek, and what biases might they introduce?",
      "Suppose one accident is described in extraordinary detail. How would that change the value of the earlier silence?",
    ],
    concepts: ["source", "silence", "provenance", "corroboration", "bias", "inference"],
    strongAnswer: "Silence is not automatically evidence of absence. Its value depends on recording habits, purpose, audience and whether accidents would normally have been noted. A strong candidate uses the silence as one piece of evidence and seeks independent corroboration rather than choosing a source to trust wholesale.",
  },
  {
    id: "rx-humanities-2", track: "humanities", title: "Did the railway cause growth?", difficulty: "Stretch", time: 9,
    stimulus: "Between 1850 and 1880, towns connected to a new railway grew faster on average than nearby towns without a station.",
    prompt: "Build the strongest argument that the railway caused growth, then tell me what would make you doubt it.",
    probes: [
      "Could railway companies have chosen towns that were already likely to grow?",
      "What comparison group would be more convincing than ‘towns without a station’?",
      "What evidence about timing would matter?",
      "If some connected towns shrank, does that destroy the causal claim?",
    ],
    concepts: ["causation", "selection", "comparison", "evidence", "timing", "counterfactual"],
    strongAnswer: "Correlation is consistent with a railway effect but also with selection into railway connection. Strong reasoning asks what the relevant counterfactual is, examines pre-trends and timing, and treats exceptions as evidence to interpret rather than automatic refutation.",
  },
  {
    id: "rx-humanities-3", track: "humanities", title: "When is a border natural?", difficulty: "Stretch", time: 9,
    prompt: "People sometimes describe rivers or mountains as ‘natural borders’. Is that a geographical fact, a political claim, or both? Define what ‘natural’ is doing in the phrase before you answer.",
    probes: [
      "A river changes course. Has the natural border moved?",
      "Could the same mountain range unite communities rather than divide them?",
      "What evidence would show that physical geography materially constrained a political boundary?",
      "Does calling a border natural make it seem more legitimate?",
    ],
    concepts: ["border", "natural", "political", "geography", "legitimacy", "definition"],
    strongAnswer: "Physical features can constrain movement and influence boundary-making, but ‘natural border’ is also interpretive and political. A strong candidate distinguishes material geography from the social decision to treat a feature as a boundary and notices the legitimating effect of the language.",
  },
  {
    id: "rx-humanities-4", track: "humanities", title: "Freedom under a curfew", difficulty: "Challenge", time: 9,
    prompt: "A city introduces a night-time curfew and violent street crime falls sharply. Has the population become more free or less free? You must define freedom before using the evidence.",
    probes: [
      "Can restricting one liberty increase another form of freedom?",
      "Who gains and who loses from the policy?",
      "Would your answer differ if compliance were voluntary rather than legally enforced?",
      "Can empirical evidence settle the disagreement, or is part of it conceptual?",
    ],
    concepts: ["freedom", "liberty", "security", "trade-off", "definition", "evidence"],
    strongAnswer: "The answer depends on the conception of freedom: non-interference, effective capability, security from coercion, or a plural account. Crime data can inform consequences but cannot by itself choose the normative weighting. Strong answers define terms, identify distributional effects and keep empirical and conceptual claims distinct.",
  },

  {
    id: "rx-econ-1", track: "economics", title: "A cheaper train ticket", difficulty: "Foundation", time: 8,
    stimulus: "A train company cuts off-peak fares by 20%. Passenger journeys rise by 12%, but total ticket revenue falls.",
    prompt: "What can you infer from those figures, and what can you not infer? Explain the mechanism rather than just naming elasticity.",
    probes: [
      "Can you estimate the direction of the price elasticity from these numbers?",
      "Why might revenue fall even though more journeys are sold?",
      "Suppose on-peak fares were unchanged. What substitution effect might complicate your conclusion?",
      "Would a profit-maximising company necessarily reverse the price cut?",
    ],
    concepts: ["elasticity", "revenue", "demand", "substitution", "cost", "profit"],
    strongAnswer: "Quantity rises less proportionally than price falls, so demand appears relatively inelastic over the observed range and revenue can fall. Profit cannot be inferred without costs, and substitution from peak travel or other modes complicates causal interpretation.",
  },
  {
    id: "rx-econ-2", track: "economics", title: "The crowded free bus", difficulty: "Stretch", time: 9,
    stimulus: "A city makes buses free. Bus journeys rise 35%, car journeys fall 4%, walking falls 12%, and average bus waiting time increases.",
    prompt: "Is the policy working? Give me a model of the intended mechanism, then use the data to challenge it.",
    probes: [
      "Which new bus journeys appear to come from the behaviour the policy was meant to change?",
      "Who bears the cost of crowding and longer waits?",
      "What additional data would you need before making a welfare judgement?",
      "Suppose lower-income residents make most of the extra bus journeys. Does that alter your evaluation?",
    ],
    concepts: ["substitution", "externality", "welfare", "crowding", "equity", "opportunity cost"],
    strongAnswer: "The data suggest substantial induced demand and some substitution from walking, with only a modest fall in car use. Whether the policy works depends on its aims and welfare effects, including distribution, operating costs, congestion and emissions. A strong answer does not treat ridership growth itself as success.",
  },
  {
    id: "rx-econ-3", track: "economics", title: "A tax that raises sales", difficulty: "Stretch", time: 9,
    stimulus: "A small tax is introduced on a product. In the following month, the product's sales are higher than before the tax.",
    prompt: "Does this observation contradict the law of demand? Give me at least three ways the data could arise before choosing an explanation.",
    probes: [
      "What does the law of demand hold constant?",
      "Could expectations before a larger future tax matter?",
      "How would seasonality or advertising alter the interpretation?",
      "What empirical comparison would make the tax effect easier to identify?",
    ],
    concepts: ["demand", "ceteris paribus", "confounder", "expectations", "causation", "data"],
    strongAnswer: "A before-after rise in sales does not by itself contradict a ceteris-paribus demand relationship. Other determinants of demand may have shifted, expectations may have changed, or the comparison may be confounded. A stronger design uses an appropriate control or exploits variation in exposure to the tax.",
  },
  {
    id: "rx-econ-4", track: "economics", title: "The auction bidder", difficulty: "Challenge", time: 9,
    prompt: "Two people value an object at £100 each. They bid in a sealed-bid auction where the highest bidder wins and pays their own bid. Should either person bid £100? Build your reasoning from incentives rather than from a memorised auction rule.",
    probes: [
      "What happens to the winner's surplus if they bid exactly their value?",
      "Could bidding less create a profitable trade-off between winning and paying?",
      "Now suppose each bidder is uncertain about the other's value. What new problem appears?",
      "How would your strategy differ if the winner paid the second-highest bid instead?",
    ],
    concepts: ["incentive", "auction", "surplus", "strategy", "uncertainty", "equilibrium"],
    strongAnswer: "Bidding one's full value in a first-price auction leaves zero surplus if one wins and may not be optimal; shading the bid trades off price against winning probability. Uncertainty about the opponent matters. Changing to a second-price mechanism changes incentives because the winner's own bid no longer directly sets the price paid.",
  },

  {
    id: "rx-lang-1", track: "languages", title: "An unchanged room", difficulty: "Foundation", time: 8,
    stimulus: "‘Nothing had changed,’ she said, stepping over the pale rectangle where the rug used to be.",
    prompt: "Start with what you notice in this single sentence. What possibilities does it open up about the speaker and the situation?",
    probes: [
      "What is the effect of placing the claim before the visual contradiction?",
      "Does the sentence prove that the speaker is lying?",
      "What difference would first-person narration make?",
      "Give me one alternative reading that preserves the speaker's reliability.",
    ],
    concepts: ["narrator", "contradiction", "irony", "syntax", "reliability", "interpretation"],
    strongAnswer: "The sentence creates tension between assertion and detail. That can suggest denial, self-deception, irony or a narrower meaning of ‘changed’. A strong answer notices order and wording, separates speaker from author, and offers an alternative reading rather than declaring unreliability as a fact.",
  },
  {
    id: "rx-lang-2", track: "languages", title: "Two translations", difficulty: "Stretch", time: 9,
    stimulus: "A line can be translated as either ‘She finally spoke’ or ‘At last, she spoke.’",
    prompt: "Assume both are grammatically defensible. What different effects might the translations create, and what context would help you choose between them?",
    probes: [
      "What does moving the time expression to the front do to rhythm or emphasis?",
      "Could ‘finally’ imply impatience more strongly than ‘at last’?",
      "Would dialogue immediately before the line affect your choice?",
      "Is there always one best translation? Give me a principled answer.",
    ],
    concepts: ["translation", "emphasis", "rhythm", "tone", "context", "choice"],
    strongAnswer: "Both preserve basic temporal meaning but distribute emphasis and tone differently. A candidate should discuss syntax, rhythm and possible connotations, then use surrounding context and the wider voice of the text to justify a choice while recognising legitimate trade-offs in translation.",
  },
  {
    id: "rx-lang-3", track: "languages", title: "A repeated ordinary word", difficulty: "Stretch", time: 9,
    stimulus: "Across a short story, the word ‘still’ appears repeatedly: ‘still warm’, ‘still waiting’, ‘still there’, ‘still.’",
    prompt: "How would you decide whether that repetition is structurally important rather than accidental?",
    probes: [
      "What different grammatical jobs can ‘still’ perform in those examples?",
      "Could the repetition connect time, persistence and silence at once?",
      "What evidence elsewhere in the story would strengthen that reading?",
      "What would make you abandon the interpretation?",
    ],
    concepts: ["repetition", "structure", "syntax", "motif", "evidence", "interpretation"],
    strongAnswer: "A strong close reading begins with the changing grammatical and semantic roles of the repeated word, then tests whether the pattern aligns with broader structure, imagery or themes. It also states what counter-evidence would make the proposed motif less persuasive.",
  },
  {
    id: "rx-lang-4", track: "languages", title: "Can a text resist its author?", difficulty: "Challenge", time: 9,
    prompt: "An author says in an interview that a novel is ‘not political at all’, but many readers argue that its structure and conflicts are deeply political. What weight should the author's statement carry when interpreting the novel?",
    probes: [
      "Distinguish evidence about intention from evidence in the text itself.",
      "Could an author's later explanation change the meaning of an earlier work?",
      "Is a reading valid simply because the text can be made to support it?",
      "What would count as a stronger or weaker political interpretation?",
    ],
    concepts: ["author", "intention", "text", "interpretation", "evidence", "political"],
    strongAnswer: "Authorial intention is relevant evidence but need not determine meaning. Strong candidates distinguish historical intention, textual structure and reader interpretation, then set standards for a persuasive reading: explanatory power, textual evidence, coherence and ability to handle resistant details.",
  },
  {
    id: "rx-maths-5", track: "maths", title: "The missing handshake", difficulty: "Foundation", time: 8,
    stimulus: "Six students meet. Every pair shakes hands except one pair who have already met. No one shakes their own hand.",
    prompt: "How many handshakes happen? Show me a way to count that you would trust if the group were much larger.",
    probes: [
      "If each student reports five possible handshakes, why can you not simply multiply six by five?",
      "Can you express the answer for n students and k pairs who do not shake?",
      "The students report 14 handshakes. Could they each have shaken the same number of hands? Explain without listing every arrangement.",
      "What changes if two students leave before the meeting begins? Which missing-pair information would you need?",
    ],
    concepts: ["counting", "pairs", "double counting", "generalise", "degree", "evidence"],
    strongAnswer: "There are 6×5/2=15 unordered pairs, so 14 handshakes. Each handshake is counted twice if we add each person's partners, which explains the division by two. For n students with k missing pairs the count is n(n−1)/2−k. If all six shook the same number of hands after 14 handshakes, their degree would be 28/6, not an integer, so that is impossible. After two students leave, the result depends on whether the missing pair involved either of them.",
  },
  {
    id: "rx-physical-5", track: "physical", title: "Two cups under a lamp", difficulty: "Foundation", time: 8,
    stimulus: "Two identical cups contain the same amount of water at the same starting temperature. One is wrapped in matte black paper and the other in shiny foil. Both sit the same distance from a lamp.",
    prompt: "Which water sample do you predict will warm faster? Tell me what assumptions your prediction needs and how you would test it.",
    probes: [
      "Where does energy enter and leave each cup? Does the lamp emit only visible light?",
      "Could the foil change heat loss as well as absorption? How would that affect your prediction?",
      "What would you keep the same, and why would you swap the cup positions halfway through a repeat?",
      "If the black cup warms faster under the lamp but cools faster afterwards, is that a contradiction?",
    ],
    concepts: ["radiation", "absorption", "emission", "heat transfer", "control", "prediction"],
    strongAnswer: "A matte black surface may absorb more of the lamp's radiation than shiny foil, so the black cup may warm faster, but the outcome depends on lamp spectrum, surface properties and heat loss. Dark surfaces can also emit thermal radiation efficiently. Measure water temperature over time with equal volumes and starting temperatures, control distance and airflow, and swap positions or repeat to rule out position effects. Faster warming and faster cooling can coexist because absorption and emission are different parts of the energy balance.",
  },
  {
    id: "rx-life-5", track: "life", title: "Seedlings by the window", difficulty: "Foundation", time: 8,
    stimulus: "Twelve seedlings of the same species grow in two trays. The tray by a window has taller seedlings after a week. The window tray was also watered more often.",
    prompt: "Can you conclude that more light caused the height difference? Design the next experiment you would actually run.",
    probes: [
      "What competing explanation is already present in the observation?",
      "How would you allocate seedlings between light conditions, and what would you measure before starting?",
      "Why might height alone be a misleading measure of healthy growth?",
      "If the brighter group is still taller, what evidence would help you rule out a temperature difference near the window?",
    ],
    concepts: ["confounder", "light", "water", "randomisation", "growth", "measurement"],
    strongAnswer: "The observation cannot isolate light because watering differed; the window may also change temperature. Randomly allocate comparable seedlings to light conditions, keep water and other conditions as equal as possible, record initial size, and repeat with enough plants. Measure height alongside leaf area, biomass or health because low-light seedlings can elongate without growing more biomass. Temperature measurements or a light treatment away from the window would help separate effects.",
  },
  {
    id: "rx-law-5", track: "law", title: "The photograph and the poster", difficulty: "Foundation", time: 8,
    stimulus: "A college asks students for permission to photograph an open-day event. Months later it uses a close-up of one student on an advertising poster. The student objects. Assume the permission form says only 'photographs may be taken at the event'.",
    prompt: "What arguments would each side make about permission, and what facts would you need before reaching a view?",
    probes: [
      "Is permission to take a photograph necessarily permission for every later use of it?",
      "Would your analysis change if the poster showed a crowd rather than a close-up?",
      "What if the student had seen the camera and smiled? What could that reasonably establish?",
      "Draft one clearer sentence for the form that would reduce this dispute without hiding the intended use.",
    ],
    concepts: ["consent", "scope", "notice", "interpretation", "reasonable expectation", "remedy"],
    strongAnswer: "The college can point to event notice and apparent cooperation, while the student can distinguish taking a photograph from using an identifiable close-up in advertising. The form's narrow wording, context, visibility of the camera, age of the student and any other notice matter. A reasoned answer interprets the scope of permission and considers proportionate remedies without asserting a jurisdiction-specific legal outcome. Clear notice would identify advertising use and how an attendee can object.",
  },
  {
    id: "rx-humanities-5", track: "humanities", title: "The factory town ledger", difficulty: "Foundation", time: 8,
    stimulus: "A town ledger records 200 factory workers in 1850 and 400 in 1860. A later brochure says, 'The factory doubled the town's prosperity.'",
    prompt: "What does the ledger establish, and how would you investigate the brochure's much larger claim?",
    probes: [
      "Could the number of workers double while the town's population or wages move in a different direction?",
      "What is the brochure trying to persuade its readers to believe, and who produced it?",
      "Which other records would you compare, and what limitations would each have?",
      "Suppose household income rose but housing conditions worsened. Would that count as prosperity?",
    ],
    concepts: ["source", "prosperity", "causation", "context", "evidence", "definition"],
    strongAnswer: "The ledger reports a doubling of recorded factory workers, subject to how workers were counted. It does not show that prosperity doubled or that the factory caused any improvement. Compare population, wages, prices, housing, health and other employment records, examine the brochure's audience and purpose, and define whose prosperity and which measure are at issue. Different measures can support different conclusions.",
  },
  {
    id: "rx-econ-5", track: "economics", title: "The café price cut", difficulty: "Foundation", time: 8,
    stimulus: "A café sells 100 coffees a day at £4 each. Ingredients and cups cost £1.50 per coffee. It cuts the price to £3 and sells 130 coffees a day; assume its other daily costs do not change.",
    prompt: "Did the price cut help the café? Calculate the relevant figures, then tell me what your calculation leaves out.",
    probes: [
      "How do revenue and contribution after per-coffee costs differ before and after the cut?",
      "At £3, how many coffees would it need to sell to beat the old contribution?",
      "If the extra customers create a queue, how might that change your answer?",
      "Would one busy day establish a reliable change in demand? What comparison would you want?",
    ],
    concepts: ["revenue", "variable cost", "contribution", "demand", "capacity", "evidence"],
    strongAnswer: "Revenue falls from £400 to £390. Contribution after £1.50 per coffee falls from £250 to £195, so the price cut hurts daily profit under the stated unchanged fixed costs. At £3 the café needs at least 167 coffees to exceed £250 contribution (167×£1.50=£250.50). Queueing, staffing costs, repeat visits and day-to-day demand variation could alter the wider decision.",
  },
  {
    id: "rx-lang-5", track: "languages", title: "A tiny unfamiliar language", difficulty: "Foundation", time: 8,
    stimulus: "In a fictional language, 'nalo' means 'bird', 'nalo-ti' means 'birds', 'soro' means 'tree', and 'soro-ti' means 'trees'. You are also told that 'meka' means 'house'.",
    prompt: "What would you predict 'meka-ti' means? Explain both the pattern and why the examples do not prove your answer.",
    probes: [
      "What rule fits all four examples, and what other rule could also fit them?",
      "What new example would you request to test whether '-ti' always marks more than one?",
      "Suppose 'meka-ti' means 'neighbourhood'. How would you revise your hypothesis?",
      "How would you distinguish a plural suffix from a word ending that happens to look the same?",
    ],
    concepts: ["morphology", "plural", "pattern", "hypothesis", "counterexample", "generalisation"],
    strongAnswer: "The natural prediction is 'houses' because -ti corresponds to the plural in both supplied pairs. Two nouns are too few to establish a universal rule: the ending could mark a broader collective or behave differently for other noun classes. Ask for further singular-plural pairs and counterexamples, then revise the rule if 'meka-ti' has a collective meaning. The candidate should distinguish a supported prediction from a proven grammar.",
  },
]

export function realisticQuestionsForTrack(track: TrackId) {
  return realisticInterviewQuestions.filter(question => question.track === track)
}
