import type { TestQuestion } from "@/lib/oxbridge-data"

function rotate<T>(items: T[], shift: number) {
  const n = ((shift % items.length) + items.length) % items.length
  return [...items.slice(n), ...items.slice(0, n)]
}

function q(
  id: string,
  prompt: string,
  correct: string,
  distractors: [string, string, string, string],
  explanation: string,
  seed: number,
): TestQuestion {
  const options = rotate([correct, ...distractors], seed % 5)
  return {
    id,
    test: "TARA",
    section: "Problem Solving",
    difficulty: "Challenge",
    prompt,
    options,
    answer: options.indexOf(correct),
    explanation,
  }
}

// Separate family names are deliberate: the full-paper family balancer can
// distribute similarity reasoning across both forms instead of treating every
// item as one repeated template family.
export const taraSimilarityReliableReserveBank: TestQuestion[] = [
  q(
    "tara-spec-ps-similar-affine-a",
    "A device follows the same input-output rule for every row: 3→11, 5→17 and 8→26. Which pair follows that same rule?",
    "11→35",
    ["11→33", "10→32", "12→35", "13→38"],
    "The consistent rule is output = 3×input + 2: 3 gives 11, 5 gives 17 and 8 gives 26. Applying that same structure to 11 gives 3×11+2=35.",
    1,
  ),
  q(
    "tara-spec-ps-similar-ratio-b",
    "Four mixtures are compared with a reference mixture containing 6 parts water for every 4 parts concentrate. Which mixture has the same proportion as the reference?",
    "15 parts water to 10 parts concentrate",
    ["12 parts water to 10 parts concentrate", "16 parts water to 12 parts concentrate", "18 parts water to 15 parts concentrate", "21 parts water to 16 parts concentrate"],
    "The reference ratio 6:4 simplifies to 3:2. The ratio 15:10 also simplifies to 3:2; each other option has a different water-to-concentrate proportion.",
    3,
  ),
  q(
    "tara-spec-ps-similar-vector-c",
    "A point moves from (−2, 3) to (3, 1). Which movement has the same displacement?",
    "From (4, 6) to (9, 4)",
    ["From (4, 6) to (7, 1)", "From (1, −2) to (6, 1)", "From (0, 5) to (4, 3)", "From (−1, 4) to (5, 2)"],
    "The original displacement is +5 horizontally and −2 vertically. Only the movement from (4,6) to (9,4) reproduces the vector (+5,−2).",
    5,
  ),
  q(
    "tara-spec-ps-similar-procedure-d",
    "Procedure X starts with a number, doubles it, subtracts 6, then divides the result by 2. Which procedure has the same overall effect on every starting number?",
    "Subtract 3 from the starting number.",
    ["Subtract 6 from the starting number.", "Divide the starting number by 2, then subtract 3.", "Double the starting number, then subtract 3.", "Add 3 to the starting number."],
    "For a starting value x, Procedure X gives (2x−6)/2=x−3. Therefore it is equivalent for every input to subtracting 3 directly.",
    7,
  ),
  q(
    "tara-spec-ps-similar-growth-e",
    "A sequence is generated by multiplying the previous term by 2 and then adding 1: 2, 5, 11, 23, …. Which sequence is generated by the same rule?",
    "4, 9, 19, 39",
    ["4, 8, 16, 32", "4, 10, 22, 46", "4, 9, 18, 37", "4, 7, 15, 31"],
    "The required transition is next = 2×current + 1. Starting from 4 gives 9, then 19, then 39, so the keyed sequence has the same generating rule.",
    9,
  ),
  q(
    "tara-spec-ps-similar-scale-f",
    "Plan A uses 8 staff for 12 groups, keeping the staff-to-group ratio fixed. Which plan has the same staffing proportion?",
    "14 staff for 21 groups",
    ["10 staff for 18 groups", "12 staff for 20 groups", "15 staff for 20 groups", "16 staff for 21 groups"],
    "The reference ratio 8:12 simplifies to 2:3. The ratio 14:21 also simplifies to 2:3; the other options produce different staff-to-group proportions.",
    11,
  ),
]
