import type { FullPaperQuestion } from "@/lib/full-paper-question"

const difficulties: FullPaperQuestion["difficulty"][] = ["Stretch", "Challenge", "Stretch", "Challenge"]

function answerMask(values: [boolean, boolean, boolean, boolean, boolean]) {
  return values.reduce((mask, value, index) => value ? mask | (1 << index) : mask, 0)
}

function statementQuestion(
  id: string,
  prompt: string,
  statements: [string, string, string, string, string],
  answers: [boolean, boolean, boolean, boolean, boolean],
  explanation: string,
  seed: number,
): FullPaperQuestion {
  return { id, test: "UCAT", section: "Decision Making", difficulty: difficulties[seed % difficulties.length], prompt, options: [], answer: answerMask(answers), explanation, responseType: "yes-no-statements", statements, maxMarks: 2 }
}

// The production selector takes alternating questions for Forms 1 and 2.
// Indices 0-7 therefore provide four syllogism sets per form, while indices
// 8-15 provide four information-interpretation sets per form. This mirrors the
// two multi-statement item families reported in UCAT technical documentation.
export const ucatDecisionMakingStatementBank: FullPaperQuestion[] = [
  statementQuestion("ucat-dm-statements-01", "Every botanist is a researcher. No researcher is a pilot. Some botanists are tutors. Decide whether each conclusion follows from the information given.", ["Every botanist is a researcher.", "No botanist is a pilot.", "Some tutors are researchers.", "Every tutor is a botanist.", "Some pilots are botanists."], [true, true, true, false, false], "Botanists are inside the researcher set, and researchers cannot be pilots. The stated botanists who are tutors therefore show that some tutors are researchers. Nothing makes every tutor a botanist, and a botanist cannot be a pilot.", 0),
  statementQuestion("ucat-dm-statements-02", "All archivists are graduates. Some archivists are divers. No diver is a runner. Some graduates are runners. Decide whether each conclusion follows from the information given.", ["Every archivist is a graduate.", "Some divers are graduates.", "No archivist is a runner.", "Some graduates are not runners.", "Every graduate is an archivist."], [true, true, false, true, false], "The archivists who are divers must also be graduates, and no diver is a runner, so some graduates are not runners. Other archivists could still be runners, and the graduate-to-archivist relationship cannot be reversed.", 1),
  statementQuestion("ucat-dm-statements-03", "Every medic is a scientist. No scientist is a poet. Some medics are cyclists. Decide whether each conclusion follows from the information given.", ["No medic is a poet.", "Some cyclists are scientists.", "Every scientist is a medic.", "Some poets are medics.", "Some medics are not poets."], [true, true, false, false, true], "All medics are scientists and no scientist is a poet, so medics cannot be poets. The medics who are cyclists are scientists. The premises do not say that every scientist is a medic.", 2),
  statementQuestion("ucat-dm-statements-04", "All amber tokens are circles. No circle is a square. Some amber tokens are numbered. Decide whether each conclusion follows from the information given.", ["No amber token is a square.", "Some numbered objects are circles.", "Every numbered object is amber.", "Some numbered objects are not squares.", "No square is an amber token."], [true, true, false, true, true], "Amber tokens are circles, and circles cannot be squares. The numbered amber tokens are therefore numbered circles and are not squares. Nothing says that every numbered object is amber.", 3),
  statementQuestion("ucat-dm-statements-05", "Every ranger is trained. No trained person is a visitor. Some rangers are first-aiders. Decide whether each conclusion follows from the information given.", ["Every ranger is trained.", "No ranger is a visitor.", "Some first-aiders are trained.", "Every trained person is a ranger.", "Some visitors are rangers."], [true, true, true, false, false], "Rangers are a subset of trained people, and trained people cannot be visitors. The stated first-aider rangers must be trained. The premises do not reverse the trained-to-ranger relationship.", 4),
  statementQuestion("ucat-dm-statements-06", "All blue folders are locked. No locked folder is red. Some blue folders are archived. Decide whether each conclusion follows from the information given.", ["No blue folder is red.", "Some archived folders are locked.", "Every archived folder is blue.", "Some red folders are blue.", "Some blue folders are not red."], [true, true, false, false, true], "Every blue folder is locked and locked folders cannot be red, so no blue folder is red. The archived blue folders are locked. Nothing says that every archived folder is blue.", 5),
  statementQuestion("ucat-dm-statements-07", "Every physicist is a mathematician. Some physicists are teachers. No mathematician is an actor. Decide whether each conclusion follows from the information given.", ["No physicist is an actor.", "Some teachers are mathematicians.", "Every teacher is a physicist.", "Some actors are physicists.", "Some physicists are not actors."], [true, true, false, false, true], "Physicists are mathematicians and mathematicians cannot be actors. The physicists who are teachers are therefore teachers who are mathematicians. The premises do not make every teacher a physicist.", 6),
  statementQuestion("ucat-dm-statements-08", "All economists are graduates. Some economists are writers. No writer is a diver. Decide whether each conclusion follows from the information given.", ["Some graduates are writers.", "Some economists are not divers.", "Every writer is a graduate.", "No economist can be a diver.", "Every graduate is an economist."], [true, true, false, false, false], "The economists who are writers are graduates and cannot be divers, so the first two conclusions follow. Other economists need not be writers, so the premises do not exclude every economist from diving, and neither implication can be reversed.", 7),

  statementQuestion("ucat-dm-statements-09", "In a randomised study, 240 students were assigned either to retrieval-practice quizzes or to rereading for the same study time. The quiz group had a mean test score of 78 and the rereading group a mean of 72. No measure of spread or confidence interval is provided. Decide whether each conclusion follows from the study information.", ["The reported mean is six points higher in the quiz group.", "The study proves that quizzes improve the score of every student.", "Random allocation reduces concern that pre-existing differences explain the group means.", "Statistical significance can be determined from the two means alone.", "Equal study time removes one plausible time-on-task explanation."], [true, false, true, false, true], "The two reported means differ by six points. Random allocation and equal study time strengthen interpretation, but individual benefit is not guaranteed and significance cannot be established without information about variation and group sizes.", 8),
  statementQuestion("ucat-dm-statements-10", "A service recorded 150 appointments in Clinic A with a 12% non-attendance rate and 100 appointments in Clinic B with an 8% non-attendance rate. Decide whether each statement is supported by the recorded data.", ["Clinic A had 18 non-attendances.", "Clinic B had 8 non-attendances.", "The clinics had 26 non-attendances in total.", "The combined non-attendance rate was 10.4%.", "Clinic A accounted for more than two-thirds of all non-attendances."], [true, true, true, true, true], "Clinic A has 150×0.12=18 non-attendances and Clinic B has 100×0.08=8, giving 26 of 250 overall, or 10.4%. Clinic A contributes 18/26≈69.2%, which is more than two-thirds.", 9),
  statementQuestion("ucat-dm-statements-11", "An observational survey reports that people who cycle to work have fewer sick days on average than people who drive. The groups were not randomly assigned, and cyclists were younger on average. Decide whether each conclusion follows from the survey information.", ["The survey reports an association between travel mode and sick days.", "The survey proves that cycling causes fewer sick days.", "Age is a plausible confounding variable.", "Random assignment would help reduce systematic baseline differences between groups.", "The association must disappear after adjusting for age."], [true, false, true, true, false], "The survey establishes an association, not causation. Age differs between the groups and could confound the comparison. Random assignment would reduce this concern, but the information does not show that adjustment must remove the association.", 10),
  statementQuestion("ucat-dm-statements-12", "A council compares two otherwise similar libraries for six months. Library X extends evening opening while Library Y keeps its previous hours. Borrowing rises by 12% at X and by 2% at Y. No other measured service change differs between the libraries. Decide whether each conclusion follows from this comparison.", ["Borrowing increased at both libraries.", "The larger increase at X is consistent with extended hours contributing to borrowing.", "The comparison proves that extended hours caused exactly a ten-percentage-point increase.", "Library Y helps account for changes affecting both libraries over the same period.", "No unmeasured difference between the libraries could have influenced the result."], [true, true, false, true, false], "Both libraries increased, and the comparison strengthens the case that extended hours contributed to the larger rise at X. It does not identify an exact causal effect or rule out every unmeasured difference.", 11),
  statementQuestion("ucat-dm-statements-13", "A transport service records 200 journeys on Route A, of which 180 arrive on time, and 120 journeys on Route B, of which 96 arrive on time. Decide whether each statement is supported by the data.", ["Route A's on-time rate is 90%.", "Route B's on-time rate is 80%.", "There were 276 on-time journeys across both routes.", "The combined on-time rate is 86.25%.", "Route A had fewer late journeys than Route B."], [true, true, true, true, true], "Route A is 180/200=90% on time and has 20 late journeys. Route B is 96/120=80% on time and has 24 late journeys. Combined, 276 of 320 journeys are on time, which is 86.25%.", 12),
  statementQuestion("ucat-dm-statements-14", "A survey of 500 residents finds that 60% use a digital council service. Of the users, 70% report being satisfied; of the non-users, 50% report being satisfied with council services overall. Decide whether each statement follows from the survey figures.", ["Three hundred residents use the digital service.", "Two hundred and ten digital-service users report being satisfied.", "Two hundred residents do not use the digital service.", "One hundred non-users report being satisfied.", "Three hundred and ten residents in total report being satisfied in the two stated groups."], [true, true, true, true, true], "There are 500×0.60=300 users and 200 non-users. Satisfied users are 300×0.70=210 and satisfied non-users are 200×0.50=100, giving 310 in total.", 13),
  statementQuestion("ucat-dm-statements-15", "A randomised trial assigns 100 participants to Programme A and 100 to Programme B. Thirty people in A and twenty people in B meet the stated outcome. No confidence interval or significance test is reported. Decide whether each conclusion follows from the information provided.", ["The observed outcome rate is 30% in Programme A.", "The observed outcome rate is 20% in Programme B.", "The observed absolute difference is ten percentage points.", "The observed rate in A is 1.5 times the rate in B.", "The information alone proves that the population effect is statistically significant."], [true, true, true, true, false], "The observed rates are 30/100=30% and 20/100=20%, so the absolute difference is ten percentage points and the rate ratio is 1.5. Statistical significance cannot be established from these counts without the relevant inferential analysis.", 14),
  statementQuestion("ucat-dm-statements-16", "A college records 320 first-year students. Of these, 208 attend an optional induction workshop. Among attendees, 156 complete the first assignment on time; among the 112 non-attendees, 70 complete it on time. Participation was voluntary. Decide whether each conclusion follows from the recorded information.", ["The workshop attendance rate was 65%.", "The on-time rate among attendees was 75%.", "The on-time rate among non-attendees was 62.5%.", "Attendees had a higher observed on-time rate than non-attendees.", "The figures prove that workshop attendance caused the difference in on-time completion."], [true, true, true, true, false], "Attendance is 208/320=65%. The on-time rates are 156/208=75% and 70/112=62.5%. The observed association favours attendees, but voluntary participation means the figures do not prove a causal effect.", 15),
]
