import type { FullPaperQuestion } from "@/lib/full-paper-question"

const difficulties: FullPaperQuestion["difficulty"][] = ["Stretch", "Challenge", "Stretch", "Challenge"]

function answerMask(values: [boolean, boolean, boolean, boolean, boolean]) {
  return values.reduce((mask, value, index) => value ? mask | (1 << index) : mask, 0)
}

function statementQuestion(
  id: string,
  prompt: string,
  statements: [string, string, string, string, string],
  answers: [boolean, boolean, boolean, boolean, boolean],
  explanation: string,
  seed: number,
): FullPaperQuestion {
  return { id, test: "UCAT", section: "Decision Making", difficulty: difficulties[seed % difficulties.length], prompt, options: [], answer: answerMask(answers), explanation, responseType: "yes-no-statements", statements, maxMarks: 2 }
}

export const ucatDecisionMakingStatementBank: FullPaperQuestion[] = [
  statementQuestion("ucat-dm-statements-01", "Every botanist is a researcher. No researcher is a pilot. Some botanists are tutors. Decide whether each conclusion follows from the information given.", ["Every botanist is a researcher.", "No botanist is a pilot.", "Some tutors are researchers.", "Every tutor is a botanist.", "Some pilots are botanists."], [true, true, true, false, false], "Botanists are a subset of researchers, and researchers cannot be pilots. Because some botanists are tutors, at least some tutors are researchers. Nothing says every tutor is a botanist.", 0),
  statementQuestion("ucat-dm-statements-02", "All archivists are graduates. Some graduates are runners. No runners are divers. Some divers are archivists. Decide whether each conclusion follows.", ["Every archivist is a graduate.", "Some divers are graduates.", "No archivist is a runner.", "Some graduates are not runners.", "Every graduate is an archivist."], [true, true, false, true, false], "The divers who are archivists must be graduates, and because no diver is a runner those same people show that some graduates are not runners. The premises do not exclude other archivists from being runners and do not make all graduates archivists.", 1),
  statementQuestion("ucat-dm-statements-03", "All red cards are circles. Some circles are numbered. No numbered object is a square. Every square is blue. Decide whether each conclusion follows.", ["No red card is a square.", "Some circles are numbered.", "No numbered object is blue.", "Every square is blue.", "Some numbered objects are not squares."], [false, true, false, true, true], "The premises directly establish that some circles are numbered, all squares are blue, and numbered objects cannot be squares. They do not relate red cards to squares or rule out a numbered object being blue for some other reason.", 2),
  statementQuestion("ucat-dm-statements-04", "Five presentations A, B, C, D and E are scheduled in five consecutive slots. D is before A; A is before B; B is before C; and C is before E. Decide whether each conclusion follows.", ["D is before B.", "A is before C.", "E is in the final slot.", "C is before A.", "B is immediately before C."], [true, true, true, false, true], "The four ordering constraints force the unique order D-A-B-C-E. With exactly five presentations and five slots, B and C are therefore adjacent and E is last.", 3),
  statementQuestion("ucat-dm-statements-05", "Workshops K, L and M take place on Monday, Tuesday and Wednesday, one per day. K is before L. M is not on Monday. Decide whether each conclusion follows.", ["K is on Monday.", "M is on Tuesday.", "L is on Wednesday.", "L is before M.", "K is after M."], [true, true, true, false, false], "If K were Tuesday, L would have to be Wednesday and M Monday, which is forbidden. Therefore K is Monday; L must then be Wednesday and M Tuesday.", 4),
  statementQuestion("ucat-dm-statements-06", "A bag contains 4 red counters, 3 blue counters and 3 green counters. One counter is selected at random. Decide whether each statement is correct.", ["The probability of selecting red is 0.40.", "The probability of not selecting red is 0.60.", "Blue is more likely to be selected than green.", "The probability of selecting red or blue is 0.70.", "The probability of selecting green is 0.20."], [true, true, false, true, false], "There are 10 counters. Red is 4/10, non-red 6/10, blue and green are each 3/10, and red-or-blue is 7/10.", 5),
  statementQuestion("ucat-dm-statements-07", "In a randomised study, 200 students were assigned either to retrieval-practice flashcards or to rereading for the same study time. The flashcard group had a mean test score of 74 and the rereading group a mean of 68. No measure of spread or confidence interval is provided. Decide whether each conclusion follows.", ["The study reports a difference in mean score between the assigned methods.", "The results prove that flashcards improve the score of every individual student.", "Random allocation reduces concern that pre-existing group differences explain the mean-score difference.", "The statistical significance of the six-point difference can be determined from the two means alone.", "Keeping study time equal removes one plausible time-on-task explanation for the observed difference."], [true, false, true, false, true], "The reported means differ and randomisation plus equal study time strengthen causal interpretation, but individual benefit is not guaranteed and significance cannot be inferred without information such as variation and sample allocation.", 6),
  statementQuestion("ucat-dm-statements-08", "A service recorded 120 appointments in Clinic A with a 15% non-attendance rate and 80 appointments in Clinic B with a 10% non-attendance rate. Decide whether each statement is correct.", ["Clinic A had 18 non-attendances.", "Clinic B had 8 non-attendances.", "The two clinics had 26 non-attendances in total.", "The combined non-attendance rate was 12.5%.", "Clinic A accounted for more than two-thirds of all non-attendances."], [true, true, true, false, true], "Clinic A has 120×0.15=18 non-attendances and Clinic B 80×0.10=8, giving 26 of 200 overall (13%). A contributes 18/26, about 69.2%, which is more than two-thirds.", 7),
  statementQuestion("ucat-dm-statements-09", "All poets are readers. Some readers are cyclists. No cyclist is a chemist. Every chemist is an analyst. Decide whether each conclusion follows.", ["Every poet is a reader.", "Some cyclists are readers.", "No reader is a chemist.", "Some readers are not chemists.", "Every analyst is a chemist."], [true, true, false, true, false], "Some readers are cyclists and no cyclist is a chemist, so at least some readers are not chemists. The premises do not exclude all readers from chemistry and do not reverse the chemist-to-analyst relationship.", 8),
  statementQuestion("ucat-dm-statements-10", "If an alarm is active, a warning light flashes. If the warning light flashes, a log entry is created. The alarm is active. No information is given about sound. Decide whether each conclusion follows.", ["The warning light flashes.", "A log entry is created.", "The alarm must make a sound.", "If there is no log entry, the alarm cannot be active.", "A log entry proves that the alarm was active."], [true, true, false, true, false], "Alarm active implies light, and light implies a log. The contrapositive gives no log implies no active alarm. A log could arise for another reason, and nothing states that the alarm produces sound.", 9),
  statementQuestion("ucat-dm-statements-11", "Of 30 people surveyed, 18 drink tea, 14 drink coffee and 7 drink both. Decide whether each statement is correct.", ["Twenty-five people drink tea or coffee or both.", "Five people drink neither tea nor coffee.", "Eleven people drink tea but not coffee.", "Seven people drink coffee but not tea.", "More people drink coffee only than drink both drinks."], [true, true, true, true, false], "Inclusion-exclusion gives 18+14−7=25 drinking at least one, so 5 drink neither. Tea-only is 11 and coffee-only is 7, exactly equal to the number drinking both.", 10),
  statementQuestion("ucat-dm-statements-12", "A delivery route is 150 km. A vehicle travels the first 60 km at 40 km/h and the remaining 90 km at 60 km/h. Decide whether each statement is correct.", ["The first part of the journey takes 1.5 hours.", "The second part of the journey takes 1.5 hours.", "The whole journey takes 3 hours.", "The average speed for the whole journey is 50 km/h.", "The average speed is the simple arithmetic mean of 40 km/h and 60 km/h because the two distances are equal."], [true, true, true, true, false], "Both legs take 1.5 hours, so total time is 3 hours and average speed is 150/3=50 km/h. The distances are not equal, so the final statement's reasoning is false even though 50 is also the arithmetic mean.", 11),
  statementQuestion("ucat-dm-statements-13", "An observational survey finds that people who cycle to work report fewer sick days than people who drive. The groups were not randomly assigned, and cyclists were younger on average. Decide whether each conclusion follows.", ["The survey identifies an association between travel mode and reported sick days.", "The survey proves that cycling to work causes fewer sick days.", "Age is a plausible confounding variable in the comparison.", "Random assignment would help reduce systematic baseline differences between groups.", "The observed association must disappear after adjusting for age."], [true, false, true, true, false], "The survey establishes an association, not causation. Age differs between groups and could confound the comparison. Adjustment may alter the association, but the information does not show that it must disappear.", 12),
  statementQuestion("ucat-dm-statements-14", "Four tasks P, Q, R and S must each be assigned to a different time slot 1 to 4. P is earlier than Q. R is in slot 1. S is later than Q. Decide whether each conclusion follows.", ["P is in slot 2.", "Q is in slot 3.", "S is in slot 4.", "R is earlier than P.", "Q is earlier than P."], [true, true, true, true, false], "R occupies slot 1. The remaining chain P<Q<S must therefore fill slots 2, 3 and 4 respectively, fixing the complete order R-P-Q-S.", 13),
  statementQuestion("ucat-dm-statements-15", "A fair six-sided die is rolled once. Event A is 'the result is even' and event B is 'the result is greater than 3'. Decide whether each statement is correct.", ["The probability of event A is 1/2.", "The probability of event B is 1/2.", "The probability of both event A and event B occurring is 1/3.", "Events A and B are statistically independent.", "The probability of event A or event B occurring is 2/3."], [true, true, true, false, true], "A={2,4,6}, B={4,5,6}, their intersection is {4,6} so P(A∩B)=1/3. Independence would require 1/3=(1/2)(1/2), which is false. The union is {2,4,5,6}, probability 2/3.", 14),
  statementQuestion("ucat-dm-statements-16", "A council compares two otherwise similar libraries for six months. Library X extends its evening opening hours while Library Y keeps the old hours. Borrowing rises by 12% at X and by 2% at Y. No other measured service change differs between the libraries. Decide whether each conclusion follows.", ["Borrowing increased at both libraries during the comparison period.", "The larger increase at Library X is consistent with extended hours contributing to borrowing.", "The comparison proves that extended hours caused exactly a 10-percentage-point increase in borrowing.", "Library Y provides a comparison that helps account for changes affecting both libraries over the same period.", "No unmeasured difference between the libraries could have influenced the result."], [true, true, false, true, false], "Both libraries increased, and the comparison strengthens the case that extended hours contributed to the larger rise at X. It does not prove an exact causal effect or rule out every unmeasured difference.", 15),
]
