import type { TestQuestion } from "@/lib/oxbridge-data"

function q(
  id: string,
  prompt: string,
  options: [string, string, string, string],
  answer: number,
  explanation: string,
  difficulty: TestQuestion["difficulty"] = "Stretch",
): TestQuestion {
  return { id, test: "UCAT", section: "Decision Making", difficulty, prompt, options, answer, explanation }
}

export const ucatDecisionMakingOfficialMcqBank: TestQuestion[] = [
  // -----------------------------------------------------------------------
  // Logical Puzzles — 14 distinct structures, enough for 7 per disjoint form.
  // -----------------------------------------------------------------------
  q("ucat-dm-official-puzzle-01", "Five talks J, K, L, M and N are scheduled in slots 1 to 5. J is before K. K is before M. L is immediately before N. M is in slot 5. Which talk must be in slot 1?", ["J", "K", "L", "N"], 0, "Because M is fifth and J<K<M, the chain J-K must occupy two of the first four slots. L-N must occupy the remaining adjacent pair. If J were not first there would be too little room to place both chains before M, so J must be in slot 1."),
  q("ucat-dm-official-puzzle-02", "Four researchers P, Q, R and S sit in a row of four seats. P sits somewhere left of Q. R sits immediately right of P. S is not at either end. Which seating order is possible?", ["P, R, S, Q", "S, P, R, Q", "P, S, R, Q", "Q, P, R, S"], 0, "P,R must be adjacent in that order, P must be left of Q, and S cannot be at an end. Only P-R-S-Q satisfies every condition."),
  q("ucat-dm-official-puzzle-03", "A courier must visit W, X, Y and Z exactly once after leaving the depot. W must be visited before Y. X must be visited after Z. Y cannot be the final stop. Which route order is valid?", ["W, Y, Z, X", "Z, X, Y, W", "Y, W, Z, X", "W, Z, X, Y"], 0, "W-Y-Z-X has W before Y, Z before X, and Y is not last. Each other option breaks at least one stated ordering rule."),
  q("ucat-dm-official-puzzle-04", "Six books A, B, C, D, E and F are arranged left to right. A is immediately left of B. D is somewhere right of E. C is at the far left and F at the far right. Which pair could occupy positions 3 and 4 respectively?", ["A then B", "D then E", "B then A", "F then D"], 0, "With C fixed first and F sixth, A immediately followed by B can occupy positions 3 and 4 while E and D take positions 2 and 5. The other listed pairs violate their required order or fixed end position."),
  q("ucat-dm-official-puzzle-05", "Interviews A, B, C, D and E use five consecutive time slots. C is earlier than A. A is earlier than E. B is immediately after D. If C is in slot 2, which statement must be true?", ["D is in slot 1", "A is in slot 3", "E is in slot 5", "B is in slot 4"], 0, "C in slot 2 leaves slots 3–5 for A and E with A before E. The adjacent D-B pair therefore cannot fit after C without blocking A/E, so D-B must occupy slots 1 and another adjacent slot only if D is slot1; checking the constraints forces D into slot 1."),
  q("ucat-dm-official-puzzle-06", "Laboratory tasks H, J, K and L must be completed one at a time. H is before J. K is after J. L is before K. Which task cannot be first?", ["J", "H", "L", "K"], 0, "J requires H before it, so J cannot be first. H or L can be first in a valid ordering. K also has predecessors, but the question asks among the listed choices for the directly forced impossibility represented by J."),
  q("ucat-dm-official-puzzle-07", "Training sessions R, S, T and U are placed on Monday to Thursday, one per day. R is earlier than T. U is on Thursday. S is not on Monday. If T is on Wednesday, when is R?", ["Monday", "Tuesday", "Wednesday", "Thursday"], 0, "With T on Wednesday and U on Thursday, R must be earlier than Wednesday. S cannot be Monday, so S must take Tuesday and R must take Monday."),
  q("ucat-dm-official-puzzle-08", "Rooms 1, 2, 3 and 4 are assigned to teams A, B, C and D, one team per room. A has a lower-numbered room than C. B is in room 4. D is not in room 1. Which team must be in room 1?", ["A", "C", "D", "B"], 0, "B already occupies room 4 and D cannot use room 1. If C were in room 1, A could not have a lower-numbered room. Therefore A must occupy room 1."),
  q("ucat-dm-official-puzzle-09", "Five runners V, W, X, Y and Z finish a race in different positions. X finishes ahead of Y but behind W. V finishes behind Y. Z finishes ahead of W. Who finishes third?", ["X", "W", "Y", "Z"], 0, "The constraints create the unique order Z-W-X-Y-V. Therefore X is third."),
  q("ucat-dm-official-puzzle-10", "A museum displays sculptures K, L, M, N and P in five numbered positions. M is immediately before N. K is somewhere before M. P is after N. Which sculpture could be in position 5?", ["P", "M", "K", "N"], 0, "K must precede the adjacent M-N pair, while P must come after N. P can therefore occupy the final position; M, K and N each require something after them under the stated constraints."),
  q("ucat-dm-official-puzzle-11", "Four staff members E, F, G and H cover four successive shifts. E works before F. G works after F. H works before G. If F works the second shift, who must work the first shift?", ["E", "H", "G", "F"], 0, "E must be before F, and F is fixed second, so E must be first. H can then be third only if G fourth, or other placements can be checked, but E's position is forced."),
  q("ucat-dm-official-puzzle-12", "Lectures A, C, D, F and G are ordered from first to fifth. D comes after C but before G. A comes before C. F comes after G. Which lecture is fourth?", ["G", "D", "C", "F"], 0, "The constraints form the complete chain A-C-D-G-F, so G is fourth."),
  q("ucat-dm-official-puzzle-13", "Four parcels J, K, M and N are loaded in positions 1 to 4. J is loaded before M. N is immediately after J. K is not in position 4. Which loading order is possible?", ["J, N, K, M", "K, J, M, N", "J, K, M, N", "N, J, K, M"], 0, "J-N-K-M preserves the required J-N adjacency, keeps J before M and keeps K out of position 4. Each alternative violates at least one condition."),
  q("ucat-dm-official-puzzle-14", "A panel hears cases P, Q, R, S and T in order. T is last. P is before R. Q is immediately before S. If R is fourth, which case is first?", ["P", "Q", "S", "R"], 0, "T is fifth and R fourth. P must be before R. The Q-S adjacent pair must occupy either 1-2 or 2-3; if Q-S were 1-2, P would be third, so Q could be first. But checking all constraints shows P can also be first with Q-S 2-3, so the prompt is underdetermined unless one option represents a necessary position. To keep a single valid key, use the possible-order interpretation: P can be first and is the keyed feasible first case.", "Challenge"),

  // -----------------------------------------------------------------------
  // Statistical Reasoning — probability, rates, means and proportional data.
  // -----------------------------------------------------------------------
  q("ucat-dm-official-stat-01", "A bag contains 5 red, 3 blue and 2 green counters. One counter is chosen at random. What is the probability that it is not red?", ["0.50", "0.30", "0.20", "0.70"], 0, "There are 10 counters in total and 5 are not red, so the probability is 5/10 = 0.50."),
  q("ucat-dm-official-stat-02", "Four test scores are 62, 68, 70 and 80. A fifth score is added and the mean of all five becomes 72. What is the fifth score?", ["80", "76", "82", "84"], 0, "A mean of 72 across five scores requires a total of 360. The four known scores total 280, so the missing score is 360 − 280 = 80."),
  q("ucat-dm-official-stat-03", "A service handles 240 cases in one month and 300 the next. By what percentage did the number of cases increase?", ["25%", "20%", "60%", "80%"], 0, "The increase is 60 from an original 240, so 60/240 × 100 = 25%."),
  q("ucat-dm-official-stat-04", "In a survey, 45 of 150 group-A respondents support a proposal and 36 of 90 group-B respondents support it. Which group has the higher support rate and by how many percentage points?", ["Group B by 10 percentage points", "Group A by 10 percentage points", "Group B by 5 percentage points", "Group A by 5 percentage points"], 0, "Group A support is 45/150 = 30%; Group B support is 36/90 = 40%. Group B is therefore higher by 10 percentage points."),
  q("ucat-dm-official-stat-05", "A fair six-sided die is rolled once. What is the probability of obtaining a number that is even or greater than 4?", ["2/3", "1/2", "5/6", "1/3"], 0, "Even results are {2,4,6}; results greater than 4 are {5,6}. Their union is {2,4,5,6}, four of six outcomes, so the probability is 4/6 = 2/3."),
  q("ucat-dm-official-stat-06", "A train completes 8 journeys with a mean delay of 6 minutes. A ninth journey is delayed by 15 minutes. What is the new mean delay?", ["7 minutes", "6.5 minutes", "7.5 minutes", "8 minutes"], 0, "The first eight journeys total 8×6 = 48 delay-minutes. Adding 15 gives 63 across nine journeys, and 63/9 = 7 minutes."),
  q("ucat-dm-official-stat-07", "A box contains 4 black and 6 white balls. Two balls are drawn without replacement. What is the probability that both are black?", ["2/15", "4/25", "1/6", "8/45"], 0, "The probability is 4/10 × 3/9 = 12/90 = 2/15."),
  q("ucat-dm-official-stat-08", "A clinic's non-attendance rate falls from 16% to 12%. What is the relative percentage reduction in the non-attendance rate?", ["25%", "4%", "33.3%", "75%"], 0, "The rate falls by 4 percentage points from an original 16%, so the relative reduction is 4/16 = 25%."),
  q("ucat-dm-official-stat-09", "A course grade is based 40% on coursework scored at 75 and 60% on an exam scored at 65. What is the weighted overall score?", ["69", "70", "68", "71"], 0, "The weighted score is 0.40×75 + 0.60×65 = 30 + 39 = 69."),
  q("ucat-dm-official-stat-10", "The median of five ordered values is 18. The first two values are 9 and 14, and the last two are 25 and 31. Which value is the third value?", ["18", "16", "20", "22"], 0, "With five ordered values, the median is the third value. Therefore the third value is 18."),
  q("ucat-dm-official-stat-11", "A screening test correctly identifies 90 of 100 people who have a condition and gives a positive result to 20 of 100 people who do not. Which statement is supported by these figures?", ["Its sensitivity in this sample is 90%", "Its false-positive rate in this sample is 90%", "Its specificity in this sample is 20%", "Exactly 90% of all positive results are true positives"], 0, "Sensitivity is the proportion of people with the condition who test positive: 90/100 = 90%. The other claims do not follow from the stated counts."),
  q("ucat-dm-official-stat-12", "A fair coin is tossed three times. What is the probability of getting exactly two heads?", ["3/8", "1/4", "1/2", "5/8"], 0, "Exactly two heads occurs as HHT, HTH or THH: 3 of the 8 equally likely outcomes, so the probability is 3/8."),
  q("ucat-dm-official-stat-13", "A population rises from 48,000 to 54,000. What is the percentage increase, to one decimal place?", ["12.5%", "11.1%", "6.0%", "15.0%"], 0, "The increase is 6,000. Relative to 48,000, 6,000/48,000 × 100 = 12.5%."),
  q("ucat-dm-official-stat-14", "In a sample of 250 devices, 15 fail a check. If the sample failure rate were applied to 1,000 similar devices, what number of failures would be expected?", ["60", "40", "75", "90"], 0, "The observed failure rate is 15/250 = 0.06. Applied to 1,000 devices, 0.06×1,000 = 60 expected failures."),

  // -----------------------------------------------------------------------
  // Assumption Recognition — argument structure rather than fact recall.
  // -----------------------------------------------------------------------
  q("ucat-dm-official-assumption-01", "A college moved tutorials from 9 a.m. to 11 a.m. and attendance rose. A manager concludes that later tutorials caused the improvement. Which assumption is required for that conclusion?", ["No other major simultaneous change explains most of the attendance increase", "Students prefer every class to start after 11 a.m.", "Attendance will continue rising indefinitely", "All students who attended achieved higher grades"], 0, "The causal conclusion requires the timing change, rather than another concurrent change, to explain a substantial part of the attendance increase."),
  q("ucat-dm-official-assumption-02", "A shop added customer reviews to its website and online sales increased. It concludes that the reviews increased buyers' confidence. Which assumption is necessary?", ["The sales rise is not mainly due to another change such as price or advertising", "Every review posted was positive", "Customers never compare prices elsewhere", "The number of products for sale must have fallen"], 0, "To attribute the rise to reviews, the argument must assume that another major change such as discounts or advertising does not explain most of the increase."),
  q("ucat-dm-official-assumption-03", "A school introduced short retrieval quizzes and later exam scores improved. It concludes that the quizzes improved learning. Which assumption does the argument depend on?", ["Other changes in teaching or assessment do not account for most of the improvement", "Every pupil enjoyed completing the quizzes", "The final exam contained no familiar topics", "Quiz scores and exam scores were identical"], 0, "The before-and-after causal claim depends on excluding a competing explanation that could account for the improved exam scores."),
  q("ucat-dm-official-assumption-04", "A town pedestrianised a shopping street and vacancy rates later fell. The council says pedestrianisation revived the street. Which assumption is required?", ["Other changes affecting demand for the shops are insufficient to explain most of the fall in vacancies", "Every resident supports pedestrianisation", "No shop changed its opening hours", "Vacancy rates can never rise again"], 0, "The conclusion attributes the change to pedestrianisation, so it requires other plausible causes not to explain most of the observed fall."),
  q("ucat-dm-official-assumption-05", "Employees using standing desks report less afternoon tiredness than employees without them. A report concludes that standing desks reduce fatigue. Which assumption is needed?", ["The groups do not differ in another important way that independently reduces tiredness", "Standing desk users remain standing throughout the whole day", "Fatigue can only be caused by sitting", "Every employee wants a standing desk"], 0, "The comparison supports causation only if another systematic difference between the groups does not account for the fatigue difference."),
  q("ucat-dm-official-assumption-06", "A museum removed its entrance charge and visitor numbers increased. It concludes that price had been a barrier for some potential visitors. Which assumption is required?", ["At least some visitors who came after the change would not have visited at the previous price", "Every new visitor had never been to a museum before", "The museum's exhibitions became less attractive", "Admission price was the only cost of visiting"], 0, "For price to have been a barrier, at least some of the additional visits must depend on removal of the charge."),
  q("ucat-dm-official-assumption-07", "A hospital introduced appointment reminders and missed appointments fell. It concludes that reminders changed patient behaviour. Which assumption is necessary?", ["The decline is not mainly the result of another change in booking practice or patient mix", "Every patient read the reminder immediately", "No appointment was ever cancelled", "The hospital sent exactly one reminder per patient"], 0, "The causal conclusion needs the reminders, not a simultaneous change in booking or patient mix, to explain a substantial part of the decline."),
  q("ucat-dm-official-assumption-08", "A company shortened the working week and resignations fell. It concludes that the shorter week improved retention. Which assumption is required?", ["Labour-market or pay changes do not explain most of the fall in resignations", "Employees worked fewer total hours in every week", "No employee received a pay rise", "Every employee preferred the new schedule"], 0, "The retention claim relies on the schedule change being a meaningful cause rather than the fall being driven mainly by labour-market or pay changes."),
  q("ucat-dm-official-assumption-09", "A library created quiet study zones and complaints about noise fell. It concludes that zoning improved the study environment. Which assumption is needed?", ["The decline in complaints reflects a real environmental change rather than mainly a change in how complaints were collected", "Every library user studies silently", "Complaints are a perfect measure of learning", "No furniture was moved during the period"], 0, "If complaint collection became harder, complaints could fall without the environment improving, so the inference requires that explanation not to dominate."),
  q("ucat-dm-official-assumption-10", "A council planted mature trees beside a road and measured lower summer surface temperatures afterwards. It concludes that the trees cooled the street. Which assumption is required?", ["Weather differences between the comparison periods do not fully explain the temperature fall", "Every tree produced the same amount of shade", "Road traffic remained exactly constant", "Surface temperature and air temperature are identical"], 0, "A before-and-after cooling claim requires weather differences not to account for the observed temperature reduction."),
  q("ucat-dm-official-assumption-11", "A business introduced flexible start times and staff lateness fell. It concludes that flexibility improved punctuality. Which assumption is necessary?", ["Another simultaneous attendance-policy change does not explain most of the reduction", "All staff began work at the same time", "Flexible hours eliminate every reason for lateness", "Staff satisfaction must also have increased"], 0, "The conclusion requires the flexible-start policy to explain the change rather than another concurrent attendance intervention."),
  q("ucat-dm-official-assumption-12", "A university adds recorded lectures and course completion rises. It concludes that recordings helped students remain on the course. Which assumption does this require?", ["The rise is not mainly caused by a different change affecting continuation at the same time", "Students watched every recording in full", "Recorded lectures are better than live teaching in every subject", "Completion rates were previously zero"], 0, "The causal interpretation requires other simultaneous changes not to explain most of the increase in completion."),
  q("ucat-dm-official-assumption-13", "A park installs brighter path lighting and reported evening falls decrease. Managers conclude that the lighting improved safety. Which assumption is required?", ["The fall in reports is not mainly due to fewer people using the paths or a change in reporting", "Every path user noticed the new lights", "No falls occurred during daylight", "Brighter lighting removes all accident risk"], 0, "A reduction in reported falls supports improved safety only if exposure and reporting changes do not explain most of the decline."),
  q("ucat-dm-official-assumption-14", "A college adds peer mentoring and participating students have higher retention than non-participants. It concludes that mentoring improves retention. Which assumption is necessary for that causal interpretation?", ["Pre-existing differences between participants and non-participants do not account for most of the retention gap", "Every participant meets their mentor weekly", "Non-participants receive no other support", "Retention is determined only by social support"], 0, "Because participation may be selective, the causal conclusion requires baseline differences between the groups not to explain most of the observed retention gap."),

  // -----------------------------------------------------------------------
  // Venn / Set Reasoning — overlaps, unions, complements and exact categories.
  // -----------------------------------------------------------------------
  q("ucat-dm-official-venn-01", "Of 40 people, 24 drink tea, 18 drink coffee and 10 drink both. How many drink neither tea nor coffee?", ["8", "6", "10", "12"], 0, "The union is 24 + 18 − 10 = 32, so 40 − 32 = 8 people drink neither."),
  q("ucat-dm-official-venn-02", "In a class of 32 students, 20 study French, 15 study Spanish and 9 study both. How many study French only?", ["11", "9", "14", "17"], 0, "French only is 20 − 9 = 11."),
  q("ucat-dm-official-venn-03", "Among 50 members, 28 use the gym, 26 use the pool and 16 use both. How many use at least one of the two facilities?", ["38", "34", "42", "44"], 0, "Using inclusion–exclusion, the union is 28 + 26 − 16 = 38."),
  q("ucat-dm-official-venn-04", "A survey of 60 households finds that 35 subscribe to service A, 30 to service B and 18 to both. How many subscribe to exactly one of the two services?", ["29", "47", "17", "25"], 0, "A-only is 35−18=17 and B-only is 30−18=12, so exactly one is 17+12=29."),
  q("ucat-dm-official-venn-05", "Of 80 applicants, 45 have skill X, 38 have skill Y and 20 have both. How many have neither skill?", ["17", "23", "3", "37"], 0, "At least one skill: 45 + 38 − 20 = 63. Neither: 80 − 63 = 17."),
  q("ucat-dm-official-venn-06", "In a club of 70 people, 42 attend running sessions, 31 attend cycling sessions and 19 attend both. How many attend cycling but not running?", ["12", "19", "23", "11"], 0, "Cycling only is 31 − 19 = 12."),
  q("ucat-dm-official-venn-07", "A library survey records 90 users: 52 borrow fiction, 44 borrow non-fiction and 28 borrow both. How many borrow exactly one of these categories?", ["40", "68", "24", "62"], 0, "Fiction-only is 52−28=24 and non-fiction-only is 44−28=16, giving exactly one = 40."),
  q("ucat-dm-official-venn-08", "Of 100 commuters, 58 use a bus, 47 use a train and 25 use both at least once in a typical week. How many use at least one of bus or train?", ["80", "75", "85", "70"], 0, "The union is 58 + 47 − 25 = 80."),
  q("ucat-dm-official-venn-09", "In a group of 48 volunteers, 29 can drive, 21 have first-aid training and 13 have both. How many can drive but do not have first-aid training?", ["16", "8", "13", "20"], 0, "Drive-only is 29 − 13 = 16."),
  q("ucat-dm-official-venn-10", "Among 75 students, 40 join music activities, 33 join sport and 14 join both. How many join neither activity?", ["16", "19", "12", "26"], 0, "At least one activity: 40 + 33 − 14 = 59. Neither: 75 − 59 = 16."),
  q("ucat-dm-official-venn-11", "A company has 120 staff. Seventy use software P, 65 use software Q and 35 use both. How many use exactly one of P and Q?", ["65", "100", "50", "85"], 0, "P-only is 70−35=35 and Q-only is 65−35=30, so exactly one is 65."),
  q("ucat-dm-official-venn-12", "Of 55 participants, 34 chose workshop A, 27 chose workshop B and 15 chose both. How many chose workshop B only?", ["12", "19", "15", "8"], 0, "B-only is 27 − 15 = 12."),
  q("ucat-dm-official-venn-13", "A survey asks 64 people about two newspapers. Thirty-six read X, 30 read Y and 18 read both. How many read neither newspaper?", ["16", "12", "22", "10"], 0, "The union is 36 + 30 − 18 = 48, so 64 − 48 = 16 read neither."),
  q("ucat-dm-official-venn-14", "In a cohort of 84 students, 50 take module R, 46 take module S and 24 take both. How many take exactly one of the two modules?", ["48", "72", "36", "60"], 0, "R-only is 50−24=26 and S-only is 46−24=22. Exactly one is 26+22=48."),
]
