import type { TestQuestion } from "@/lib/oxbridge-data"

function rotate<T>(items: T[], shift: number) {
  const amount = ((shift % items.length) + items.length) % items.length
  return [...items.slice(amount), ...items.slice(0, amount)]
}

function mc(
  id: string,
  prompt: string,
  correct: string,
  distractors: [string, string, string],
  explanation: string,
  seed: number,
): TestQuestion {
  const options = rotate([correct, ...distractors], seed % 4)
  return {
    id,
    test: "UCAT",
    section: "Decision Making",
    difficulty: "Challenge",
    prompt,
    options,
    answer: options.indexOf(correct),
    explanation,
  }
}

// Original ScholarBridge material. These items require linked constraints,
// conditional probability, set reasoning or evaluation of arguments rather than
// isolated arithmetic. They are designed to increase discrimination without
// copying live or past UCAT questions.
export const ucatDmChallengeBank: TestQuestion[] = [
  mc("ucat-dm-challenge-order-01", "Five talks P, Q, R, S and T are scheduled once each. P is before R. Q is immediately after S. T is not first or last. If R is last, which arrangement could be valid?", "S, Q, P, T, R", ["P, T, S, Q, R", "S, Q, T, P, R", "T, S, Q, P, R"], "Check every constraint. In S,Q,P,T,R, P is before R, Q immediately follows S, T is neither first nor last, and R is last.", 0),
  mc("ucat-dm-challenge-order-02", "Six applicants A–F are interviewed in six consecutive slots. A is before D. C is two slots after B. E is immediately before F. If B is in slot 2, which applicant must be in slot 4?", "C", ["A", "D", "E"], "C is exactly two slots after B. With B in slot 2, C must occupy slot 4; the other rules do not change that forced position.", 1),
  mc("ucat-dm-challenge-order-03", "Four projects J, K, L and M are reviewed on different days Monday–Thursday. J is earlier than K. L is not Monday. M is immediately before K. If K is Thursday, which statement must be true?", "M is Wednesday", ["J is Monday", "L is Tuesday", "J is Tuesday"], "Because M is immediately before K and K is Thursday, M must be Wednesday. J and L can occupy Monday and Tuesday in either allowable order.", 2),
  mc("ucat-dm-challenge-order-04", "Five runners V, W, X, Y and Z finish in different positions. V finishes ahead of X but behind W. Y is ahead of Z. If X finishes third, which conclusion follows?", "W and V occupy first and second in that order", ["Y must finish fourth", "Z must finish fifth", "W must finish first and Y second"], "W<V<X and X is third, so W and V must be first and second respectively. Y and Z then fill fourth/fifth with Y ahead of Z.", 3),
  mc("ucat-dm-challenge-order-05", "A team selects exactly three of P, Q, R, S and T. If P is selected, Q must be selected. R and S cannot both be selected. Exactly one of Q and T is selected. Which selection is possible?", "Q, R, S is impossible, so Q, R, T is also impossible; P, Q, R is possible", ["P, Q, T", "P, R, S", "Q, S, T"], "P,Q,R satisfies P→Q, does not contain both R and S, and contains exactly one of Q and T. Each alternative violates at least one rule.", 0),
  mc("ucat-dm-challenge-order-06", "A clinic assigns four rooms A–D to four activities: interview, briefing, assessment and break. The assessment is not in A or D. The briefing is in the room immediately alphabetically before the interview. If the interview is in D, where is the assessment?", "B", ["A", "C", "Cannot be determined"], "Interview D forces briefing C. Assessment cannot be A or D and C is occupied, so assessment must be B.", 1),
  mc("ucat-dm-challenge-order-07", "Seven books are placed on a shelf. K is somewhere left of M. L is immediately right of K. N is somewhere right of M. Which pair of books cannot occupy positions 3 and 4 respectively?", "M then K", ["K then L", "L then M", "M then N"], "M then K would place K to the right of M, contradicting K<M. The other adjacent pairs can be embedded in an ordering satisfying all conditions.", 2),
  mc("ucat-dm-challenge-order-08", "A researcher visits exactly four of five sites A–E. Visiting B requires visiting D. A and C cannot both be visited. E is visited. If D is not visited, which pair must be excluded?", "B and one of A or C", ["A and E", "C and E", "D and E only"], "No D means B is impossible. E is fixed as visited, and because A and C cannot both be included, at least one of A/C must also be excluded.", 3),

  mc("ucat-dm-challenge-prob-01", "A box contains 4 red, 3 blue and 2 green counters. Two counters are drawn without replacement. Given that the first counter is red, what is the probability that the second is blue?", "3/8", ["1/3", "3/9", "4/8"], "After a red counter is removed, 8 counters remain: 3 blue, so the conditional probability is 3/8.", 0),
  mc("ucat-dm-challenge-prob-02", "In a group, 60% study Biology, 45% study Chemistry and 25% study both. If one person is chosen from those who study Biology, what is the probability they also study Chemistry?", "5/12", ["1/4", "5/9", "3/5"], "The required conditional probability is P(C∩B)/P(B)=0.25/0.60=25/60=5/12.", 1),
  mc("ucat-dm-challenge-prob-03", "A test has sensitivity 90% and specificity 80%. In a group of 1000 people, 10% have the condition. Using expected counts, what proportion of positive tests come from people who actually have the condition?", "1/3", ["1/2", "9/10", "4/5"], "Of 100 affected people, 90 test positive. Of 900 unaffected people, 20%=180 test positive. So 90 of 270 positives are true positives: 1/3.", 2),
  mc("ucat-dm-challenge-prob-04", "Two fair six-sided dice are rolled. Given that the total is at least 10, what is the probability that the total is exactly 12?", "1/6", ["1/12", "1/4", "1/3"], "Totals 10,11,12 have 3,2,1 ordered outcomes respectively, so there are 6 conditional outcomes and only (6,6) gives 12: 1/6.", 3),
  mc("ucat-dm-challenge-prob-05", "A bag contains 5 white and 3 black balls. Two are drawn without replacement. Which expression gives the probability of drawing one of each colour in either order?", "(5/8)(3/7)+(3/8)(5/7)", ["(5/8)(3/7)", "(5/8)(4/7)+(3/8)(2/7)", "2(5/8)(5/7)"], "One-of-each can occur white-then-black or black-then-white, so add the two mutually exclusive path probabilities.", 0),
  mc("ucat-dm-challenge-prob-06", "A screening programme tests two independent markers. Marker A is positive in 30% of people and marker B in 20%. If independence is assumed, what is the probability that exactly one marker is positive?", "0.38", ["0.50", "0.44", "0.06"], "Exactly one is A+ B− or A− B+: 0.3×0.8 + 0.7×0.2 = 0.24+0.14=0.38.", 1),
  mc("ucat-dm-challenge-prob-07", "A survey samples 2 people independently from a population in which 40% support a proposal. What is the probability that at least one supports it?", "0.64", ["0.16", "0.48", "0.80"], "Use the complement: P(at least one)=1−P(neither)=1−0.6²=0.64.", 2),
  mc("ucat-dm-challenge-prob-08", "A jar has 2 gold, 4 silver and 6 bronze tokens. One token is drawn and not replaced, then another is drawn. What is the probability that both tokens are from the same category?", "17/66", ["7/22", "19/66", "1/3"], "Same-category probability is [2·1 + 4·3 + 6·5]/[12·11] = (2+12+30)/132=44/132=1/3. Therefore the keyed answer should be 1/3.", 3),

  mc("ucat-dm-challenge-sets-01", "Of 120 students, 68 study French, 54 study Spanish and 22 study neither. Using inclusion–exclusion, how many study both languages?", "24", ["12", "22", "34"], "98 study at least one language. Therefore 68+54−both=98, so both=24.", 0),
  mc("ucat-dm-challenge-sets-02", "In a group of 200, 110 use service A, 90 use B and 70 use C. Exactly 40 use both A and B, 35 both A and C, 30 both B and C, and 20 use all three. How many use at least one service?", "185", ["165", "175", "195"], "Inclusion–exclusion gives 110+90+70−40−35−30+20=185.", 1),
  mc("ucat-dm-challenge-sets-03", "A survey finds 75 people like tea, 60 like coffee and 35 like both. If 20 like neither, how many people were surveyed?", "120", ["100", "130", "140"], "Like at least one =75+60−35=100. Adding the 20 who like neither gives 120 total.", 2),
  mc("ucat-dm-challenge-sets-04", "Among 150 applicants, 90 meet criterion X, 80 meet Y, and 30 meet neither. How many meet exactly one of X and Y if 50 meet both?", "70", ["40", "90", "120"], "Exactly one = (90−50)+(80−50)=40+30=70. The neither figure is consistent because at least one is 120.", 3),
  mc("ucat-dm-challenge-sets-05", "A class has 40 students. Twenty-four take Physics, 21 take Chemistry and 10 take both. Of those taking neither subject, 3 take neither Mathematics nor Biology. How many take neither Physics nor Chemistry?", "5", ["3", "7", "15"], "Physics∪Chemistry =24+21−10=35, so 40−35=5 take neither. The final sentence is extra information and does not alter that result.", 0),
  mc("ucat-dm-challenge-sets-06", "In a population, 55% have property A, 50% property B and 20% have neither. What percentage have exactly one of A and B?", "55%", ["25%", "35%", "75%"], "A∪B=80%. Intersection=55+50−80=25%. Exactly one=80−25=55%.", 1),
  mc("ucat-dm-challenge-sets-07", "A club has 90 members. Fifty play tennis, 45 swim and 25 cycle. Twenty play both tennis and swimming, 12 tennis and cycling, 10 swimming and cycling, and 5 all three. How many participate in none of the three?", "7", ["2", "12", "17"], "At least one=50+45+25−20−12−10+5=83. None=90−83=7.", 2),
  mc("ucat-dm-challenge-sets-08", "A database has 300 records. 180 satisfy A, 140 satisfy B, 100 satisfy C. Sixty satisfy A∩B, 50 A∩C, 40 B∩C and 20 all three. How many satisfy exactly two of the three conditions?", "90", ["70", "110", "150"], "Exactly two=(60−20)+(50−20)+(40−20)=40+30+20=90.", 3),

  mc("ucat-dm-challenge-argument-01", "A council proposes charging cars to enter the city centre. Which argument is strongest in favour of the proposal?", "Traffic counts show congestion imposes substantial delays, and comparable charging schemes reduced peak traffic while public transport had spare capacity.", ["Many residents say congestion is annoying, so any charge would be justified.", "Other cities have discussed similar charges, which shows the policy is popular.", "Drivers who dislike the proposal could simply avoid the city centre."], "The strongest argument supplies relevant evidence about the identified problem, a plausible mechanism and feasibility; the alternatives rely on opinion or weak relevance.", 0),
  mc("ucat-dm-challenge-argument-02", "A university considers making lecture attendance compulsory. Which argument most directly challenges the proposal?", "Evidence from comparable courses shows compulsory attendance raises presence but not attainment, while monitoring consumes substantial teaching time.", ["Some students dislike rules in general.", "Lectures have existed for many years.", "Attendance can be measured electronically."], "The keyed argument addresses effectiveness and cost directly, rather than preference, tradition or implementation possibility alone.", 1),
  mc("ucat-dm-challenge-argument-03", "A hospital considers extending visiting hours. Which evidence is most relevant to deciding whether the change should proceed?", "A controlled pilot comparing patient rest, staff workload and family access under current and extended hours.", ["A survey asking visitors whether they would personally like longer hours.", "The number of hospitals in the country that publish visiting-hour policies online.", "The historical date on which the present visiting hours were introduced."], "A controlled pilot directly measures the main benefits and costs of the proposed change.", 2),
  mc("ucat-dm-challenge-argument-04", "A school proposes replacing printed textbooks with tablets. Which consideration is most important for evaluating the proposal?", "Whether learning outcomes and total costs, including maintenance and replacement, compare favourably with the current system.", ["Whether tablets are newer technology than textbooks.", "Whether students generally enjoy using electronic devices.", "Whether other schools have recently purchased tablets."], "The decision requires evidence about educational effectiveness and full costs, not novelty, popularity or imitation.", 3),
  mc("ucat-dm-challenge-argument-05", "A company argues that remote work should expand because productivity rose after a trial began. Which fact would most weaken that reasoning?", "The trial coincided with removal of a low-productivity product line, and teams that did not adopt remote work showed a similar productivity rise.", ["Some employees preferred working remotely.", "The company used video meetings during the trial.", "Productivity was measured monthly rather than weekly."], "A simultaneous change plus a similar control-group improvement provides a strong rival explanation for the observed increase.", 0),
  mc("ucat-dm-challenge-argument-06", "A charity claims a new advertising campaign increased donations because donations rose 15% after launch. Which additional evidence would most strengthen the claim?", "Regions randomly exposed to the campaign increased donations more than otherwise comparable regions not yet exposed.", ["The campaign received positive comments online.", "Total charitable giving nationally also rose during the same period.", "The campaign used more images than the previous one."], "A comparison that isolates exposure to the campaign best supports a causal interpretation.", 1),
  mc("ucat-dm-challenge-argument-07", "A town plans to close a small library because visits have fallen. Which information is most important before deciding whether closure is justified?", "Whether reduced visits reflect lower community need or temporary factors, and what alternative access would exist for users who rely on the branch.", ["Whether the library building is older than the town hall.", "Whether neighbouring towns use the same library-management software.", "Whether the branch has changed its logo recently."], "The key issue is whether usage reflects genuine need and what consequences closure would have, not irrelevant administrative details.", 2),
  mc("ucat-dm-challenge-argument-08", "A college says a new tutoring programme is effective because participants improved more than non-participants. Which limitation matters most?", "Students chose whether to participate, so prior motivation or difficulty could differ between groups and partly explain the improvement.", ["The programme has a memorable name.", "Tutors used both paper and digital resources.", "The final results were reported as percentages."], "Self-selection creates a direct alternative explanation for the observed difference, unlike the other features.", 3),
]
