import type { TestQuestion } from "@/lib/oxbridge-data"

function q(id: string, prompt: string, options: [string, string, string, string], answer: number, explanation: string): TestQuestion {
  return { id, test: "UCAT", section: "Decision Making", difficulty: "Stretch", prompt, options, answer, explanation }
}

export const ucatDmLogicalPuzzleBank: TestQuestion[] = [
  q("ucat-dm-verified-puzzle-01", "Five talks J, K, L, M and N are scheduled in five consecutive slots. J is before K, K is before L, L is before M, and M is before N. Which talk is in slot 3?", ["L", "K", "M", "J"], 0, "The constraints give the unique order J-K-L-M-N. L is therefore in slot 3."),
  q("ucat-dm-verified-puzzle-02", "Four researchers P, Q, R and S sit in a row of four seats. P sits somewhere left of Q. R sits immediately right of P. S is not at either end. Which seating order is possible?", ["P, R, S, Q", "S, P, R, Q", "P, S, R, Q", "Q, P, R, S"], 0, "P-R-S-Q satisfies all three conditions. In the second option S is at an end; the third breaks the P-R adjacency; the fourth places P to the right of Q."),
  q("ucat-dm-verified-puzzle-03", "A courier must visit W, X, Y and Z exactly once after leaving the depot. W must be visited before Y. X must be visited after Z. Y cannot be the final stop. Which route order is valid?", ["W, Y, Z, X", "Z, X, Y, W", "Y, W, Z, X", "W, Z, X, Y"], 0, "W-Y-Z-X has W before Y, Z before X, and Y is not final. Every other route breaks at least one condition."),
  q("ucat-dm-verified-puzzle-04", "Six books A, B, C, D, E and F are arranged left to right. A is immediately left of B. E is somewhere left of D. C is at the far left and F at the far right. Which pair could occupy positions 3 and 4 respectively?", ["A then B", "D then E", "B then A", "F then D"], 0, "A-B can occupy positions 3 and 4 with E in position 2 and D in position 5. The other pairs contradict the required order or a fixed end position."),
  q("ucat-dm-verified-puzzle-05", "Five interviews C, A, E, D and B use slots 1 to 5. C is before A, A is before E, D is immediately before B, C is in slot 1, and D is in slot 4. Which interview is in slot 3?", ["E", "A", "D", "B"], 0, "D-B must occupy slots 4-5. With C in slot 1 and C<A<E, A and E must occupy slots 2-3 respectively. E is therefore third."),
  q("ucat-dm-verified-puzzle-06", "Laboratory tasks H, J, K and L must be completed one at a time. H is before J, J is before K, and K is before L. Which task is completed third?", ["K", "J", "L", "H"], 0, "The constraints form the unique order H-J-K-L, so K is third."),
  q("ucat-dm-verified-puzzle-07", "Training sessions R, S, T and U are placed on Monday to Thursday, one per day. R is earlier than T. U is on Thursday. S is not on Monday. If T is on Wednesday, when is R?", ["Monday", "Tuesday", "Wednesday", "Thursday"], 0, "With T on Wednesday and U on Thursday, Monday and Tuesday remain for R and S. Since S cannot be Monday, R must be Monday."),
  q("ucat-dm-verified-puzzle-08", "Rooms 1, 2, 3 and 4 are assigned to teams A, B, C and D, one team per room. A has a lower-numbered room than C. B is in room 4. D is not in room 1. Which team must be in room 1?", ["A", "C", "D", "B"], 0, "B is already in room 4 and D cannot be in room 1. C cannot be in room 1 because A must have a lower-numbered room. Therefore A must be in room 1."),
  q("ucat-dm-verified-puzzle-09", "Five runners V, W, X, Y and Z finish in different positions. X finishes ahead of Y but behind W. V finishes behind Y. Z finishes ahead of W. Who finishes third?", ["X", "W", "Y", "Z"], 0, "The constraints force Z-W-X-Y-V. X is therefore third."),
  q("ucat-dm-verified-puzzle-10", "A museum displays sculptures K, L, M, N and P in five numbered positions. M is immediately before N. K is somewhere before M. P is after N. Which sculpture could be in position 5?", ["P", "M", "K", "N"], 0, "P must be after N and can occupy position 5. M needs N after it, K needs M after it, and N needs P after it, so none of those can be fifth."),
  q("ucat-dm-verified-puzzle-11", "Four staff members E, F, G and H cover four successive shifts. E works before F. G works after F. H works before G. If F works the second shift, who must work the first shift?", ["E", "H", "G", "F"], 0, "E must be before F. Since F is second, the only earlier shift is shift 1, so E must be first."),
  q("ucat-dm-verified-puzzle-12", "Lectures A, C, D, G and F are ordered from first to fifth. A is before C, C is before D, D is before G, and G is before F. Which lecture is fourth?", ["G", "D", "C", "F"], 0, "The constraints give the unique order A-C-D-G-F. G is fourth."),
  q("ucat-dm-verified-puzzle-13", "Four parcels J, K, M and N are loaded in positions 1 to 4. J is loaded before M. N is immediately after J. K is not in position 4. Which loading order is possible?", ["J, N, K, M", "K, J, M, N", "J, K, M, N", "N, J, K, M"], 0, "J-N-K-M satisfies the J-N adjacency, puts J before M and keeps K out of position 4. Each other option breaks at least one rule."),
  q("ucat-dm-verified-puzzle-14", "Five cases P, Q, R, S and T are heard in order. P is before Q, Q is before R, R is before S, and S is before T. Which case is heard third?", ["R", "Q", "S", "P"], 0, "The conditions give the unique order P-Q-R-S-T. R is third."),
]
