"use client"

import Link from "next/link"
import { useEffect, useState } from "react"
import { ArrowLeft, Copy, Loader2, RefreshCw, School, Trash2, Users } from "lucide-react"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"

type Member={userId:string;role:"owner"|"member";joinedAt:string;displayName:string;email:string}
type Organization={id:string;name:string;join_code:string;seat_limit:number;status:string;owner_user_id:string;isOwner:boolean;seatsUsed:number;seatsRemaining:number;members:Member[]}
type SchoolData={tier:string;organization:Organization|null}
async function post(body:Record<string,unknown>){const response=await fetch("/api/school",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const data=await response.json() as {error?:string;ok?:boolean;joinCode?:string};if(!response.ok)throw new Error(data.error||"Request failed");return data}

export default function SchoolSeatsPage(){
 const[data,setData]=useState<SchoolData|null>(null);const[loading,setLoading]=useState(true);const[error,setError]=useState("");const[code,setCode]=useState("");const[name,setName]=useState("")
 async function load(){setLoading(true);setError("");try{const response=await fetch("/api/school",{cache:"no-store"});const payload=await response.json() as SchoolData&{error?:string};if(!response.ok)throw new Error(payload.error||"Could not load School seats");setData(payload);setName(payload.organization?.name??"")}catch(cause){setError(cause instanceof Error?cause.message:"Could not load School seats")}finally{setLoading(false)}}
 useEffect(()=>{void load()},[])
 async function join(){try{await post({action:"joinSchool",joinCode:code});setCode("");await load()}catch(cause){setError(cause instanceof Error?cause.message:"Could not join school")}}
 async function remove(userId:string){if(!window.confirm("Remove this account from the School licence? Their personal account and progress will remain intact."))return;try{await post({action:"removeSchoolMember",userId});await load()}catch(cause){setError(cause instanceof Error?cause.message:"Could not remove member")}}
 async function rename(){try{await post({action:"updateSchoolName",name});await load()}catch(cause){setError(cause instanceof Error?cause.message:"Could not update school name")}}
 async function regenerate(){if(!window.confirm("Generate a new School join code? The old code will stop working."))return;try{await post({action:"regenerateSchoolCode"});await load()}catch(cause){setError(cause instanceof Error?cause.message:"Could not regenerate code")}}
 const org=data?.organization
 return <main className="min-h-screen bg-[#f5f7f7] text-[#172b3a]"><header className="border-b bg-white"><div className="mx-auto flex max-w-5xl items-center justify-between px-4 py-4"><Button asChild variant="ghost"><Link href="/account"><ArrowLeft/>Account</Link></Button><Badge variant="outline"><School className="size-3.5"/>School seats</Badge></div></header><div className="mx-auto max-w-5xl space-y-6 px-4 py-8">
 <section><p className="text-xs font-bold uppercase tracking-[.18em] text-[#147d91]">School licence</p><h1 className="mt-2 font-serif text-4xl font-bold">Five separate accounts. One subscription.</h1><p className="mt-3 max-w-3xl text-slate-600">The School plan includes 5 individual logins. Each person keeps their own password, Tutor memory, interview history and progress. Never share one login between users.</p></section>
 {error&&<div className="rounded-2xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-950">{error}</div>}
 {loading&&!data?<Card><CardContent className="flex items-center gap-3 p-6"><Loader2 className="animate-spin"/>Loading School licence…</CardContent></Card>:org?<>
 <section className="grid gap-4 md:grid-cols-3"><Card className="border-0 bg-[#102a43] text-white"><CardHeader><CardDescription className="text-white/60">Seats used</CardDescription><CardTitle className="font-serif text-4xl">{org.seatsUsed}/{org.seat_limit}</CardTitle></CardHeader></Card><Card><CardHeader><CardDescription>Seats available</CardDescription><CardTitle className="font-serif text-4xl">{org.seatsRemaining}</CardTitle></CardHeader></Card><Card><CardHeader><CardDescription>Your role</CardDescription><CardTitle className="font-serif text-2xl">{org.isOwner?"School owner":"School member"}</CardTitle></CardHeader></Card></section>
 {org.isOwner&&<Card><CardHeader><CardTitle className="font-serif text-2xl">Invite your other accounts</CardTitle><CardDescription>Ask each person to create their own Oxbridge login, then give them this School code. The code activates one of your 5 included seats.</CardDescription></CardHeader><CardContent className="space-y-4"><div className="flex flex-col gap-2 sm:flex-row"><div className="flex-1 rounded-xl border bg-slate-50 px-4 py-3 font-mono text-xl font-bold tracking-[.15em]">{org.join_code}</div><Button variant="outline" onClick={()=>void navigator.clipboard.writeText(org.join_code)}><Copy/>Copy code</Button><Button variant="outline" onClick={()=>void regenerate()}><RefreshCw/>New code</Button></div><div className="flex gap-2"><input className="h-10 flex-1 rounded-md border bg-white px-3 text-sm" value={name} onChange={e=>setName(e.target.value)} placeholder="School / organisation name"/><Button onClick={()=>void rename()} disabled={!name.trim()}>Save name</Button></div></CardContent></Card>}
 <Card><CardHeader><CardTitle className="font-serif text-2xl">Accounts on this licence</CardTitle><CardDescription>Removing a seat only removes School access. It does not delete that person's account or preparation history.</CardDescription></CardHeader><CardContent className="space-y-2">{org.members.map(member=><div key={member.userId} className="flex flex-col justify-between gap-3 rounded-xl border bg-white p-4 sm:flex-row sm:items-center"><div><div className="flex items-center gap-2"><strong>{member.displayName}</strong><Badge variant="outline">{member.role}</Badge></div><p className="text-sm text-slate-500">{member.email}</p></div>{org.isOwner&&member.role!=="owner"&&<Button size="sm" variant="outline" onClick={()=>void remove(member.userId)}><Trash2/>Remove seat</Button>}</div>)}</CardContent></Card>
 <div className="flex flex-wrap gap-2"><Button asChild><Link href="/school-dashboard"><Users/>School Dashboard</Link></Button><Button asChild variant="outline"><Link href="/school-classroom">Student Classroom</Link></Button></div>
 </>:<Card><CardHeader><CardTitle className="font-serif text-2xl">Join a School licence</CardTitle><CardDescription>If your school has purchased the School plan, enter the School code supplied by the subscription owner. This is different from a cohort/class code.</CardDescription></CardHeader><CardContent className="flex flex-col gap-2 sm:flex-row"><input className="h-10 flex-1 rounded-md border bg-white px-3 font-mono text-sm uppercase tracking-[.12em]" value={code} onChange={e=>setCode(e.target.value.toUpperCase())} placeholder="SCH-XXXXXXXX"/><Button onClick={()=>void join()} disabled={!code.trim()}>Activate School seat</Button></CardContent></Card>}
 </div></main>
}
