"use client"

import { useEffect, useState } from "react"
import Link from "next/link"
import { ArrowLeft, Plus, Search, Trash2 } from "lucide-react"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"
import { NativeSelect, NativeSelectOption } from "@/components/ui/native-select"
import { EVIDENCE_KEY, type EvidenceItem } from "@/lib/digital-twin-2"

const types:EvidenceItem["type"][]=["statement","written-work","reading","research","certificate","competition","reflection"]
const fresh=():EvidenceItem=>({id:crypto.randomUUID(),type:"reading",title:"",detail:"",tags:[],createdAt:new Date().toISOString()})
export default function EvidenceLockerPage(){const [items,setItems]=useState<EvidenceItem[]>([]);const [draft,setDraft]=useState(fresh());const [tags,setTags]=useState("");const [query,setQuery]=useState("");useEffect(()=>{try{const x=JSON.parse(localStorage.getItem(EVIDENCE_KEY)||"[]");if(Array.isArray(x))setItems(x)}catch{}},[]);const persist=(next:EvidenceItem[])=>{setItems(next);localStorage.setItem(EVIDENCE_KEY,JSON.stringify(next))};const save=()=>{if(!draft.title.trim())return;persist([{...draft,tags:tags.split(",").map(x=>x.trim()).filter(Boolean)},...items]);setDraft(fresh());setTags("")};const visible=items.filter(x=>`${x.title} ${x.detail} ${x.tags.join(" ")}`.toLowerCase().includes(query.toLowerCase()));return <main className="min-h-screen bg-[#f5f7f7] px-4 py-8 text-[#172b3a]"><div className="mx-auto max-w-6xl space-y-5"><Link href="/digital-twin" className="inline-flex items-center gap-2 text-sm font-semibold"><ArrowLeft className="size-4"/>Digital Twin</Link><div><h1 className="font-serif text-4xl font-bold">Application Evidence Locker</h1><p className="mt-2 text-slate-600">Keep the evidence behind your application in one place so the Tutor can turn it into future questions and revision targets.</p></div><Card><CardHeader><CardTitle>Add evidence</CardTitle></CardHeader><CardContent className="grid gap-3 md:grid-cols-2"><NativeSelect value={draft.type} onChange={e=>setDraft({...draft,type:e.target.value as EvidenceItem["type"]})}>{types.map(t=><NativeSelectOption key={t} value={t}>{t}</NativeSelectOption>)}</NativeSelect><Input placeholder="Title" value={draft.title} onChange={e=>setDraft({...draft,title:e.target.value})}/><Textarea className="md:col-span-2" placeholder="What happened, what you learned, and what you could defend about it..." value={draft.detail} onChange={e=>setDraft({...draft,detail:e.target.value})}/><Input className="md:col-span-2" placeholder="Tags, comma separated" value={tags} onChange={e=>setTags(e.target.value)}/><Button onClick={save} className="md:col-span-2"><Plus/>Save evidence</Button></CardContent></Card><div className="relative"><Search className="absolute left-3 top-3 size-4 text-slate-400"/><Input className="pl-9" placeholder="Search evidence..." value={query} onChange={e=>setQuery(e.target.value)}/></div><div className="grid gap-4 md:grid-cols-2">{visible.map(x=><Card key={x.id}><CardHeader><div className="flex justify-between gap-3"><div><p className="text-xs uppercase text-[#147d91]">{x.type}</p><CardTitle>{x.title}</CardTitle></div><Button size="icon" variant="ghost" onClick={()=>persist(items.filter(i=>i.id!==x.id))}><Trash2 className="size-4"/></Button></div></CardHeader><CardContent><p className="text-sm leading-6">{x.detail}</p><div className="mt-3 flex flex-wrap gap-1">{x.tags.map(t=><span key={t} className="rounded-full bg-slate-100 px-2 py-1 text-xs">{t}</span>)}</div></CardContent></Card>)}</div></div></main>}
