"use client"

import { useEffect, useState } from "react"
import Link from "next/link"
import { ArrowLeft, Plus, Trash2 } from "lucide-react"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"
import { NativeSelect, NativeSelectOption } from "@/components/ui/native-select"
import { SOURCE_NOTEBOOK_KEY, type SourceNote } from "@/lib/digital-twin-2"

const blank=()=>({id:crypto.randomUUID(),title:"",sourceType:"book" as SourceNote["sourceType"],centralArgument:"",strongestEvidence:"",weakness:"",questionRaised:"",connection:"",opinion:"",createdAt:new Date().toISOString()})
export default function SourceNotebookPage(){const [items,setItems]=useState<SourceNote[]>([]);const [draft,setDraft]=useState<SourceNote>(blank());useEffect(()=>{try{const x=JSON.parse(localStorage.getItem(SOURCE_NOTEBOOK_KEY)||"[]");if(Array.isArray(x))setItems(x)}catch{}},[]);const save=()=>{if(!draft.title.trim())return;const next=[draft,...items];setItems(next);localStorage.setItem(SOURCE_NOTEBOOK_KEY,JSON.stringify(next));setDraft(blank())};const remove=(id:string)=>{const next=items.filter(x=>x.id!==id);setItems(next);localStorage.setItem(SOURCE_NOTEBOOK_KEY,JSON.stringify(next))};return <main className="min-h-screen bg-[#f5f7f7] px-4 py-8 text-[#172b3a]"><div className="mx-auto max-w-6xl space-y-5"><Link href="/digital-twin" className="inline-flex items-center gap-2 text-sm font-semibold"><ArrowLeft className="size-4"/>Digital Twin</Link><div><h1 className="font-serif text-4xl font-bold">Academic Source Notebook</h1><p className="mt-2 text-slate-600">Turn every source into an argument you can compare, criticise and defend.</p></div><Card><CardHeader><CardTitle>Add a source</CardTitle></CardHeader><CardContent className="grid gap-3 md:grid-cols-2"><Input placeholder="Title" value={draft.title} onChange={e=>setDraft({...draft,title:e.target.value})}/><NativeSelect value={draft.sourceType} onChange={e=>setDraft({...draft,sourceType:e.target.value as SourceNote["sourceType"]})}>{["book","article","lecture","paper","podcast","video"].map(x=><NativeSelectOption key={x} value={x}>{x}</NativeSelectOption>)}</NativeSelect>{[["centralArgument","Central argument"],["strongestEvidence","Strongest evidence"],["weakness","Weakness / limitation"],["questionRaised","Question it raises"],["connection","Connection to another idea/source"],["opinion","Your current view"]].map(([k,p])=><Textarea key={k} placeholder={p} value={String(draft[k as keyof SourceNote]||"")} onChange={e=>setDraft({...draft,[k]:e.target.value})}/>)}<Button onClick={save} className="md:col-span-2"><Plus/>Save source note</Button></CardContent></Card><div className="grid gap-4 md:grid-cols-2">{items.map(x=><Card key={x.id}><CardHeader><div className="flex items-start justify-between gap-3"><div><p className="text-xs uppercase text-[#147d91]">{x.sourceType}</p><CardTitle>{x.title}</CardTitle></div><Button size="icon" variant="ghost" onClick={()=>remove(x.id)}><Trash2 className="size-4"/></Button></div></CardHeader><CardContent className="space-y-2 text-sm"><p><b>Argument:</b> {x.centralArgument||"—"}</p><p><b>Evidence:</b> {x.strongestEvidence||"—"}</p><p><b>Weakness:</b> {x.weakness||"—"}</p><p><b>Connection:</b> {x.connection||"—"}</p><p><b>Your view:</b> {x.opinion||"—"}</p></CardContent></Card>)}</div></div></main>}
