"use client"

import Link from "next/link"
import { useState } from "react"
import { ArrowLeft, CheckCircle2, ExternalLink, Loader2, RefreshCw, ShieldAlert } from "lucide-react"
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"

type Row={id:string;label:string;url:string;status:number;ok:boolean;matched:string[];expectedCount:number;looksExpected:boolean;finalUrl:string;error?:string}
type Report={checkedAt:string;results:Row[];note:string}
type ApiError={error?:string}

export default function SourceHealthPage(){
 const [report,setReport]=useState<Report|null>(null);const [busy,setBusy]=useState(false);const [error,setError]=useState("")
 const check=async()=>{setBusy(true);setError("");try{const res=await fetch("/api/source-health",{cache:"no-store"});const data:Report|ApiError=await res.json() as Report|ApiError;if(!res.ok)throw new Error("error" in data&&data.error?data.error:"Check failed");setReport(data as Report)}catch(e){setError(e instanceof Error?e.message:"Check failed")}finally{setBusy(false)}}
 return <main className="min-h-screen bg-[#f6f8f8] text-[#172b3a]"><header className="border-b bg-white"><div className="mx-auto flex max-w-6xl items-center justify-between px-4 py-4 sm:px-6"><Button asChild variant="ghost"><Link href="/requirements"><ArrowLeft/>Requirements</Link></Button><Badge variant="outline"><RefreshCw className="size-3.5"/>Source watcher</Badge></div></header><div className="mx-auto max-w-6xl px-4 py-8 sm:px-6"><section className="mb-6"><p className="text-xs font-bold uppercase tracking-[.18em] text-[#147d91]">Official information watcher</p><h1 className="mt-2 font-serif text-4xl font-bold">Flag official sources that need a human re-check.</h1><p className="mt-2 max-w-3xl text-slate-600">This watcher checks whether key official pages are reachable and still contain expected identifying terms. It deliberately does not treat a successful check as proof that every requirement is unchanged.</p></section><div className="mb-5"><Button onClick={check} disabled={busy}>{busy?<Loader2 className="animate-spin"/>:<RefreshCw/>}{busy?"Checking official sources…":"Run source check"}</Button></div>{error&&<Alert className="mb-5 border-red-200 bg-red-50"><ShieldAlert/><AlertTitle>Could not complete source check</AlertTitle><AlertDescription>{error}</AlertDescription></Alert>}{report&&<><section className="mb-5 grid gap-4 sm:grid-cols-3"><Metric label="Sources checked" value={String(report.results.length)} note={new Date(report.checkedAt).toLocaleString("en-GB")}/><Metric label="Look expected" value={String(report.results.filter(x=>x.looksExpected).length)} note="Reachable + identifying terms present"/><Metric label="Needs review" value={String(report.results.filter(x=>!x.looksExpected).length)} note="Unreachable or content signature changed"/></section><Alert className="mb-5"><ShieldAlert/><AlertTitle>Human verification still required</AlertTitle><AlertDescription>{report.note}</AlertDescription></Alert><Card className="shadow-none"><CardHeader><CardTitle className="font-serif text-2xl">Source status</CardTitle></CardHeader><CardContent className="space-y-2">{report.results.map(row=><div key={row.id} className={`grid gap-3 rounded-xl border p-4 md:grid-cols-[minmax(0,1fr)_auto] ${row.looksExpected?"border-emerald-200 bg-emerald-50":"border-amber-200 bg-amber-50"}`}><div><div className="flex flex-wrap items-center gap-2"><strong>{row.label}</strong><Badge variant="outline">HTTP {row.status||"—"}</Badge>{row.looksExpected?<Badge><CheckCircle2 className="size-3"/>Looks expected</Badge>:<Badge variant="outline"><ShieldAlert className="size-3"/>Review</Badge>}</div><p className="mt-1 text-xs text-slate-500">Matched {row.matched.length}/{row.expectedCount} expected identifying terms{row.error?` · ${row.error}`:""}</p></div><Button asChild size="sm" variant="outline"><a href={row.finalUrl||row.url} target="_blank" rel="noreferrer">Open official page <ExternalLink/></a></Button></div>)}</CardContent></Card></>}</div></main>
}
function Metric({label,value,note}:{label:string;value:string;note:string}){return <Card className="shadow-none"><CardHeader className="pb-2"><CardDescription>{label}</CardDescription><CardTitle className="font-serif text-3xl">{value}</CardTitle></CardHeader><CardContent><p className="text-xs text-slate-500">{note}</p></CardContent></Card>}
